### ISSUE TITLE
I cannot access to mixin funtions

### ISSUE THREAD

**Issue by mstfkhazaal** [inertiajs/inertia#1482] opened 2023-03-05 18:14 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.2

### Describe the problem:

app.js
```
import { createApp, h } from 'vue'
import { createInertiaApp } from '@inertiajs/vue3'
import {base} from '@/base'

createInertiaApp({
  resolve: name => {
    const pages = import.meta.glob('./Pages/**/*.vue', { eager: true })
    return pages[`./Pages/${name}.vue`]
  },
  setup({ el, App, props, plugin }) {
    createApp({ render: () => h(App, props) })
      .use(plugin)
      .mixin(base)
      .mount(el)
  },
})
```
base.js
```
export const base = {
    methods: {
        /**
         * Translate the given key.
         */
        tr(key, replace = {}) {
            let translation = this.$page.props.language[key]
                ? this.$page.props.language[key]
                : key;

            Object.keys(replace).forEach(function (key) {
                translation = translation.replace(':' + key, replace[key])
            });

            return translation
        },
   
    
    }
};
```

Login.vue
```
<script lang="ts" setup>
console.log(this.tr('welcome')); /// Error
</script>
<template>
<p>{{tr('welcome')}}</p> // Work
</template>

```

**I cannot access to method tr from setup**

**Comment by mstfkhazaal** [comment] 2023-03-30 09:17
> i have the same problem. did you find a solution?

I've not used mixin but I've used another alternative external function which instead of using $this.page I've used usePage()

**Comment by codeallday31** [comment] 2023-04-02 18:21
I think this is the normal behavior of vue3 composition api and options api .. for more details kindly check here
https://github.com/vuejs/core/issues/1866#issuecomment-674881439

you should use options api for using mixins then just call this.route and it will be working

**Comment by reinink** [comment] 2023-07-28 01:47
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:47 UTC
