### ISSUE TITLE
Module '"@inertiajs/inertia-react"' has no exported member 'Head'.

### ISSUE THREAD

**Issue by jrafaaael** [inertiajs/inertia#1094] opened 2022-02-10 19:51 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-react` version: 0.7.0

### Describe the problem:
When I try to use the component `Head`, the error of the title appear.

### Steps to reproduce:
1. Import the component as is described in the documentation: https://inertiajs.com/title-and-meta
2. See the error

### Considerations
I had to delete the `jsconfig.json` file because with that file, my code editors (VSCode, neovim) couldn't correctly display errors like components not imported or variables not declared

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
Labels: react
