### ISSUE TITLE
File did not sent with form patch submit

### ISSUE THREAD

**Issue by As1fAli** [inertiajs/inertia#1066] opened 2022-01-26 14:33 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue3` version: 0.5.2

### Describe the problem:
 Form submit with patch (this.$inertia.form.patch()) does not upload file. I managed to upload using "post" method with setting '_method' set as 'patch'

### Steps to reproduce:
  Submit a file using this.$inertia.form with patch request

```
data() {
  return {
    form: this.$inertia.form({
      photo: null, 
    }),
  };
},
methods: {
  change(e) {
    this.form.photo = e.target.files[0];
  },
  submitForm() {
    this.form.patch(url);
  },
},

**Comment by blogui91** [comment] 2022-01-27 03:38
@As1fAli 
According to the documentation, it says you have to send it this way

```Inertia.post(`/users/${user.id}`, {
  _method: 'put',
  avatar: form.avatar,
})```

https://inertiajs.com/file-uploads

**Comment by ajnsn** [comment] 2022-01-27 14:19
Hey @As1fAli, as you already figured out, you need to submit a `PATCH` request with the `_method` inside the payload. This is nothing related to Inertia, see [comment over here.](https://github.com/inertiajs/inertia-laravel/issues/180#issuecomment-719998370)

**Comment by As1fAli** [comment] 2022-02-05 18:08
Hey @ajnsn , Thanks for your response. I was thinking as Inertia is mostly suitable for Laravel, It would be great if inertia itself add `_method` inside payload in case of `PUT`, `PATCH` OR `DELETE` form submissions

**Comment by ajnsn** [comment] 2022-02-05 20:01
Yes, that's exactly the long-standing PHP issue. As Inertia is not PHP-only, I assume this will probably stay like it is.

**Comment by reinink** [comment] 2023-07-28 01:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:54 UTC
