### ISSUE TITLE
The GET method is not supported for this route. Supported methods: PATCH, DELETE.

### ISSUE THREAD

**Issue by puncoz** [inertiajs/inertia#1101] opened 2022-02-16 12:04 UTC
### Versions:

- Laravel: 8
- Laravel Jetstream: 2.6
- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:
I have used `HandleInertiaRequests` middleware in HTTP kernel as everybody suggested in other similar issues. That solves the same issue with PUT/PATCH/DELETE operation as expected.

But now I find a weird issue with the same error right after login. I am using laravel jetstream's default authentication without any significant modification. 

### Steps to reproduce:

1. Login into the application
2. right after login, without a manual page refresh, perform PUT/DELETE/PATCH operation. You can browse other pages (in intertia without page refresh)

eg: After login, click on delete in the list of users which call following: 

```
Inertia.delete(route("users.destroy", userId))
```

Now, It will throw the following exception
![image](https://user-images.githubusercontent.com/7767424/154259661-5d457d90-1476-4e89-bee9-e0d26f0426d5.png)

If we refresh the application, this exception will not come again.

The wried thing I found in `network` tab of chrome dev tools.

Here, when we click on delete action right after login without refresh:
The first request is an actual DELETE request. and the second one is GET request (don't know why it is redirecting to the same route)

![image](https://user-images.githubusercontent.com/7767424/154260146-468cdb57-ae5f-4603-ab85-2fccf085dac5.png)

But after refreshing, its different:
![image](https://user-images.githubusercontent.com/7767424/154260398-22ac61ea-e570-49a3-8800-f442fcdefc2e.png)

Here, after the first request with DELETE, the second route of `/positions?.....` . And this is the correct one.

I don't know why it's different right after login.

**Comment by puncoz** [comment] 2022-02-20 00:04
yes, @craigrileyuk I agree with you. But in my case redirection route is different.

If my delete request is in the following route:
`[DELETE] /users/20`

and in the controller, it is redirecting back to `[GET] /users`

But right after login, no matter what there is in the controller, it is redirecting to `[GET] /users/20` which is the delete route.

And after refreshing, it is working fine with intended redirection of `[GET] /users`

**Comment by craigrileyuk** [comment] 2022-03-03 10:57
Can you post the code for your Controller that handles the DELETE route for /users/{id}

**Comment by puncoz** [comment] 2022-03-03 15:35
The controller is pretty much straightforward.

Here is the code:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/7767424/156597581-5e112ff2-cdde-454f-91f9-9b8b113dfccc.png">

**Comment by puncoz** [comment] 2022-03-06 13:56
**Update**: I fixed it by manually modifying the response of Login and Logout by extending default Jetstream/fortify's classes.

LoginResponse.php
```php
use Illuminate\Http\Request;
use Laravel\Fortify\Contracts\LoginResponse as LoginResponseContract;
use Laravel\Fortify\Fortify;
use Symfony\Component\HttpFoundation\Response;

class LoginResponse implements LoginResponseContract
{
    public function toResponse($request)
    {
        $url = redirect()->intended(Fortify::redirects('login'))->getTargetUrl();

        return $request->wantsJson() ? response()->json(['two_factor' => false]) : inertia()->forceRedirect($url);
    }
}
```

and LogoutResponse.php
```php
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Laravel\Fortify\Contracts\LogoutResponse as LogoutResponseContract;
use Laravel\Fortify\Fortify;
use Symfony\Component\HttpFoundation\Response;

class LogoutResponse implements LogoutResponseContract
{
    public function toResponse($request)
    {
        $url = Fortify::redirects('logout', '/');

        return $request->wantsJson() ? new JsonResponse('', 204) : inertia()->forceRedirect($url);
    }
}
```

Register these extended classes in the service provider as:

```php
    public function register()
    {
        $this->app->bind(\Laravel\Fortify\Contracts\LoginResponse::class, LoginResponse::class);
        $this->app->bind(\Laravel\Fortify\Contracts\LogoutResponse::class, LogoutResponse::class);
    }
```

I have used manual `forceRedirect` as inertia macro. which you can register as follows in the service provider.

```php
        Inertia::macro(
            'forceRedirect',
            function (string $url) {
                return response('', Response::HTTP_CONFLICT)->header('x-inertia-location', $url);
            }
        );
```

Here, all I have done is forcefully refresh the page after login and logout, which solved the above-mentioned problem for me.

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
