### ISSUE TITLE
Return type of the `Link` component is incorrect

### ISSUE THREAD

**Issue by Gregory-Gerard** [inertiajs/inertia#1511] opened 2023-04-09 12:57 UTC
### Version:

- `@inertiajs/react` version: 1.0.2

### Describe the problem:

`Link` component forward ref to `a` (or `as` prop) element. However, the typing of the `Link` component does not allow the use of the `ref` property.

Wrong type is here: https://github.com/inertiajs/inertia/blob/5c9c2707dc5f2f1f36d8eff99d731b5e42dab021/packages/react/src/Link.ts#L40

This tells TypeScript that `Link` is just a `FunctionComponent` when in fact it returns a component that can take a ref.

### Steps to reproduce:

```typescript
const someRef = useRef<HTMLLinkElement>(null);
const Test = <Link href={'/'} ref={someRef} />;
```

This code makes TypeScript angry with TS2769 alert.

### Possible solution

`InertiaLink` return type could be removed to just let TypeScript infer correct return type using `forwardRef`. If this solution suits you, I can create the PR.

Thanks!

**Comment by reinink** [comment] 2023-07-28 01:39
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:39 UTC
Labels: react
