### ISSUE TITLE
Inertia link does not reload the page form data

### ISSUE THREAD

**Issue by tanthammar** [inertiajs/inertia#170] opened 2020-03-31 20:46 UTC
If I am on an the `edit` page for **Organizer A** 
and click on an inertia link to `edit` **Organizer B**.
Inertia replaces the url **but the form is not reloaded** and keeps Organizer A data
(and vue blows up)
(If I click on the link from any other page it works as expected.)

Example href: https://test-site.test/app/organizers/org-YSMqnF-L8VSq8s5jzZ-nB/edit
```js
<inertia-link :href="app.organizers.edit " method="get">{{organizer.name}}</inertia-link>
```

OrganizerController@edit
```php
public function edit(Organizer $organizer)
{
    return inertia('Organizers/Edit', [
        'organizer' => $organizer,
    ]);
}
```

**Comment by reinink** [comment] 2020-10-16 16:03
Hey @tanthammar!

We're trying to clean up some old issues. Do you know if this problem is still relevant?

**Comment by IvanBernatovic** [comment] 2020-10-18 18:16
@reinink I'm running into a similar issue when I submit the PUT request and redirect back to a form. Maybe I'm doing something wrong here but here's the code and steps for setup and reproducing the issue. https://github.com/IvanBernatovic/inertia-vue-issue
I reuse forms by extracting them into a separate component, that way I use the same component for create and edit form. If I put `:key="Math.random().toString(36)"` on the form component, that fixes the issue. Btw. I'm using Laravel Jetstream app in the example but it shouldn't matter.

**Comment by reinink** [comment] 2020-10-20 11:43
@IvanBernatovic So, this is actually being caused by Jetstream, not Inertia.js. It's because Jetstream defaults form submission to `{ resetOnSuccess: true }`, which is actually problematic if you submit a form back to the **same page**. Basically what happens is Jetstream captures the props on the initial component load and saves them in local memory. Then, when you make a request to submit the form, it returns back to the **same component**, which still has those original values in memory, and Jetstream restores those values.

Update your `UserForm.vue` file to fix this:

```js
form: this.$inertia.form({
  name: this.user?.name || "",
  email: this.user?.email || "",
}, {
  resetOnSuccess: false,
}),
```

IMHO, Jetstream shouldn't default `resetOnSuccess` to `true`, but rather this should be an opt-in thing you use when it's needed (ie. resetting password inputs back to blank).

**Comment by reinink** [comment] 2020-10-20 11:55
So, I am going to close this issue, because I actually think I remember what was wrong here, and it's been fixed.

The issue had to do with component state when making `GET` requests to the same component. Ping CRM actually suffered from this bug originally as well. This was fixed by introducing the [preserveState](https://github.com/inertiajs/inertia-vue/commit/ece756015ac94749ca8f8a69c80e74038cf8d78c) feature.

My only concern is that this issue was posted long after that feature was added. The only thing I can think is that @tanthammar maybe was using an older version of Inertia.

If someone is able to provide a repo that reproduces this issue, I'd be more than happy to have another look at this. 👍

**Closed by reinink** 2020-10-20 11:55 UTC
Labels: vue.js

**Comment by IvanBernatovic** [comment] 2020-10-21 17:23
@reinink Thanks for the quick response. That was it so thank you very much, and it was Jetstream after all.
