### ISSUE TITLE
Incorrent type annotation for `useForm().transform`

### ISSUE THREAD

**Issue by balthild** [inertiajs/inertia#1001] opened 2021-12-11 05:58 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-react` version: 0.7.1

### Describe the problem:

The `transform` function has this signature ([src](https://github.com/inertiajs/inertia/blob/master/packages/inertia-react/index.d.ts#L89)):

```ts
export interface InertiaFormProps<TForm = Record<string, any>> {
	transform: (callback: (data: TForm) => TForm) => void
}
```

which requires the transformed data must be the same type as the form data. This is mostly unexpected. The transformed data should be allowed to be any type.

### Steps to reproduce:

```ts
const { transform } = useForm({
    email: '',
    password: '',
    remember: false,
})

transform((data) => ({
    ...data,
    remember: data.remember ? 'on' : '',
}));
```

The code results in the error:

```
Type 'string' is not assignable to type 'boolean'. ts(2322)
Login.tsx(14, 9): The expected type comes from property 'remember' which is declared here on type '{ email: string; password: string; remember: boolean; }'
```

**Comment by reinink** [comment] 2023-07-28 01:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:54 UTC
Labels: react

**Comment by esistgut** [comment] 2024-12-06 12:21
These seems to be still the case, this issue should be reopened.
