### ISSUE TITLE
[react] Prop of array of objects does not get updated using Inertia.reload

### ISSUE THREAD

**Issue by hailwood** [inertiajs/inertia#528] opened 2021-03-03 02:39 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-react` version: 0.5.4

### Describe the problem:

When an inertia response includes an array of objects if an object changes due to `Inertia.reload()` this is not reflected in the app.

### Steps to reproduce:

With the following setup, when clicking the reload button observe that the random number changes, however the values in the list do not.

```php
Inertia::render('SomePage', [
    'random' => random_int(0, 100),
    'arr' => [
        (object)['id' => 1, 'value' => random_int(0, 100)],
        (object)['id' => 2, 'value' => random_int(0, 100)]
    ]
]);
```

```jsx
function SomePage({random, arr}) {

    return (
        <div>
          <button onClick={() => Inertia.reload({preserveState: false})}>reload</button>
          Number: {random}
          <ul>
            {arr.map(item=> <li key={item.id}>{item.value}</li>)}
          </ul>
        </div>
    );
}
```

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: react
