### ISSUE TITLE
using "sentry/sentry-laravel" cause transition between page +800ms slower

### ISSUE THREAD

**Issue by vortechron** [inertiajs/inertia#317] opened 2020-11-06 18:33 UTC
Already tested in multiple application, still same result. It has to do within sentry ServiceProvider@register. 

Step to reproduce:

`composer require sentry/sentry-laravel`

**Comment by sebastiandedeyne** [comment] 2020-11-13 08:06
Isn't this more of a Sentry issue than an Inertia issue?

**Comment by vortechron** [comment] 2020-11-13 08:12
@sebastiandedeyne debugbar and without inertia show normal speed, only ajax request from inertia cause +800ms delay

**Comment by RobertBoes** [comment] 2020-11-13 10:17
@vortechron I think you should do some more investigation, it takes quite a lot of valuable time from the maintainers to investigate this isssue.

I've tried reproducing this issue by installing `sentry/sentry-laravel`, before and after I have response times of 20 to 40ms. Then I proceeded to create an account and setup sentry properly, with error reporting and performance monitoring. Still the same results of 20 to 40ms. So there's no change in response times in my setup.

It might be caused by a slow internet connection, since sentry sends data/reports to their servers. You could try to see if the issue exists in a clean Laravel setup (without Inertia) and only installing `sentry/sentry-laravel`

**Comment by vortechron** [comment] 2020-11-13 10:29
@RobertBoes maybe its because im on windows wampp, later i try to setup on my macos machine, what environment are you using?

**Comment by RobertBoes** [comment] 2020-11-13 10:59
@vortechron I'm using Valet on Mac. However, it would be strange that wampp would cause +800ms delay when sentry is used.

**Comment by reinink** [comment] 2020-11-13 12:39
As others have suggested, I don’t think this is an Inertia.js issue. I’m going to close this for now, but if you do find the root problem, and if it is related to Inertia somehow, feel free to post back here. 👍

**Closed by reinink** 2020-11-13 12:39 UTC
Labels: core, investigate
