### ISSUE TITLE
XHR request was sent, but it's without Version, so 303 code returns, then 409,  page is full-reloaded at the last, it appears on some pages

### ISSUE THREAD

**Issue by ybzc-gg** [inertiajs/inertia#1599] opened 2023-06-23 19:06 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.8
- `laravel` version : 9.*

### Describe the problem:
I use it with Laravel 9
I tested with Link Component, 
Page1 Link Page2, it works right. Page2 Link Page3, this time maybe gets the problem like title said, this GET request straight returns 409 if manifest.json exists in build folder else you will get an err on browser's console: "this.resolvecomponent is not a function"

about PUT requests, will first return 303, then inertia requests the redirect url, but no version code be sent with the request.  So browser gets 409, the full loaded is the page

Update:

I found that including inertia by breeze on Laravel 9 now will use version 1.* of @inertiajs/vue3, and it's also including @inertiajs/inertia-vue3, but doc for inertiajs 1.0 above says only @inertiajs/vue3 need to include. maybe it's the problem.

**Comment by reinink** [comment] 2023-07-28 00:57
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 00:57 UTC
