### ISSUE TITLE
Flash message not showing when redirecting to same page?

### ISSUE THREAD

**Issue by mathiasselleslach** [inertiajs/inertia#686] opened 2021-05-21 10:53 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-vue` version: 0.5.12

### Describe the problem:

Flash messages are not being displayed when you redirect back to the same page?
We have a page that contains a regular vue component. The component contains a form that performs a post submission.
The receiving controller performs a redirect back to the same page.
The flash message is not being displayed.
When you redirect to another page, then the flash message is being displayed.

The initialPage.props.flash.message remains 'null'.

What does catch my eye is that the xhr response does contain the flash message though...

**Comment by Anahkiasen** [comment] 2021-05-26 08:34
Seeing the same thing on our end, flash messages for two different actions work correctly but two same requests (eg. two updates to an entity) only show one flash message.

**Comment by Anahkiasen** [comment] 2021-05-26 08:59
[This line](https://github.com/inertiajs/inertia/blob/master/packages/inertia-vue/src/app.js#L42-L46) seems to be the culprit, if I pass `preserveState: false` in my `form.put` options it does work properly.

**Comment by seewhy17** [comment] 2021-05-30 09:31
> ### Versions:
> * `@inertiajs/inertia` version: 0.8.7
> * `@inertiajs/inertia-vue` version: 0.5.12
> 
> ### Describe the problem:
> Flash messages are not being displayed when you redirect back to the same page?
> We have a page that contains a regular vue component. The component contains a form that performs a post submission.
> The receiving controller performs a redirect back to the same page.
> The flash message is not being displayed.
> When you redirect to another page, then the flash message is being displayed.
> 
> The initialPage.props.flash.message remains 'null'.
> 
> What does catch my eye is that the xhr response does contain the flash message though...

@mathiasselleslach I think you could display the flash message in several ways
You could get the message from any component by importing ```Inertia``` or ```usePage``` like so
```
import { Inertia } from '@inertiajs/inertia'
import { useForm, usePage } from '@inertiajs/inertia-vue3'
```
and get the message using
```  Inertia.page.props.flash.message``` or ```usePage().props.value.flash.token```


Alternatively, you can create a local prop ```flash``` on your component.

**Comment by mathiasselleslach** [comment] 2021-05-31 19:15
@seewhy17 , thanks for your feedback.
You actually made me realise how to improve this.
I was only looking for the flash messages in the created lifecycle callback (vue2 due to vuetify dependency).
I have now made it a watcher that looks like this:

```
    watch: {
        '$page.props.flash.message': function (newValue) {
            messageStore.addItem({
                type: 'info',
                message: this.$page.props.flash.message,
            });
        }
    }
```
MessageStore is a messagebus that takes care of displaying the messages.

Works like a charm.

Can me closed afaik. <3

**Comment by seewhy17** [comment] 2021-05-31 22:14
@mathiasselleslach glad I could help, thanks for sharing the message bus idea

**Comment by Anahkiasen** [comment] 2021-06-01 08:21
I would perhaps still keep this open on the basis alone that it's contrary to how [the documentation shows](https://inertiajs.com/shared-data#flash-messages) how to do it and feels like a bug to me but I'm new to Inertia so not sure on that last part

**Comment by reinink** [comment] 2021-06-05 12:10
Hey folks, I am not able to reproduce this issue. I have a Vue 2 app (Ping CRM), which has a form, which submits via post to an `OrganizationsController@store` method:

```js
methods: {
  store() {
    this.form.post(this.route('organizations.store'))
  },
},
```

I've updated my controller code to have the following:

```php
public function store()
{
    return Redirect::back()->with('success', 'Does this work?');
    // ...
}
```

Which results in this:

![image](https://user-images.githubusercontent.com/882133/120891176-1f5fa580-c5d5-11eb-9b46-a56465aae3b4.png)

The way this works is by conditionally checking the `$page.props.flash.success` prop, which you can see [here](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Shared/FlashMessages.vue#L3).

You definitely should not need to set `preserveState: false` to make this work, as props are reactive.

So, not sure what to say. If anyone is able to provide a small demo app that reproduces this, I'd be HAPPY to dig into this further.

**Comment by Anahkiasen** [comment] 2021-06-08 09:15
@reinink There's a misunderstanding I think, the issue is not that the flash messages don't show, it's that if the flash messages is dismissed on timeout, a subsequent request to your form would not make it show the second time around

**Comment by saurabh85mahajan** [comment] 2021-07-08 08:11
The issue can be recreated when you have a Listing and within the Listing you have the Delete Button which Redirects back to the same Screen. 

Since on the PingCRM App, the Delete Button is on the Detail Screen, the issue can not be reproduced there.

As others have mentioned, using `preserveState:false` does fixes the issue.

**Comment by revandpratama** [comment] 2023-05-04 14:46
> [This line](https://github.com/inertiajs/inertia/blob/master/packages/inertia-vue/src/app.js#L42-L46) seems to be the culprit, if I pass `preserveState: false` in my `form.put` options it does work properly.

Literally save my day

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: vue 2
