### ISSUE TITLE
Typescript type on form errors should optionally be an array

### ISSUE THREAD

**Issue by aviemet** [inertiajs/inertia#1156] opened 2022-04-16 00:14 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-react` version: 0.8.0

### Describe the problem:

In the types for the Inertia form components, [`InertiaFormProps`](https://github.com/inertiajs/inertia/blob/85b5694dea5c6193809e9ddd4eada4dfee054f7f/packages/inertia-react/index.d.ts#L79) defines the `errors` object as `Record<keyof TForm, string>`.

Rails returns form errors as an object of string arrays, which caused the red squiglies when I tried to pass it to a component. Could/should this be amended to be `Record<keyof TForm, string | string[]>`?

### Steps to reproduce:

```tsx
import { useForm } from '@inertiajs/inertia-react'

const Errors = ({ errors }: { errors: string[] }) => (
  <div>
    <ul>
      { errors.map((error, i) => <li key={ i }>{ error }</li>) }
    </ul>
  </div>
)


const Form = () => {
  const form = useForm<Record<string, string>>({ record: '' })

  return (
    <>
      <input type="text" name="record" value={ form.data.record } onChange={ e => form.setData('record', e.target.value) } />
      { form.errors && <Errors errors={ form.errors } /> }
    </>
  )
}
```

I would expect this to be valid because the errors I receive from Rails are in the form:

```javascript
{
  "record": [
    "can't be blank"
  ],
}
```

**Comment by emachiels** [comment] 2022-05-24 07:56
Laravel (9 at least) also returns the error in that format:

```json
{
    "message": "The email field is required.",
    "errors": {
        "email": [
            "The email field is required."
        ]
    }
}
```

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
Labels: react
