### ISSUE TITLE
Failed to execute 'replaceState' on 'History': #<Object> with Sortable.js

### ISSUE THREAD

**Issue by EmilMoe** [inertiajs/inertia#854] opened 2021-08-09 16:59 UTC
### Versions:

- `vue` version 3.0.5
- `@inertiajs/inertia` version 0.9.0
- `@inertiajs/inertia-vue3` version 0.4.0

### Describe the problem:

Similar to here, I have this problem when using Sortable.js / VueDraggable: https://github.com/inertiajs/inertia/issues/730

```
app.js?id=f8cbfda01b9810c19e0f:2 DOMException: Failed to execute 'replaceState' on 'History': #<Object> could not be cloned.
    at e.n.replaceState (/js/app.js?id=f8cbfda01b9810c19e0f:2:28191)
    at e.n.saveScrollPositions (/js/app.js?id=f8cbfda01b9810c19e0f:2:21087)
    at e.n.visit (/js/app.js?id=f8cbfda01b9810c19e0f:2:25155)
    at onClick (/js/app.js?id=f8cbfda01b9810c19e0f:2:11402)
    at At (/js/app.js?id=f8cbfda01b9810c19e0f:2:657430)
    at Pt (/js/app.js?id=f8cbfda01b9810c19e0f:2:657508)
    at HTMLAnchorElement.n (/js/app.js?id=f8cbfda01b9810c19e0f:2:708099)
```
### Steps to reproduce:

Sort elements with sortable.js or Vue draggable and click on any Inertia link.

Similar to the linked thread, I can fix it by modifying the minified javascript file with this:

```
n.replaceState=function(e){this.page=e,e=JSON.parse(JSON.stringify(e)),window.history.replaceState(e,"",e.url)}
```

**Comment by EmilMoe** [comment] 2021-08-10 14:42
It seems that I solved it by copying the list I'm sorting to a `data()` variable in the Vue component instead of sorting it on a property on the object.

This would fail when sorting `type.list:

```
data() {
  return {
    type: { prop1: 'string', list: [1,2,3] }
  }
}
```

This seems not to fail when sorting `list`:

```
data() {
  return {
    type: { prop1: 'string', list: [1,2,3] },
    list: []
  }
},
mounted() {
  this.list = this.type.list
}
```

**Comment by grantholle** [comment] 2021-08-24 03:01
After lots of work, I've found out that if you try to modify a prop directly in a component, it will cause this error. This tripped me up with object references (oh javascript). Cloning the prop I needed to do work on solved me issues.

**Comment by foreverheavy** [comment] 2021-11-03 04:22
Just to piggyback on this, I also encountered this issue when using vue.draggable.next (SortableJS) and useForm. Any time I sorted an array property in the form data, this error would occur. I was ultimately able to solve this by unsetting v-model on the **draggable** component and [using the list prop instead](https://github.com/SortableJS/vue.draggable.next#list). 

I still cannot identify the reason using v-model on the component causes this issue, but it ultimately wasn't a bug in Inertia

**Comment by claudiodekker** [comment] 2021-12-03 09:46
Yeah, so, this is indeed likely related to third-party javascript libraries or user-code creating references, proxy objects, or other 'fancy' rich states that aren't serializable to a JSON string, which then causes this failure.

If someone knows of a way that this can be done (it probably means just ignoring those properties, or some of their child properties / partially serializing an object?) then please do let me know so we can solve this. If not, I'll probably eventually end up looking for a way that we can tell the user about what's going on with a more friendly console message.

Thanks!

**Comment by ryanhungate** [comment] 2022-01-27 21:50
Just throwing it out there - I had this same problem today and ended up tying it to the "dynamic component" node type. As soon as I removed that from the equation everything worked fine. I have no clue what was causing this but it's annoying. :)

**Comment by jcfrane** [comment] 2022-01-29 12:58
I also experienced this when using dynamic components or v-if. Still can't figure out what's wrong.

**Comment by SimonJ** [comment] 2022-03-31 13:36
I had the same issue. I fixed it by adding

```javascript
onMounted(() => {
  JSON.parse(JSON.stringify(this.yourDATA))
})
```

**Comment by rajan-parmar** [comment] 2022-04-19 11:58
> I had the same issue. I fixed it by adding
> 
> ```js
> onMounted(() => {
>   JSON.parse(JSON.stringify(this.yourDATA))
> })
> ```

@SimonJ I have similar issue while i changing the property of array(multi select option where add/remove).

**Comment by brunoleles** [comment] 2022-07-08 02:47
> I had the same issue. I fixed it by adding
> 
> ```js
> onMounted(() => {
>   JSON.parse(JSON.stringify(this.yourDATA))
> })
> ```

Indeed I'd the issue using an object with nested levels of v-models, and this worked, to dissociate the models from the props.

**Comment by ericmp33** [comment] 2022-10-10 11:08
Having same issue! I also fixed it using the "JSON parse JSON stringify" way:
```js
const item = ref(props.item)
```
to
```js
const item = ref(JSON.parse(JSON.stringify(props.item)))
```

**Comment by Atif-Bashir-1998** [comment] 2022-11-23 08:05
Instead of doing anything with the `props` directly, create new variables and reference the props using those.

Cause of the issue:
```
<script setup>

const props = defineProps({
    foo: String
});

props.foo = "new value";

</script>
```
In order to fix it I did the following:

```
<script setup>

const props = defineProps({
    foo: String
});

const myFoo = ref(props.foo);

</script>
```

**Comment by tirta-keniten** [comment] 2023-01-07 09:26
I had the same issue, and this is how I fix it.
```
const props = defineProps({
    transaction: Object,
    customer: Object,
});

const propsClone = JSON.parse(JSON.stringify(props));

const form = useForm({ transaction:  propsClone.transaction });

```

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: bug, help wanted, investigate, vue 3
