### ISSUE TITLE
Form helper not preserving state and errors

### ISSUE THREAD

**Issue by piljac1** [inertiajs/inertia#590] opened 2021-03-11 23:05 UTC
Hi guys! First of all, this is my first project using the Vue 3/Inertia combo and I gotta say I love it so far! However, I encountered what might not be a bug (could be, but the problem is probably on my side).

So I have this data setup

```js
data() {
  return {
    form: this.$inertia.form({
      redirect_to_page: 'ParentCategorySelection',
      product_option_value_id: '',
      product_color_id: null,
      area: 0,
      option_ids: []
    })
  }
},
```

So far, everything works alright, all v-models are working and data was validated using Vue devtools, as well as by outputting them directly in the page.

Now comes the time to post the form. Here's what I have:

```js
addProduct(page) {
  this.form.redirect_to_page = page;

  // P.S. this.postRoute comes from a prop
  this.form.post(this.postRoute);
}
```

When I try to post the form while having invalid fields (according to my form request validation), the page is reloaded because validation errors were encountered (tried removing all validations to see if the reload could be due to something else, but when I do, the behavior is as intended and the user gets redirected on another page as desired).

At this point, this is the intended behavior. The page should be reloaded upon validation errors, like it successfully does right now.

But... the problem is that in the doc (and when I inspect the form object), it mentions that we should be able to access errors from the form using `form.error.the_field`. However, the error object is always empty, despite the fact that the global `$form.props.errors` contain the appropriate errors.

Also, reading the doc, the state should be preserved automatically when using the post method. It is not the case for me. All form attributes fall back to their default values. I tried explicitly setting the `preserveState` flag to true, but no dice.

Let me know if you need more info. Thanks in advance for your input!

### EDIT : 

My present workaround is to retrieve all inputs in my controller create method and send them as an `oldForm` prop. Then, in my Vue component, I do the following:

```js
form: this.$inertia.form(
  _.isEmpty(this.oldForm)
    ? {
      redirect_to_page: 'ParentCategorySelection',
      product_option_value_id: '',
      product_flodeco_color_id: null,
      area: 0,
      option_ids: []
    }
    : this.oldForm
),
```

This isn't ideal because I still don't know why the form helper doesn't send back errors and doesn't preserve the state, but it fixes my issue for now because I need to meet the deadline.

However, I'd like to understand why it doesn't work so I can hopefully fix it before the release. I'm baffled right now because I look at the PingCRM demo and the default Breeze scaffolding and what I did is pretty much the same apport separating my validation in a form request (I had also tried to put the validation in the controller like in the doc and the PingCRM demo, but it didn't fix the issue). I also use the LaravelLocalization package, but it doesn't seem to do unwanted redirections. I tried to disable it anyway to debug, but it didn't help.

**Comment by JohnCarlo29** [comment] 2021-05-23 14:01
I encountered this issue also. On a page I have 2 components that has `this.$inertia.form()` inside. One of my form got the errors value using `form.errors` but the other one dont. My work around on the form that has empty object `errors` is like this 

``` this.addForm
        .transform((data) => pickBy(data))
        .post(route('admin.product-categories.store'), {
          onError: (error) => { this.addForm.errors = error }
        })```

**Comment by leemcd56** [comment] 2021-06-02 16:50
I'm encountering the same issue. I'm using the Inertia helper to send form data, such as searches and picking dates. The form helper isn't restoring data post-navigation.

On form submission, this uses a GET request to fetch customers by search string, appending a query string to the URL to allow for pagination. Since the form helper isn't restoring the data, I am having to manually pull the data from the query string and reset the form.

```js
const form = useForm('Customers/Search', {
  search: '',
})
```

A `@change` is checking the component this is tied to, and uses a GET request to fetch records. I am having to reset the form the same way as the customer search.

```js
const form = useForm('Appointments/Date', {
  date: new Date(),
})
```

**Comment by reinink** [comment] 2021-06-05 19:55
Hey folks! If you're still having this issue, can you update to the latest version of Inertia and the Vue 3 adapter, and let me know if this is still happening?

**Comment by leemcd56** [comment] 2021-06-06 18:29
> Hey folks! If you're still having this issue, can you update to the latest version of Inertia and the Vue 3 adapter, and let me know if this is still happening?

Unfortunately, it's not working for me. 🙁 I am beginning to wonder if I am using it correctly?

Referencing the appointment snippet I posted above, I am changing the date by using this method:

```js
const changeDate = () => {
  Inertia.visit('/appointments', {
    method: 'get',
    data: {
      date: format(form.date, 'yyyy-MM-dd'),
    },
  })
}
```

Would this lead to the form helper not retaining data?

**Comment by msonowal** [comment] 2021-07-12 08:20
in vue3 same for me as
After successful submission it is not respecting the new prop data came from the server,
It does show in the Vue dev tools inside the form but not rendered in the UI/ input fields. I thinks its kind of internal bug of reactivity rendering

**Comment by claudiodekker** [comment] 2021-12-01 17:50
Hey all,

Trying to understand what's going on here, and I have a couple of questions.

https://github.com/inertiajs/inertia/issues/590#issue-844781337:
> [...] it mentions that we should be able to access errors from the form using `form.error.the_field.` However, the error object is always empty, despite the fact that the global `$form.props.errors` contain the appropriate errors. [...]

This might sound very silly and maybe it's just a typo in the issue description, but, what happens if you try `form.errors` instead of `form.error`?

As far as the 'default values' coming back, that sounds very strange to me. Do you have a reproducable sample, or a screen recording of the behaviour? I almost can't imagine how this would happen, as Inertia's requests are AJAX, the only case that the form would reset is if the page reloads, which only happens when:
- The `X-Inertia-Version` is used and changes (https://inertiajs.com/the-protocol#asset-versioning)
- You call `form.reset()` somewhere

Under no circumstances should Inertia change your form's filled input, unless you tell it to do so or state is lost by manually navigating away.

Thanks!

**Comment by quantumwebco** [comment] 2022-09-22 13:48
I'm still having this issue. I have a ```this.$inertia.post("the/url", {foo: "bar"}, {preserveState: true});``` and in Laravel ```return back()->with('success', $message)->withInput();``` and the page just resets to initial state. Not even passing reactive data, just an arbitrary object. Should I be returning JSON? Is this better done with axios so it doesn't reset the data?

**Comment by flexchar** [comment] 2022-12-18 23:23
I've encountered the same of form.errors always being empty even though I can see them being flashed in the response from Laravel. I'll try to recreate a minimal repo.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 3
