### ISSUE TITLE
Error when updating the list on consecutive page reload

### ISSUE THREAD

**Issue by bakanyaka** [inertiajs/inertia#615] opened 2021-04-08 09:09 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.6
- `@inertiajs/inertia-vue3` version: 0.3.12
-  `inertiajs/inertia-laravel` version 0.3.6

### Describe the problem:

I've a checkbox on the page and a watcher that reloads the page with filtered data based on it's value, I'm getting following error when Inertia reloads the page second time and element list in the DOM is being updated:
```
app.js:12889 Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
    at insert (app.js:12889)
    at mountElement (app.js:9604)
    at processElement (app.js:9545)
    at patch (app.js:9465)
    at patchKeyedChildren (app.js:10210)
    at patchChildren (app.js:10093)
    at processFragment (app.js:9839)
    at patch (app.js:9461)
    at patchKeyedChildren (app.js:10174)
    at patchChildren (app.js:10117)
```

### Steps to reproduce:

1. Have a page with it's content wrapped within layout component. (Using persistent layout fixes the problem)
2. Have an element that that triggers page reload with new data based on some property
3. Have a deeply nested list of data with v-for loop. (Moving the loop one level up in my example fixes the problem). I've tried keying element by object id (in my real app) , by index or just by numeric value but that does not help.
4. Trigger page reload several times. (In my example error occurs on second reload)
That's my test component recreated in new Laravel Breeze with Inertia template - resources/js/Pages/Welcome.vue

```Vue
 <template>
  <guest>
      <div>
          <div class="mt-2 text-right">
              <label class="inline-flex items-center leading-none">
                  <input v-model="checkBox" type="checkbox" class="mr-2" />
                  <span>Test checkbox</span>
              </label>
          </div>
          <div>
              <div v-for="value in someData" :key="value">
                  {{value}}
              </div>
          </div>
      </div>
  </guest>
  </template>
  
  <script>
      import Guest from "../Layouts/Guest";
      import {ref, watch} from "vue";
      import { Inertia } from '@inertiajs/inertia';
      export default {
          components: {Guest},
          props: {
              someData: {
                  type: Array,
                  required: true,
              }
          },
          setup() {
              const checkBox = ref(false);
              watch(checkBox, (value) => {
                  Inertia.reload({ data: { test: value ? 1 : 0 } });
              });
              return {checkBox}
          }
      }
  </script>
```

That is the test route I'm using:

```PHP
Route::get('/', function () {
    return Inertia::render('Welcome', [
        'someData' => request()->input('test') === '1' ? [1, 2, 3] : [1, 2, 3, 4, 5, 6],
    ]);
});
```

Demo repository: https://github.com/bakanyaka/inertia-vue-bug

**Comment by GDanielRG** [comment] 2021-04-20 04:32
I am also having this problem :/

**Comment by reinink** [comment] 2021-04-20 12:08
Hey thanks for providing a nice demo repo for this. I just spent almost an hour trying to figure out what's going on here, and I honestly don't know. I'm starting to think this is a Vue bug, as the error suggests:

![image](https://user-images.githubusercontent.com/882133/115393003-34ac7c00-a1af-11eb-92ff-0bac7e03c7c3.png)

One thing that did work for me was to wrap the page component in an extra `<div>`:

```html
 <template>
  <div>
    <guest>
      ...
    </guest>
  </div>
</template>
```

The fact that this works, makes me think this is an issue with the new fragments feature in Vue 3.

I am sorry I cannot be more helpful than that. I am going to close this issue, as I don't think it's an Inertia bug, but if anyone can prove otherwise, feel free to post, and we can reopen. 👍

**Closed by reinink** 2021-04-20 12:08 UTC

**Comment by kbellpostman** [comment] 2021-04-25 00:39
Pretty sure it has something todo with scoped slots. 

https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

Solved it myself by passing the data that was not being reactive inside the slot, which in your case is <guest>

Took me 5 hours to figure out grrrr

![image](https://user-images.githubusercontent.com/60920059/115976522-2ecbe780-a56f-11eb-9095-17b657d3e764.png)

**Comment by akc4** [comment] 2021-04-29 00:32
I am having this exact same issue. I also get this issue using "this.$inertia.reload({ only: ['users']})" on a axios request.

**Comment by kbellpostman** [comment] 2021-04-29 09:03
@akc4 The issue is that your code is running in a vue slot inside app-layout. You have to v-bind your data to app-layout like I've done in the screenshot above if you want to make it reactive.

**Comment by devstack-be** [comment] 2021-06-12 19:31
> ### Versions:
> * `@inertiajs/inertia` version: 0.8.6
> * `@inertiajs/inertia-vue3` version: 0.3.12
> * `inertiajs/inertia-laravel` version 0.3.6
> 
> ### Describe the problem:
> I've a checkbox on the page and a watcher that reloads the page with filtered data based on it's value, I'm getting following error when Inertia reloads the page second time and element list in the DOM is being updated:
> 
> ```
> app.js:12889 Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
>     at insert (app.js:12889)
>     at mountElement (app.js:9604)
>     at processElement (app.js:9545)
>     at patch (app.js:9465)
>     at patchKeyedChildren (app.js:10210)
>     at patchChildren (app.js:10093)
>     at processFragment (app.js:9839)
>     at patch (app.js:9461)
>     at patchKeyedChildren (app.js:10174)
>     at patchChildren (app.js:10117)
> ```
> 
> ### Steps to reproduce:
> 1. Have a page with it's content wrapped within layout component. (Using persistent layout fixes the problem)
> 2. Have an element that that triggers page reload with new data based on some property
> 3. Have a deeply nested list of data with v-for loop. (Moving the loop one level up in my example fixes the problem). I've tried keying element by object id (in my real app) , by index or just by numeric value but that does not help.
> 4. Trigger page reload several times. (In my example error occurs on second reload)
>    That's my test component recreated in new Laravel Breeze with Inertia template - resources/js/Pages/Welcome.vue
> 
> ```
>  <template>
>   <guest>
>       <div>
>           <div class="mt-2 text-right">
>               <label class="inline-flex items-center leading-none">
>                   <input v-model="checkBox" type="checkbox" class="mr-2" />
>                   <span>Test checkbox</span>
>               </label>
>           </div>
>           <div>
>               <div v-for="value in someData" :key="value">
>                   {{value}}
>               </div>
>           </div>
>       </div>
>   </guest>
>   </template>
>   
>   <script>
>       import Guest from "../Layouts/Guest";
>       import {ref, watch} from "vue";
>       import { Inertia } from '@inertiajs/inertia';
>       export default {
>           components: {Guest},
>           props: {
>               someData: {
>                   type: Array,
>                   required: true,
>               }
>           },
>           setup() {
>               const checkBox = ref(false);
>               watch(checkBox, (value) => {
>                   Inertia.reload({ data: { test: value ? 1 : 0 } });
>               });
>               return {checkBox}
>           }
>       }
>   </script>
> ```
> 
> That is the test route I'm using:
> 
> ```
> Route::get('/', function () {
>     return Inertia::render('Welcome', [
>         'someData' => request()->input('test') === '1' ? [1, 2, 3] : [1, 2, 3, 4, 5, 6],
>     ]);
> });
> ```
> 
> Demo repository: https://github.com/bakanyaka/inertia-vue-bug

I got the same problem and i found a solution.
I think that you can fix it with changing the :key on your "for".
Like this:
>               <div v-for="value in someData" :key="value">
>                   {{value}}
>               </div>

>               <div v-for="(value, key) in someData" :key="key">
>                   {{value}}
>               </div>

**Comment by valante** [comment] 2021-06-14 16:05
> I got the same problem and i found a solution.
> I think that you can fix it with changing the :key on your "for".
> Like this:

That's not working for me. I'm in the same situation as described above.

**Comment by williamjulianvicary** [comment] 2021-06-28 21:24
FWIW - I ran into this today as well, using JetStream (which I guess is fair to assume others are too).

Adding a wrapping <div> around <app-layout> worked for me too... odd!

**Comment by stevebauman** [comment] 2021-06-29 14:27
For anyone browsing this issue, here is exactly how I fixed it (as others mention above, but without examples):

**Before:**

```vue
<template>
    <layout>
        ...content
    </layout>
</template>
```

**After:**

```vue
<template>
    <div>
        <layout>
            ...content
        </layout>
    </div>
</template>
```

**Comment by matthieumota** [comment] 2021-07-25 16:15
Hi @reinink I think @bakanyaka worry is fixed. I've got same worry and update `vue` dep on project.

In `vue@3.1.5`, bug is fixed. For information, I've search for [issue](https://github.com/vuejs/vue-next/issues/3943) mentionning that.

**Comment by reinink** [comment] 2021-07-26 16:56
@mathieutu Great to hear!

Can anyone else here confirm this issue has been fixed by getting onto the latest version of Vue 3?

**Comment by mathieutu** [comment] 2021-07-26 17:23
Hi there! 👋
Always like reading you @reinink but I'm apparently not the man you're looking for! 😋

Ping @matthieumota

**Comment by reinink** [comment] 2021-07-26 17:43
@mathieutu Ugh I do that more often...just take the first recommendation in the `@` autocomplete. Sorry!

**Comment by marcomessa** [comment] 2021-07-26 17:51
@reinink I confirm for me the problems is solved. I Tried with `vue@3.1.5`, I removed the `preserveState=false` fix and everything is working flawlessly.

**Comment by reinink** [comment] 2021-07-26 17:52
@marcomessa Awesome! 🙌

**Comment by grantholle** [comment] 2021-07-31 04:25
Ahhhh `vue@3.1.5` solves it, I was losing my mind over this!
