### ISSUE TITLE
FormData uses 'undefined' and not 'null' when sending files

### ISSUE THREAD

**Issue by billygl** [inertiajs/inertia#613] opened 2021-04-07 17:02 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4
- `@inertiajs/inertia-laravel` version: 0.3.5

### Describe the problem:

When a form sends null values for some fields, it work okey when not sending files.
If the form sends these values and files, it serializes null as undefined
![image](https://user-images.githubusercontent.com/442925/113904872-25353800-9798-11eb-9dfc-8d34c1c62f28.png)

### Steps to reproduce:

In Vue2, 
````
data(){
  form: this.$inertia.form({
      'service_center_id': 1,
      'customer_id': 1,
      'device_id': 1,
      'type': 0,
      'has_insurance': null,
      'files': null
  }, {
      resetOnSuccess: false,
  }),
},
methods:{
  save() {              
          let url = 'route'
          let method = "post"
          this.form[method](url, {
              preserveScroll: true,
              errorBag: 'form'
          });
      },
  updateFiles(e){
        this.form.files= e.map( (f) => f.file)
    },
````
Files is
````
<file-pond
      name="file"
      allow-multiple="true"
      @updatefiles="updateFiles"
      />
````
If files is null, it works ok, If it doesn't have files, it sends null values as undefined.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 2
