### ISSUE TITLE
Issues starting with vue@3.2.18

### ISSUE THREAD

**Issue by jaulz** [inertiajs/inertia#947] opened 2021-10-20 09:08 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue3` version: 0.5.2

### Describe the problem:

Navigation is not working anymore with `vue@3.2.20`. I already tried to identify which change could have caused the issue but couldn't find anything so far:
https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md

Edit: the navigation does not work anymore starting with `vue@3.2.0` but the page props are not updating anymore starting from `vue@3.2.18`.

### Steps to reproduce:

Install `vue@3.2.20` and try to navigate to another page.

Edit:
Install `vue@3.2.18`and see if props are updating after the navigation.

**Comment by ajnsn** [comment] 2021-10-21 06:56
Hey @jaulz 
I just upgraded one of the Vue 3 projects to v3.2.20 and cannot reproduce your issue. Everything works fine. Do you have any errors logged to the Console? Can you please post your `package.json`?

**Comment by claudiodekker** [comment] 2021-12-01 18:22
Since this issue's been in a doubtful state for a while now, I'll be closing it for now. We also haven't had any other reports of this, which I imagine we would have if something was that broken. Feel free to re-open this if necessary 👍

**Closed by claudiodekker** 2021-12-01 18:22 UTC
