### ISSUE TITLE
Does not keep scroll position on Edge browser (Win 11)

### ISSUE THREAD

**Issue by quyhoangs** [inertiajs/inertia#1603] opened 2023-07-02 09:31 UTC
### Versions:
- `@inertiajs/vue3` version: #.#.#

### Describe the problem:

The preserve-scroll attribute works fine on chrome and firefox ,
however this doesn't work on Microsoft Edge (Win 11), the scrollbar is still dragged to the top

### Steps to reproduce:
please refer to attached image
<img width="220" alt="User-Edge" src="https://github.com/inertiajs/inertia/assets/61405350/0da186c8-f442-4561-9cab-0184d9519cd6">
<img width="206" alt="User-FireFox" src="https://github.com/inertiajs/inertia/assets/61405350/187ebb59-5c83-4ffc-88ae-f3dae8b87871">
<img width="221" alt="User-Refresh-Edge" src="https://github.com/inertiajs/inertia/assets/61405350/39bf5169-f85c-417b-9974-ad5b0dcd0073">
<img width="237" alt="User-Refresh-FireFox" src="https://github.com/inertiajs/inertia/assets/61405350/d4b67d0c-bb18-4777-9ced-7862bf2ab165">

This is my code
`<template>
    <h1 class="text-4xl font-bold">
        Users
    </h1>

    <Nav />

    <div style="margin-top: 1400px">
        <p>The current time is {{ time }}.</p>

        <Link href="/users" class="text-blue-500" preserve-scroll>
        Refresh
        </Link>
    </div>
</template>

<script>
import Nav from "../Shared/Nav";
import { Link } from '@inertiajs/vue3';

export default {
    components: { Nav, Link },

    props: { time: String }
};
</script>`

**Comment by reinink** [comment] 2023-07-28 00:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 00:54 UTC
