### ISSUE TITLE
[vue-i18n] Layout messages doesn't update when locale is switched

### ISSUE THREAD

**Issue by kenan-recebli** [inertiajs/inertia#983] opened 2021-11-28 14:13 UTC
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue` version: 0.6.2
- `vue-i18n` version: 8.26.7

### Describe the problem:

When I use `layout: {Layout}`, translation messages are not updated in layout file, but when I use `components: {Layout}` and manually wrap with `<layout></layout>` in every single page, messages are updated.

### Steps to reproduce:

- Use layout as `layout: {Layout}` (or even make it global in `resolve`, it doesn't matter)
- Install `vue-i18n` package
- Configure it according to the official docs
- Copy-paste locale switching example from official docs

Only page's (`<slot/>`) messages will be updated.

**Comment by ajnsn** [comment] 2021-11-29 22:50
Hey @kenan-recebli 
I think the described issue is by design as these are called [persistent layouts](https://inertiajs.com/pages#persistent-layouts), means they persists (= not being touched) betwen Inertia's server roundtrips.

If the layourt contains a property than needs to be reactive, you might need the already discovered solution or keep properties reactive by using appropriate methods of your frontend framework. This is much more easier in Vue 3.

**Comment by kenan-recebli** [comment] 2021-11-30 22:48
> 

Thanks for the repsonse! Unfortunately, I have to deal with Vue 2, so I have to keep the already discovered solution until I can migrate to Vue 3, when all its important plugins will be stable too.

**Comment by claudiodekker** [comment] 2021-12-01 19:16
Another thing you could try in your layout is to 'watch' for a prop change, and then do a `this.$forceUpdate()` to force Vue to re-render that layout component. 

Maybe that's not a great fix (and the 'force' part here already indicates it's definitely not something that would make Vue very happy), but unless vue-i18n has a better solution to this or others developed their own workaround, I don't think there's super much here that can be done.

In either case, as @ajnsn already stated, this is kind of by design and isn't really an Inertia 'bug', as under normal circumstances the view still reactively updates as it normally would (e.g. when props change) so I'll be closing this one.

**Closed by claudiodekker** 2021-12-01 19:16 UTC

**Comment by kenan-recebli** [comment] 2021-12-01 21:00
> Another thing you could try in your layout is to 'watch' for a prop change, and then do a `this.$forceUpdate()` to force Vue to re-render that layout component.
> 
> Maybe that's not a great fix (and the 'force' part here already indicates it's definitely not something that would make Vue very happy), but unless vue-i18n has a better solution to this or others developed their own workaround, I don't think there's super much here that can be done.
> 
> In either case, as @ajnsn already stated, this is kind of by design and isn't really an Inertia 'bug', as under normal circumstances the view still reactively updates as it normally would (e.g. when props change) so I'll be closing this one.

I have tried `this.$forceUpdate()` before opening this issue, but it didn't help. Anyway, thanks! :)

**Comment by kenan-recebli** [comment] 2021-12-01 21:01
> Another thing you could try in your layout is to 'watch' for a prop change, and then do a `this.$forceUpdate()` to force Vue to re-render that layout component.
> 
> Maybe that's not a great fix (and the 'force' part here already indicates it's definitely not something that would make Vue very happy), but unless vue-i18n has a better solution to this or others developed their own workaround, I don't think there's super much here that can be done.
> 
> In either case, as @ajnsn already stated, this is kind of by design and isn't really an Inertia 'bug', as under normal circumstances the view still reactively updates as it normally would (e.g. when props change) so I'll be closing this one.

I have tried `this.$forceUpdate()` before opening this issue, but it didn't help. Anyway, thanks! :)

**Comment by claudiodekker** [comment] 2021-12-02 12:03
In that case, I recommend you to ask your question in our [Discord](https://discord.com/invite/inertiajs), as a [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) topic, or perhaps even over at [the Laracasts forums](https://laracasts.com/discuss/channels/inertia), as those places are more suitable compared to the issue tracker, as well as that there's many others (especially on our Discord) that might be able to help with this 👍
