### ISSUE TITLE
Transitions are causing bugs

### ISSUE THREAD

**Issue by joburgard** [inertiajs/inertia#178] opened 2020-04-08 12:30 UTC
Hello,
I found an easily reproducible bug that creates problems with routing. It happens as soon as Svelte transitions are used.
```html
<script>
import {fade} from 'svelte/transition';
</script>

<div in:fade out:fade="{{duration: 2000}}">
  ...
</div>
```
Now when you click on an InertiaLink it will only change the page after all the transitions habe ended played. I don't think that is useful when you are loading another page anyway. Maybe it should be optional.

But that is not all. After that it has problems with destroying and recreating the components. That causes different kind of problems.

**How to reproduce the bug:**
The easiest way is to use the pingcrm-svelte project as a basis. https://github.com/zgabievi/pingcrm-svelte/

Now just add a transition. For example in this file: https://github.com/zgabievi/pingcrm-svelte/blob/master/resources/js/Pages/Organizations/Index.svelte

Add the transition like the example code above. Now when you go the Organizations area, then to another page and back to Organizations it won't work anymore and show an error in the console.

**Comment by reinink** [comment] 2021-03-03 15:00
I am hoping that #529 fixes this. If someone could confirm after we release those changes, that would be appreciated. 👍

**Comment by mariojankovic** [comment] 2021-03-11 10:33
This seems to have worked with the svelte adapter prior to my #528 PR (I've reproduced the same exact scenario and it didn't show any errors with or without the fix). Since this issue seems to be outdated I guess it has been fixed previously. @joburgard if you are able to test this out again and find the issue has not been resolved feel free to reopen this ticket.

**Comment by reinink** [comment] 2021-03-11 12:35
Awesome, thanks @mariojankovic. Closing this one.

**Closed by reinink** 2021-03-11 12:35 UTC
Labels: investigate, svelte
