### ISSUE TITLE
[Inertia-Vue3] Vue 3.0.3 Page component replace in persistent layout

### ISSUE THREAD

**Issue by JakubRobotka** [inertiajs/inertia#346] opened 2020-12-10 07:17 UTC
Hello,

I am working on Symfony Inertia Vue 3 project. Everything works fine. After i updated Vue to the newest version i noticed that when going from route 1 to route 2 page component remains and doesnt rerender (props works). 
So i tryed goes from minor version one by one. Latest working is Vue 3.0.2 and problems occurs from 3.0.3

When it works:
After removing persistent layout from createApp, it starts working fine.
It seems like vue did some change to importing async components that doesnt works well with vue adapter. 

Now i have to do :key binding on slot to get it working
` <slot :key="$page.component" />`
But that doesnt feel right

**Comment by reinink** [comment] 2020-12-21 13:52
Hmm, that's not good. I'm assuming you have tried the release since, `3.0.4`, yes?

**Comment by reinink** [comment] 2020-12-28 13:51
@JakubRobotka I've been working with Vue 3 (`3.0.4`) recently myself, and cannot reproduce this issue. I am going to close this for now, but if you can provide a repo that reproduces this issue, I'd be happy to have a look at it. 👍

**Closed by reinink** 2020-12-28 13:51 UTC
