### ISSUE TITLE
Get method Array serialization

### ISSUE THREAD

**Issue by Tofandel** [inertiajs/inertia#1136] opened 2022-03-18 13:54 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0

### Describe the problem:

When using the get method without formData and passing an array of objects, the serialization of the array is wrong

### Steps to reproduce:
https://codesandbox.io/s/axios-forked-dmrd6p?file=/src/index.js:224-284

```js
Inertia.get("/posts", {
    arr: [{test: 1, test2: 2}]
});
```

Look at the request produced which will be `/posts?arr[][test]=1&arr[][test2]=2` but should be `/posts?arr[0][test]=1&arr[0][test2]=2`

The current url in php will produce
```php
[
    'arr' => [['test' => '1'], ['test2' => '2']]
]
```

Instead of the expected
```php
[
    'arr' => [['test' => '1', 'test2' => '2']]
]
```

It's possible to get around the issue using the qs option, but I believe it would be best to make it the default as without it, the behavior is not correct and this option is not documented
```js
Inertia.get("/posts", {
    arr: [{test: 1, test2: 2}]
}, {queryStringArrayFormat: 'indices'});
```

**Comment by ninjaparade** [comment] 2022-04-25 17:39
[Tofandel](https://github.com/Tofandel) looks like this issue was resolved.

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
