### ISSUE TITLE
Can't use tree shaking because of mixin

### ISSUE THREAD

**Issue by ibrunotome** [inertiajs/inertia#882] opened 2021-08-26 16:26 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue3` version: 0.5.2

### Describe the problem:

In Vue 3 we can disable options api and use only composition api by configure webpack with:

```js
plugins: [
    new webpack.DefinePlugin({
      __VUE_OPTIONS_API__: false,
      __VUE_PROD_DEVTOOLS__: false,
    }),
  ],
```

But `@inertiajs/inertia-vue3/src/app.js` has this piece of code:

```js
export const plugin = {
  install(app) {
    Inertia.form = useForm

    Object.defineProperty(app.config.globalProperties, '$inertia', { get: () => Inertia })
    Object.defineProperty(app.config.globalProperties, '$page', { get: () => page.value })
    Object.defineProperty(app.config.globalProperties, '$headManager', { get: () => headManager })

    app.mixin(remember)
  },
}
```

Which makes this warning appear:

`[Vue warn]: Mixins are only available in builds supporting Options API`

### Steps to reproduce:

- Configure a project with inertia and vue 3
- Disable options api with `__VUE_OPTIONS_API__: false` flag in webpack.

**Comment by reinink** [comment] 2023-07-28 01:57
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:57 UTC
Labels: investigate, vue 3
