### ISSUE TITLE
Getting `currently unable to handle this request.` error while rendering inertia component from app/Exceptions/Handler.php in Laravel 8

### ISSUE THREAD

**Issue by uncannyMBM** [inertiajs/inertia#1551] opened 2023-05-13 15:44 UTC
### Version:

- `@inertiajs/vue2` version: 1.0.3
-  `@inertiajs/inertia-laravel` version: 0.6.9

I'm getting redirection issue while trying to implement inertia error handling. I'm getting exact below output.

```
This page isn’t working
bugfinder.test is currently unable to handle this request.
HTTP ERROR 500
```

My handler code is look like. 

```
   public function render($request, Throwable $e)
    {
        $response = parent::render($request, $e);
        if (!app()->environment(['local', 'testing']) && in_array($response->status(), [500, 503, 404, 403])) {
            return Inertia::render('Frontend/Error', ['status' => $response->status()])
                ->toResponse($request->all())
                ->setStatusCode($response->status());
        } elseif ($response->status() === 419) {
            return back()->with([
                'message' => 'The page expired, please try again.',
            ]);
        }
        return $response;
    }
```

Can anyone give any shot about this? Thanks in advance.

**Comment by reinink** [comment] 2023-07-28 01:25
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:25 UTC
