### ISSUE TITLE
Remember lazily loaded props when reloading a page

### ISSUE THREAD

**Issue by lpeterke** [inertiajs/inertia#863] opened 2021-08-13 10:37 UTC
When reloading (or redirecting back to) a page, Inertia will reload all props for that page. This will typically NULL all props that use the ```Inertia::lazy()``` method in the backend.

Currently there is no way to keep these props. To work around this you'll need to throw an event in the ```onFinish``` event callback after your ```$inertia.post()``` call and then catch this event in your page component and perform an additional ```$intertia.reload()``` there with the option ```only: ['my', 'lazy', 'props']```.

A cleaner solution would the the ability to provide an array of prop names in the page component that should never be refetched automatically by Inertia or the ability to add them to the ```remember```attribute, so you have full control over props that are loaded using ```Inertia::lazy()```

**Comment by claudiodekker** [comment] 2021-12-03 09:43
Hey @apocalyarts,

Yeah, I was considering a similar solution, and was thinking about a new `except` prop, that essentially indicates that everything should be re-fetched, except, well, the ones you provide. In a way, this would do the exact inverse of the `only` prop.

Thoughts? (cc @reinink)

**Comment by apocalyarts** [comment] 2021-12-03 09:51
Sounds perfect. I think it should be an attribute for page components (like remember).

**Comment by claudiodekker** [comment] 2021-12-03 09:54
Interesting. I only thought of it as a visit-level/`Link`-level attribute and not a page-level one. I'll give it some more thought 👍

**Comment by apocalyarts** [comment] 2021-12-03 10:07
I think a page component attribute would be perfect to define a default behaviour with very little code (just one array), but I think an attribute on a visit-level is also necessary.

Surely on the page you have at least ONE bit of code somewhere that reloads the lazyloaded props.

What would be even more crazy: a merging strategy for the lazyloaded props. I am thinking of a "pinterest"- or "kanban board"-like page where you load all the usual props (users, filter options, etc.) and then when the page is loaded you say "okay fetch 50" items. And then when the user scrolls to the bottom, do another reload with the lazyloaded prop with an offset and the response will be merged with the data already present in the lazyloaded prop (by ID or so)

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: enhancement
