### ISSUE TITLE
Scroll position not preserved on elements with scroll-region inside Vue templates

### ISSUE THREAD

**Issue by ipimpat** [inertiajs/inertia#1181] opened 2022-05-17 21:16 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue3` version: 0.5.2
- `inertiajs/inertia-laravel` version: 0.5.4

### Describe the problem:

I'm trying to have the scroll position preserved on a side menu, when certain navigation links are clicked inside the menu.

But I have problem with scroll position not being preserved on scrollable elements with the `scroll-region` attribute, if they are inside the Vue template / component.

But when placing elements outside Vue, in my Laravel view, the scroll position is preserved as expected.

### Steps to reproduce:

Placing the scrollable element inside Vue `<template>` tag does not work:

js/Pages/MyVuePage.vue

```js
<template>
    <div id="test1" style="height:250px; border: 1px solid red; overflow-y: auto; margin: 50px" scroll-region>
        <div style="height:300px; border: 1px solid yellow; margin: 50px">
        </div>
    </div>

    <Link href="http://localhost/" preserve-scroll>Foo Bar</Link>
</template>
```

Placing the scrollable element outside Vue does work:

views/app.blade.php

```html
@inertia

<div id="test2" style="height:250px; border: 1px solid red; overflow-y: auto; margin: 50px" scroll-region>
    <div style="height:300px; border: 1px solid yellow; margin: 50px">
    </div>
</div>
```

**Comment by reinink** [comment] 2023-07-28 01:52
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:52 UTC
