### ISSUE TITLE
Full page reloads on form submission possible?

### ISSUE THREAD

**Issue by mooseh** [inertiajs/inertia#1202] opened 2022-06-18 10:37 UTC
### Versions:

- `@inertiajs/inertia` version: "^0.10.0"
- `@inertiajs/inertia-vue3` version: "^0.5.1"

### Describe the problem:

I am using inertia with laravel, and I am using inertia on the login page using a separate blade page like so

```
        Inertia::setRootView('auth');
        return Inertia::render('Auth/Login'); 
```

the problem is when I submit the inertia login form there is only a partial page reload via web splitting so all the assets get missed causing the next page to not render properly. I need a way  of when submitting the form to perform a full reload, I have tried a few ways but they are all just so ugly as it loads twice.

here is what I have implemented but am unhappy with. is there a way of achieving this?

```
	this.form.post('/login', {
		onSuccess(page){
			window.location.href = page.url
			console.log(page)
		}
        }
```

**Comment by lecrackdudut** [comment] 2022-06-20 22:49
Hello, have you tried to use this instead of an Inertia "partial reload" redirect?
```php
return Inertia::location($url);
```

from https://inertiajs.com/redirects#external-redirects

**Comment by craigrileyuk** [comment] 2022-06-30 17:36
So you're creating an entirely separate blade view for the login page? Why?

Inertia has persistent page layouts for exactly this reason. Change the layout and put all your stuff in the <InertiaHead /> tag if you need to load extra scripts/styles.

**Comment by mooseh** [comment] 2022-07-08 14:57
> So you're creating an entirely separate blade view for the login page? Why?
> 
> Inertia has persistent page layouts for exactly this reason. Change the layout and put all your stuff in the tag if you need to load extra scripts/styles.

because the login blade only has about 2 prerequisites.
the app blade has about 50.

**Comment by Tofandel** [comment] 2022-07-19 11:01
In case you have multiple template, you could use versioning in your `HandleInertiaRequest` middleware

```php
    public function version(Request $request) {
        if ($request->is(['login'])) {
            return 'login-'.parent::version($request);
        }
        return parent::version($request);
    }
```

When inertia receives the json response and sees that the version is different, it will reload the page (still means 2 requests though)

The other way is simply not to use inertia for those requests, if you already know that the page is gonna load a different template just use `window.location = '/some-path';`

**Comment by najibu** [comment] 2023-03-07 12:43
> > Hello, have you tried to use this instead of an Inertia "partial reload" redirect?
> > ```
> > return Inertia::location($url);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > from https://inertiajs.com/redirects#external-redirects
> 
> So I have implemented this by overriding sendLoginResponse in the LoginController in laravel, and it is working very well, thankyou for your response @lecrackdudut, although this has made me achieve my goal I still feel that we should have the power to tell inertia to do a full reload without web splitting, could this be submitted as a feature request?
> 
> This is the resulting code fix below
> 
> ```
>     /**
>      * Send the response after the user was authenticated.
>      *
>      * @param  \Illuminate\Http\Request  $request
>      * @return \Inertia\Inertia|\Illuminate\Http\JsonResponse
>      */
>     protected function sendLoginResponse(Request $request)
>     {
> 
>         $request->session()->regenerate();
> 
>         $this->clearLoginAttempts($request);
> 
>         if ($response = $this->authenticated($request, $this->guard()->user())) {
>             return $response;
>         }
> 
>         return $request->wantsJson()
>                     ? new JsonResponse([], 204)
>                     : Inertia::location($this->redirectPath()); //redirect()->intended($this->redirectPath());
>     }
> ```

Instead of sendLoginResponse, you can just update authenticated method. 

```
protected function authenticated()
{
        $path = session()->pull('url.intended', $this->redirectPath());

        return inertia()->location($path);
 }
```

**Comment by reinink** [comment] 2023-07-28 01:52
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:52 UTC

**Comment by sonsoixam** [comment] 2024-11-04 07:52
> Hello, have you tried to use this instead of an Inertia "partial reload" redirect?
> 
> ```
> return Inertia::location($url);
> ```
> 
> from https://inertiajs.com/redirects#external-redirects

many thanks
