### ISSUE TITLE
Don't just go to the PATCH destination.

### ISSUE THREAD

**Issue by sasasa** [inertiajs/inertia#1362] opened 2022-12-19 12:56 UTC
### Version:

- `@inertiajs/react` version: "^0.8.1",

### Describe the problem:
When you add a new user
I don't go to the PATCH destination.
It jumps to the wrong index.

### Steps to reproduce:
https://github.com/sasasa/react-inertia-drag-drop-app

Please make this app work.
It is behaving strangely.

It is working correctly in vue3.
https://github.com/sasasa/laravel-vue3-inertia-drag-and-drop

**Comment by AppleNectar** [comment] 2022-12-27 18:07
@sasasa 
>Please make this app work.
>It is behaving strangely.

This is not the place to ask others to debug your application.
If you think it is a bug in this library, you will need a more detailed explanation of what occurred.

>I don't go to the PATCH destination.
>It jumps to the wrong index.

- How did you determine that ... patch was not working correctly?
  - Have you checked the contents of the request in the browser's DevTools?
- Perhaps no one will understand what "It jumps to the wrong index." means.
  - No one can read what is in your head only.

By the way, I'm using version `0.8.1` of `@inertiajs/inertia-react` and the patch function from useFrom is correctly sending patch requests.

**Comment by reinink** [comment] 2023-07-28 01:49
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:49 UTC
Labels: react
