### ISSUE TITLE
Scroll regions inside page component are not restored after form submit.

### ISSUE THREAD

**Issue by ragulka** [inertiajs/inertia#1211] opened 2022-07-01 11:07 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:

When a page, for example, an edit form contains a `scroll-region` and we use either the form helper or `Inertia.post` with `{ preserveScroll: true, preserveState: false }`, and then server redirects back to the form after a successful save, the scroll-region scroll position is reset, instead of being preserved.

When the `scroll-region` is outside the page component (in the `Layout` or the blade template, for example), it works as expected - the scroll position is maintained. This is because neither the layout nor the blade template get re-rendered.

Note that the issue only happens when using `preserveState` with either `false` or `'error'`. This is natural, because when the state is preserved, there are no DOM changes. However, when the state is refreshed from the server, the component is re-mounted, DOM changes and this resets the scroll position.

Inertia has a [`restoreScrollPositions()`](https://github.com/inertiajs/inertia/blob/e22f5bed0780b3c1066af5e4aa7929b3c71a0264/packages/inertia/src/router.ts#L95-L109) method, that seems like is built for restoring scroll positions inside scroll regions. However, this is never called after making a form submit.

What happens is that when the request is successful, [`setPage` is called with the correct `preserveScroll` flag](https://github.com/inertiajs/inertia/blob/e22f5bed0780b3c1066af5e4aa7929b3c71a0264/packages/inertia/src/router.ts#L335), but `setPage` itself only uses this flag to _reset_ scroll position to the top of the page, if `preserveScoll: false`.

This relies on the fact that if the document body is scrollable, then browsers would maintain the scroll position. However, browsers will not maintain scroll positions of the individual scroll regions inside the page component.

It seems to me that `restoreScrollPositions()` should be called somewhere in the `setPage` method, after the `swapComponent` resolves.

### Steps to reproduce:

1. Create a `scroll-region` inside a page that has a form (such as an edit page)
2. Ensure that when the form submits, it uses the `{ preserveState: 'errors', preserveScroll: true }` options. 
3. Ensure the server redirects back to the same page
4. Scroll the `scroll-region` inside the page
5. Submit the form
6. Notice how the scroll position inside the `scroll-region` is reset.

For easier reproduction, I've opened a PR on my fork with exact steps: https://github.com/ragulka/pingcrm/pull/1

Note: this issue may be related to https://github.com/inertiajs/inertia/issues/1181

**Comment by jezzdk** [comment] 2022-10-20 22:05
I think I have the same issue. Clicking a link inside a scroll-region, with preserveScroll, doesn't preserve the scroll position after the new page is loaded, even though the scroll-region is also on the new page (it's a sidebar).

**Comment by reinink** [comment] 2023-07-28 01:52
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Comment by troygilbert** [comment] 2023-08-17 15:35
I'm having this issue is well. `scroll-region` seems to be useless when used inside of a Vue component (for the reasons thoroughly described above). I'm surprised, because I would assume the test case would be using it inside of a Vue component. Also it's a shame this got closed out, because this is very much still an issue! @reinink

**Comment by jezzdk** [comment] 2023-08-17 15:50
@troygilbert As per reininks comment, you can simply open a new ticket and include the requirements as described.

**Comment by reinink** [comment] 2023-08-17 15:57
Hey happy to just reopen this one if it's still a known issue 👍

**Comment by Yiddishe-Kop** [comment] 2023-10-15 14:12
I'm experiencing the same issue

**Comment by YakuBrangJa** [comment] 2023-12-17 06:26
Same here, I have to add preserveState to get it work.

**Comment by medabkari** [comment] 2024-01-13 23:35
Experiencing the same issue here. It just doesnt seem to work within Vue components.

**Comment by axel-paillaud** [comment] 2024-01-16 06:09
Exactly the same issue here

**Comment by baoanhng** [comment] 2024-01-23 08:33
This is still happening and I am thinking of a workaround.

**Comment by axel-paillaud** [comment] 2024-01-26 05:33
Hello there,
I have started to investigate this "issue" (is it really an issue ?), and this is what I found :

In `packages/core/src/router.ts`, we have method `setPage` like so :

```javascript
  protected setPage(
    page: Page,
    {
      visitId = this.createVisitId(),
      replace = false,
      preserveScroll = false,
      preserveState = false,
    }: {
      visitId?: VisitId
      replace?: boolean
      preserveScroll?: PreserveStateOption
      preserveState?: PreserveStateOption
    } = {},
  ): Promise<void> {
    return Promise.resolve(this.resolveComponent(page.component)).then((component) => {
      if (visitId === this.visitId) {
        // console.log(page.scrollRegions) is always undefined at this stage
        // with this.page, it work
        page.scrollRegions = this.page.scrollRegions || []
        page.rememberedState = page.rememberedState || {}
        replace = replace || hrefToUrl(page.url).href === window.location.href
        replace ? this.replaceState(page) : this.pushState(page)
        this.swapComponent({ component, page, preserveState }).then(() => {
          if (!preserveScroll) {
            this.resetScrollPositions()
          } else {
            // I added this line here
            this.restoreScrollPositions();
          }
          if (!replace) {
            fireNavigateEvent(page)
          }
        })
      }
    })
  }
```

As you can see, I have added a comment where I did some modification. Like this, it works, the `scroll-region` is well-preserved on an element that have overflow set to scroll (tested on Vue3 playground).

But I have some questions, obviously I can't make a PR, because I "cheat" with `this.page` instead of `page`.

- Why, in Promise, `console.log(page.scrollREgions)` is always undefined ? I think it's because it was defined asynchronously elsewhere, but where ?

If you guys have some idea, or advice, of course, feel free to tell me. I will continue to investigate this issue, but maybe this can already be useful.

The repos with playground set with this code is available [on my GitHub account](https://github.com/axel-paillaud/inertiajs)

**Comment by axel-paillaud** [comment] 2024-02-05 06:01
Hello there,

I have made a npm module with this modification, for testing purpose on a real project.

If you want to give it a try : `npm install @inertiajs-fix-scroll/vue3` (for vue3 packages).

Then, change all occurrences of `@inertiajs/vue3` to `@inertiajs-fix-scroll/vue3` in your project.

For me, it works with Svelte, Vue3, Vue2. I can't test it with React, because I have a lot of bugs with the React playgrounds, and I don't really investigate why.

Again, it's just for testing purpose

**Comment by joecacti** [comment] 2024-06-17 15:27
Has anyone been able to successfully work around this issue for a production site?

**Comment by gtim04** [comment] 2024-06-27 02:57
Still having this issue as well. Issue where i put the scroll-region on an overflow element but still the scrollbar reset.

**Comment by pedroborges** [comment] 2024-09-12 16:16
PRs #1782 and #1803 will fully fix the issue described by @ragulka 🙌

**Closed** 2024-09-19 17:44 UTC
Labels: bug

**Comment by filecc** [comment] 2024-12-02 22:32
Ehi, sorry to bother but... is this really resolved? I cannot get it working on a Laravel+Inertia+React project. 

method
```typescript
const submit = async () => {
 router.get('/account/notification/' + notification.id , { preserveScroll: false }) 
}
```
component
```jsx
<main className="h-dvh overflow-y-hidden">
    <div scroll-region={"true"} className="overflow-y-auto">     
        <button  onClick={submit}>Notification</button>
     </div>
</main>
```
route
```php
public function notification_mark($id)
    {
      /* various operations */

        return to_route('account.notifications');
    }
```

Doesn't matter what I put in the `preserveScroll` parameter, every time scroll position get restored to the top of the page, while I would love the it stays where I clicked first. 
I already tried with the form helper, with the Link component, nothing works.
Also, doing as per the documentation
```html
<div class="overflow-y-auto" scroll-region>
  <!-- Your page content -->
</div>
```

produce a warning: 

```
Warning: Received `true` for a non-boolean attribute `scroll-region`.
```


Any help will be VERY appreciated, it's been _84 years_ ...

**Comment by liliangiraudo5** [comment] 2024-12-04 23:03
Hey @filecc,  I had the same issue as you and after looking more closely at the source code, it seems to only add an empty value to the attribute will do the job:
`<div class="overflow-y-auto" scroll-region="">
  
</div>`

[See here](https://github.com/inertiajs/inertia/blob/cd5607fb29a1eacdbda7caf85ce4cbfbe0fd3bd5/packages/react/test-app/Layouts/WithScrollRegion.jsx#L35)

I tested it on one of my projects and it works correctly 😁
