### ISSUE TITLE
Inertia v1  Router causing full page reload

### ISSUE THREAD

**Issue by xtreme2020** [inertiajs/inertia#1444] opened 2023-02-10 13:44 UTC
### **Version**
Laravel version 9.50
"inertiajs/inertia-laravel": "0.6.9",
- `@inertiajs/vue3` version: 1.0.0

### **This code works as expected**

import {Inertia} from "@inertiajs/inertia";
import debounce from "lodash/debounce";

```
watch(search,debounce(function(newValue){
        Inertia.get( route('verses.index')
            ,{search:newValue}
            ,{preserveState:true,replace: true
        });

},900));
```

 
### **this code cause full page reload**

import { router } from '@inertiajs/vue3'  
import debounce from "lodash/debounce";

```
watch(search,debounce(function(newValue){

        router.get( route('verses.index')
            ,{search:newValue}
            ,{preserveState:true,replace: true
        });

},900));

```

**Comment by lupinitylabs** [comment] 2023-02-14 01:59
I encountered the same issue with `router.reload()`, which always does a full page reload. I am not sure why this is still the recommended way according to the [official docs](https://inertiajs.com/partial-reloads)?

Instead, what does work is to use 
```javascript
import {Inertia} from "@inertiajs/inertia";

Inertia.reload();
```

**Comment by zzzet** [comment] 2023-02-16 12:18
if you have vite hmr enabled with laravel setup, there is infinite reload if you refresh the page.
with this code:

```
import { router } from "@inertiajs/react";

router.reload({ only: ["lazy_data"]});

// your react component
```

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
