### ISSUE TITLE
Form helper is not working after Vite build

### ISSUE THREAD

**Issue by RoduanKD** [inertiajs/inertia#1293] opened 2022-09-17 23:15 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue` version: 0.8.0
- `vue` version 2

### Describe the problem:

I had a Laravel 8 project with inertia and Vue 2. I recently followed the [Vite migration guide](https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md#migrating-from-laravel-mix-to-vite). and everything went fine. and I could run the `dev` command with no issues at all. But, after successfully running the `build` command. all `$inertia.form` are not working with these errors in chrome console.
```
TypeError: uy.observable is not a function
    at H.TP [as form] (app.dadbff2a.js:9:30986)
    at d.data (Login.dbf661a3.js:1:2479)
    at S2 (app.dadbff2a.js:5:32926)
    at w2 (app.dadbff2a.js:5:32724)
    at _2 (app.dadbff2a.js:5:32346)
    at E2.e._init (app.dadbff2a.js:5:34608)
    at new d (app.dadbff2a.js:5:35911)
    at qC (app.dadbff2a.js:5:21771)
    at init (app.dadbff2a.js:5:20635)
    at b (app.dadbff2a.js:5:44637)
```
and just to be clear the code that is referred to here is this one:

```js
data() {
    return {
      form: this.$inertia.form({ // (Login.dbf661a3.js:1:2479)
        email: "",
        password: "",
        remember: !1
      })
    }
  },
```
and obviously, the `uy` is `Vue` and it's saying observable is not a function in it after running `npm run build`. 

### Steps to reproduce:

I made [this repo](https://github.com/RoduanKD/inertia-vite-issue-demo) to reproduce the issue again. you can see the changes I've made to reproduce the vite issue starting from this [commit](https://github.com/RoduanKD/inertia-vite-issue-demo/commit/73062e97551fa6969de760958c371a022c3d64f3)

please follow the steps to run the project (sorry if they're obvious)
- clone the repo
- `composer i`
- `cp .env.example .env`
- `php artisan key:generate`
- `npm i`
- `npm run build`
- `php artisan serve`
- navigate to `/login` to see the login form and the error will be there

### Notes:
- Vue version is 2.7.0 (greater than 2.6.0)
- It's perfectly working in dev mode
- it was working using webpack
- I'm using windows and I've tried it on Ubuntu (staging server)

Thanks in advance for checking this really weird issue! and I hope you've got enough information to resolve this one

**Comment by giorgiopogliani** [comment] 2022-09-20 10:55
@RoduanKD I tried your project and besides that with vue 2.7 you should use `@vitejs/plugin-vue2` and not `@vitejs/plugin-vue` or `vite-plugin-vue2` the problem looks like a bug. 

I opened a terminal at `node_modules/@inertiajs/inertia-vue`, run `npm install && npm run build` then I rebuilded your preject and it worked..

**Comment by RoduanKD** [comment] 2022-09-20 11:45
thank you! @giorgiopogliani 
I switched to `@vitejs/plugin-vue2` but the issue remained there. but it worked well when I applied your instructions here:

> I opened a terminal at `node_modules/@inertiajs/inertia-vue`, run `npm install && npm run build` then I rebuilt your project and it worked.

is there a way to prevent running the `build` command in `inertia-vue`?

**Comment by ivalkenburg** [comment] 2022-10-08 15:52
Got the same issue, what worked for me was adding the the following alias:

```js
export default defineConfig(({ command }) => ({
  //
  resolve: {
    alias: {
      //
      ...(command === "serve" ? {} : { "@inertiajs/inertia-vue": "node_modules/@inertiajs/inertia-vue/src/index.js" }),
    },
  },
}
```
It only adds this alias during building, it will break when running in development

**Comment by RoduanKD** [comment] 2022-10-08 16:25
thanks, @ivalkenburg I think this could be a temporary fix. For me, the form is working in `dev` mode. is it the same case for you?

**Comment by ivalkenburg** [comment] 2022-10-08 19:22
> thanks, @ivalkenburg I think this could be a temporary fix. For me, the form is working in `dev` mode. is it the same case for you?

Yes, it works after building and during dev mode for me.

**Comment by kitro** [comment] 2022-10-30 15:06
I have the same issue after upgrading to Vite 3, with `"vue": "^2.7.0" ` the form helper `this.$inertia.form` throws an exception, and breaks the rendering page.

```
Error in data(): "TypeError: hp.observable is not a function"
```

The @ivalkenburg  solution https://github.com/inertiajs/inertia/issues/1293#issuecomment-1272346695 works well.
Thank you,

**Comment by reinink** [comment] 2023-07-28 01:50
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:50 UTC
