### ISSUE TITLE
Redirect back without refresh all vue view

### ISSUE THREAD

**Issue by leocharrua** [inertiajs/inertia#1024] opened 2021-01-29 14:53 UTC
I have a vue view with a form that opens a modal window.
Inside the modal I have a vue component with a form that invokes inertia:

	```
      this.$inertia.put(
        this.route("team_employees.update", this.model.id),
        this.form,
        {
          onStart: () => (this.sending = true),
          onFinish: () => {
            this.sending = false;
            this.$emit("on-finish");
          },
        }
    );
```
	
The controller has the rules validation:

		```
        $validator = Validator::make(Request::all(), TeamEmployee::rules());
        if ($validator->fails()) {
           return redirect()->back()->withErrors($validator->errors()->messages());
        }
        return redirect()->back()->with('success', __('Item created successfully.'));
```		

When all is ok, all works great, because the parent form refresh, showing the success flash message. In this case, the modal is not needed anymore and it's perfect refresh the parent form.

The problem is when the controller find validation errors, that must be shown inside the modal.
Instead, the parent view is refreshed (I don't see the modal anymore) and shows the error flash message.

I tried changing the controller:

	```
    if ($validator->fails()) {
       return response()->json(['errors' => $validator->errors()->messages()]);
    }
```

In this case, I get the error in the modal (like I want), with this message:

	_All Inertia.js requests must receive a valid Inertia.js response, however a return plain JSON response was received._
	
but the form is not showing inside the modal.

Is there any way to go back to the view without refresh all view and only refresh the field errors inside the modal?

Thanks

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 2
