### ISSUE TITLE
preserveState: false work on dev but not work on production server

### ISSUE THREAD

**Issue by andrewizmaylov** [inertiajs/inertia#1220] opened 2022-07-08 18:53 UTC
### Versions:

- `@inertiajs/inertia` version: ^0.10.0
- `@inertiajs/inertia-vue3` version: ^0.5.1

### Describe the problem:
In my code I have several conditionally rendered components and tab menu wich define the active one.
Each component has it's own logic for load the part of content after user push the button.
I have a problem on production mode. 
If I load all parts of content for component-1, select component-2, than come back - component-1 keep the state and show me all parts of content dispite that I put `{preserveState: false}` in Inertia.get() 
But at the same time `{preserveState: false}` work well in dev mode.

```
<template>
	<div>
		<section>
			<navigation-element  :element="element" v-for="element in navigation @clicked="changeActive" /> 
		</section>


		<!-- lesson's tabs -->
		<lintro class="" :lesson="lesson" :course="course" v-if="$page.url.indexOf('intro') >= 0" />
		<ldictionary class="" :lesson="lesson" :course="course" v-if="$page.url.indexOf('dictionary') >= 0"  />
		<lclass class="" :lesson="lesson" :course="course" v-if="$page.url.indexOf('class') >= 0"  />
		<ltools class="" :lesson="lesson" :course="course" v-if="$page.url.indexOf('tools') >= 0"  />
		<lexam class="" :lesson="lesson" :course="course" v-if="$page.url.indexOf('exam') >= 0"  />
		<lpractice class="" :lesson="lesson" :course="course" v-if="$page.url.indexOf('practice') >= 0"  />
	</div>
</template>
<script setup>
	import {ref, computed, onMounted, reactive} from 'vue'
	import { Inertia } from '@inertiajs/inertia'
	import navigationElement from '@/Pages/modules/navigationElement.vue'

	import lintro from '@/Pages/lesson/_intro.vue'
	import ldictionary from '@/Pages/lesson/_dictionary.vue'
	import lclass from '@/Pages/lesson/_class.vue'
	import ltools from '@/Pages/lesson/_tools.vue'
	import lexam from '@/Pages/lesson/_exam.vue'
	import lpractice from '@/Pages/lesson/_practice.vue'


	const props = defineProps(['lesson', 'tab', 'course', 'course_progress'])
	const navigation = ref([
		{id: 0, action: 'intro', name: 'Intro'},
		{id: 1, action: 'dictionary', name: 'Dictionary'},
		{id: 2, action: 'class', name: 'Class'},
		{id: 3, action: 'tools', name: 'Tools'},
		{id: 4, action: 'exam', name: 'Quizess'},
		{id: 5, action: 'practice', name: 'Assignment'},
	])

	function changeActive(input) {
		Inertia.get(window.location.pathname, {tab: input.action}, {preserveState: false, preserveScroll: true });
	}
</script>
```

**Comment by reinink** [comment] 2023-07-28 01:52
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:52 UTC
