### ISSUE TITLE
Cannot read property 'toString' of undefined, at Object.h [as mergeDataIntoQueryString]

### ISSUE THREAD

**Issue by luiyongsheng** [inertiajs/inertia#744] opened 2021-06-10 18:54 UTC
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.6

### Describe the problem:

After upgrading from the default versions of `@inertiajs/inertia` and `@inertiajs/inertia-vue3` stated by `laravel/jetstream`, every page broken, EXCEPT `Welcome.vue`

### Screenshots:

![image](https://user-images.githubusercontent.com/13586871/121581305-42b8a380-ca60-11eb-9d83-9aac26f1b5ea.png)

**Comment by reinink** [comment] 2021-06-10 19:28
Thanks for submitting this. I've been able to reproduce this, and I'm working on a patch. 👍

**Comment by reinink** [comment] 2021-06-10 19:37
Fixed (8ee916703b408db1ff0d4dc318a79a12af566bb4) and released as `0.4.7`.

**Comment by luiyongsheng** [comment] 2021-06-10 20:56
The issue still persists after upgrading to `0.4.7`

**Comment by reinink** [comment] 2021-06-10 20:58
Shoot. I'll try to install Jetstream and see if I can reproduce it.

**Comment by luiyongsheng** [comment] 2021-06-17 02:08
any updates?

**Closed** 2021-06-25 04:54 UTC

**Comment by dangerdan** [comment] 2021-07-01 16:49
Why was this closed again @luiyongsheng ? I'm also still seeing this issue with 0.4.7.

**Comment by azizk17** [comment] 2021-07-07 15:13
I had the same issue a while ago when I upgraded to vue3, it turns out that the issue was occurred because href prop was missing from one of inertia-link component.

**Comment by dangerdan** [comment] 2021-07-11 12:29
I can confirm that was also my problem @azizk17 - thank you for your help!
