### ISSUE TITLE
Inertia reloads in a frame after few minutes of inactivity

### ISSUE THREAD

**Issue by SerGioPicconti** [inertiajs/inertia#92] opened 2019-10-25 06:26 UTC
Hi!

I have a problem on prod server.

If I open page first time and goes through links - everything is ok, but if I don't touch anything and after 3-5 minutes come back and click any inertia-link - it's just reloads current page in a new frame (like errors modal).

Does anyone has same issue?

**Comment by SerGioPicconti** [comment] 2019-10-25 07:23
> Hello @SerGioPicconti !
> 
> This sounds like your session is expired. Could you have a look if this might be the cause of your issue?
> 
> For me this happens when I run a bare-bones InertiaJS app and my login session is expired.
> 
> Hope this helps!

Hi!
Unfortunately that's not session expired(

When it's loads in a frame - user is logged in. Everything is ok except page is loads in a frame(
Temporary changed all links to standard href's (not inertia) - but with that pages loading takes too much time(

**Comment by enzonotario** [comment] 2019-10-26 14:16
I have a simiilar issue... also when you close the tab, and then reopen it (with CTRL + SHIFT + T). I'ts weird... I always open 2 modals. But I can close them and all works fine...

**Comment by SerGioPicconti** [comment] 2019-10-27 12:00
> I have a simiilar issue... also when you close the tab, and then reopen it (with CTRL + SHIFT + T). I'ts weird... It always open 2 modals. But I can close them and all works fine...

Yep
Exactly same happened with me.

**Comment by reinink** [comment] 2019-10-28 11:11
Hey folks, are there specific steps that you can give me to reproduce this? I've been trying, but can't.

Also, what adapters are you using for the server-side and client-side?

Finally, do you have asset versioning enabled?

**Comment by enzonotario** [comment] 2019-10-28 14:28
I'm using inertia-laravel + inertia-vue (+ vuetify, maybe it's also related). But maybe it's related to the asset versioning.
I have multiple "apps", for example a `website` and a `dashboard`. I know that the asset versioning is not working very well as an "normal" Inertia project does because if there are any changes, I have to refresh the tab, it doesn't auto-refresh as the pingcrm does, for example.

I tried to replicate my setup in pingcrm but I can't reproduce it :( https://github.com/enzonotario/pingcrm/commit/caf1cbb69d4483acb94529236d35491b0cb96daa

If you want, one thing I could do is give access to our app, so you can see what happens in the browser, if it helps to resolve this issue...

**Comment by reinink** [comment] 2019-11-07 12:47
Hey @enzonotario, I'd really prefer a simple demo app that has one commit to install Laravel, and the next to setup the issue. It allows us to quickly see the issue, and solve it if necessary.

**Comment by reinink** [comment] 2019-11-07 12:50
@SerGioPicconti Have you set any custom Axios headers? Please inspect the request headers to ensure that the `X-Inertia` header is set.

Beyond that, I'm honestly not sure what could be wrong. I'd again ask for a demo app that reproduce this, with specific steps. Otherwise it's super hard for me to debug.

Closing this for now, until more information is provided.

**Closed by reinink** 2019-11-07 12:50 UTC
