### ISSUE TITLE
React TypeScript: `useForm`'s generic is forcing to use `type` where `interface` won't work

### ISSUE THREAD

**Issue by xsjcTony** [inertiajs/inertia#1431] opened 2023-02-04 10:43 UTC
### Version:

- `@inertiajs/react` version: `v1.0.0`

### Describe the problem:

The following code won't work
```tsx
interface TestInterface {
  test: string
}

const _ = useForm<TestInterface>()
// Type 'TestInterface' does not satisfy the constraint 'Record<string, unknown>'.
// Index signature for type 'string' is missing in type 'TestInterface'.
```
while the following works
```tsx
type TestType = {
  test: string
};

const _ = useForm<TestType>()
// it works
```
### Steps to reproduce:

See above

### Suggestions

I don't see there's any reason to use `unknown` instead of `any` here, and I always prefer to use `interface` over `type` so it's frustrating for me. 

Change this ( `Record<string, unknown>` to `Record<string, any>` )
```ts
export default function useForm<TForm extends Record<string, unknown>>(initialValues?: TForm): InertiaFormProps<TForm>;
export default function useForm<TForm extends Record<string, unknown>>(rememberKey: string, initialValues?: TForm): InertiaFormProps<TForm>;
```
to 
```ts
export default function useForm<TForm extends Record<string, any>>(initialValues?: TForm): InertiaFormProps<TForm>;
export default function useForm<TForm extends Record<string, any>>(rememberKey: string, initialValues?: TForm): InertiaFormProps<TForm>;
```
solves the issue for me, just like in `react-hook-form`
```ts
export declare function useForm<TFieldValues extends FieldValues = FieldValues, TContext = any>(props?: UseFormProps<TFieldValues, TContext>): UseFormReturn<TFieldValues, TContext>;

export type FieldValues = Record<string, any>;
```

**Comment by xsjcTony** [comment] 2023-05-12 08:13
Any update?

**Comment by alexrififi** [comment] 2023-06-23 12:17
Ran into this today as well..

**Comment by ARusDian** [comment] 2023-07-24 23:59
any update from devs?

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
Labels: react
