### ISSUE TITLE
`useForm` data is not reactive/looses reactivity

### ISSUE THREAD

**Issue by LouisHaftmann** [inertiajs/inertia#1304] opened 2022-09-26 17:05 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:

`useForm` data is not reactive/looses reactivity. It probably is caused by the spreading of `restored.data` or `data` in 

https://github.com/inertiajs/inertia/blob/6e6fba7e2bb276416e81c338374da925bb92a4cf/packages/inertia-vue3/src/useForm.js#L16

When spreading a (reactive) object, the reactivity of its properties is lost. 

### Steps to reproduce:

```typescript
const form = useForm({
  name: '',
  email: ''
})

watch(form, (val) => console.log(val)) // not logging
watch(() => form, (val) => console.log(val)) // not logging
watch(() => form.name, (val) => console.log(val)) // not logging

// random data change
setTimeout(() => {
  form.name = 'Test Name'
  form.email = 'test@test.com'
}, 1000)
```

### Possible solution

With `toRefs()` it is possible to convert a reactive object to an object with it's properties tranformed into `ref`s which _can_ be spread, because the properties **themselves** are reactive. 
`ref`s spread inside a `reactive` are automatically unwrapped and preserve reactivity:
https://vuejs.org/api/reactivity-core.html#reactive

➡️  Instead of spreading the data object, it would probably be easier to create a new top level property only for form data:

```js
reactive({
  data: reactive(restored ? restored.data : data), // would replace data(), rename?
  isDirty: false,
  errors: restored ? restored.errors : {},
  hasErrors: false,
  processing: false,
  progress: null,
  wasSuccessful: false,
  recentlySuccessful: false,
  // ...
})
```

**Comment by Asharif88** [comment] 2023-03-22 18:47
I don't know why no one answered this, but I spent hours trying to debug this until I found your issue, I'm facing the exact same behavior.

Adding some details in case someone else is facing my scenario

I'm using one component for add and edit, when the creation is done I initiate an Inertia::render with the same component but updated data, all the reactive props work as expected (I'm looping one of the props to generate the fields and using v-model based on the form object).

now I get errors thrown since useForm didn't update so the object doesn't match the updated prop.

This is doubly annoying since using a "hard" redirect seems to be the only option.

Hope this gets some attention

**Comment by mhelaiwa** [comment] 2023-05-12 16:07
For me this works, but I really don't know if this is the best way!!

**Comment by mhelaiwa** [comment] 2023-05-12 16:14
This works for me. Actually, I came here to search if this is the ideal way to do so.
I use `useForm` with a modal html form. and I use `editSection()` and `close()` to fill and reset the form.
I think it would be nice if there is a function like `fill()` and `clear()` to do this work.
@reinink 

```
const defaultSectionForm = {
    id: null,
    display_name: '',
    active: false,
};

let sectionForm = useForm(<Section>{...defaultSectionForm});

const editSection = (section) => {
    sectionForm.defaults({...section}).reset();
    sectionsModal.value = true;
}

const close = () => {
    sectionsModal.value = false;
    sectionForm.defaults({...defaultSectionForm} as Record<Section,'section'>).reset()
}
```

**Comment by reinink** [comment] 2023-07-28 01:50
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:50 UTC
