### ISSUE TITLE
Http 409 from laravel exception view.

### ISSUE THREAD

**Issue by ssengineers** [inertiajs/inertia#1330] opened 2022-10-28 11:33 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: 0.7.2

### Describe the problem:

So I am using Inertia with Vue2 in our laravel application. I am using a layout for the entire app with inertia link's, which allows me to use a persistent audio player in my apps header.

I have used the global middleware to make sessions persist into Exception handlers. and I am using Inertia::render('Error', [$data]) for my exceptions page handlers let say for example 404.

but when navigating away from the exception handler inertia view, a 409 conflict happens and the page has to perform a full load killing my header player.

### Steps to reproduce:

- user goes to /home with no problem and starts playing a podcast in the header.
- user clicks a link to another valid page and the player continues to play with no problem.
- user clicks a link to a page which returns 404 and shows the inertia rendered error page and the player still continues playing
- the user clicks the "go back" link (or any link for that matter) which is an inertia link but the player stops playing and a full reload is -performed

**Comment by mooseh** [comment] 2022-11-01 12:31
This has been resolved by some reasearch on laracasts here: https://laracasts.com/discuss/channels/general-discussion/what-is-a-409-error-and-how-can-i-fix-it?page=1&replyId=845016

basically this line before the exception page fixed it
```
        Inertia::version(function () {
            return md5_file(public_path('mix-manifest.json'));
        });
```

**Comment by reinink** [comment] 2023-07-28 01:50
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:50 UTC
