### ISSUE TITLE
Some pages open in iframe modal.

### ISSUE THREAD

**Issue by iAbbos** [inertiajs/inertia#1366] opened 2022-12-28 07:33 UTC
### Version:

- `@inertiajs/vue3` version: 0.6.0

Some pages open in iframe modal. If there is no RCPC cookie. 
![image](https://user-images.githubusercontent.com/50768679/209775202-f987d583-3e02-4fab-998a-2392d4221b9e.png)
When I first time visit the page it sets RCPC cookie and returns html response:
![image](https://user-images.githubusercontent.com/50768679/209776590-ac09ef1c-1e64-460e-9042-50450faeef6d.png)

![image](https://user-images.githubusercontent.com/50768679/209777000-603cc1e3-b609-40f8-bb0e-972091dae28a.png)

And after setting RCPC cookie it returns json response:
![image](https://user-images.githubusercontent.com/50768679/209777179-ea33d9d0-691e-4704-9466-aff3fb6485a5.png)

If there is RCPC cookie every page work without a problem.
![image](https://user-images.githubusercontent.com/50768679/209775394-a37553c6-95cb-46e9-9519-764327456b08.png)

My UserController:
![image](https://user-images.githubusercontent.com/50768679/209775612-319d2f8d-bc1f-4344-8299-dc8fbdc62ae4.png)

JS resources:
![image](https://user-images.githubusercontent.com/50768679/209776071-6c467367-07dd-49e6-bde4-cd6e3a2bc984.png)

app.js:
![image](https://user-images.githubusercontent.com/50768679/209776152-43144766-d845-4944-a3b8-609be7a355b4.png)

- What is RCPC cookie ?
- This problem happens only in production hosting server. In localhost everything is ok.

**Comment by craigrileyuk** [comment] 2023-01-04 14:34
I don't believe that the RCPC has anything to do with Inertia.

Pages load in a modal when you send an Inertia request via a controller that does not return an Inertia response. I would suspect that something about that cookie is causing your application to load a separate stack of Middleware, one that doesn't include `HandleInertiaRequests`.

**Comment by iAbbos** [comment] 2023-01-06 05:22
> 

Thank you for your answer.  I appreciate it. Unfortunately it did not help me. 

I think that it depends on something like route length.

![image](https://user-images.githubusercontent.com/50768679/210934998-2ecbfd45-a610-476b-b42d-c91534fd28bf.png)

1st and 3rd routes works properly. But the 2nd route opens in iframe modal. And network bar shows this result:

![image](https://user-images.githubusercontent.com/50768679/210935547-270cd102-9731-43b2-b909-3ee1f21aab1b.png)

**Comment by reinink** [comment] 2023-07-28 01:49
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:49 UTC
