### ISSUE TITLE
Typescript error when child is added to the Inertia Head component.

### ISSUE THREAD

**Issue by benbjurstrom** [inertiajs/inertia#1253] opened 2022-08-14 20:29 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11
- `@inertiajs/inertia-react` version: 0.8.0

### Describe the problem:
A typescript error if a child is added to the Inertia `<Head>` component.

### Steps to reproduce:

```
import { Head } from '@inertiajs/inertia-react'
...
        <Head>
          <meta name="description" content="Example description" />
        </Head>
```

Gives the following error:
`error TS2559: Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & InertiaHeadProps'.`

Looks like there's a couple pull requests to fix the issue. I'd recommend merging in this one: https://github.com/inertiajs/inertia/pull/1210

**Comment by mohammad-hassani** [comment] 2022-10-02 14:53
@reinink that's right, please do it

**Comment by reinink** [comment] 2023-07-28 01:51
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:51 UTC
Labels: react
