### ISSUE TITLE
JSON displayed instead of page / component

### ISSUE THREAD

**Issue by rjdaini22** [inertiajs/inertia#1591] opened 2023-06-15 06:59 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.6

### Describe the problem:

When using a mobile device, specifically the Chrome or Firefox mobile browsers, I encounter a problem. After loading a page on my application and closing the browser, upon reopening it, I see JSON code instead of the expected page. Additionally, there are instances where it reloads the previous page I was on before being redirected. Another issue occurs when I log out and close the browser. Upon reopening it, I am automatically redirected to the dashboard, which is a page accessible only when logged in. To be redirected on the login page, I have to manually refresh the page.

### Steps to reproduce:

To get the JSON display (this issue can be caused without being logged) :
1. Log into the application.
2. Click on the application logo or another link.
3. Close the mobile browser.
4. Reopen the browser.

To load the dashboard page after logout :
1. Log into the application.
2. Click on the logout button inside the menu.
3. Close the mobile brower.
4. Reopen the browser.

The attached file is an example of the JSON data being shown instead of my page. It's the date inside my props when i'm not logged into the application.
![Screenshot_20230615-085126](https://github.com/inertiajs/inertia/assets/45245075/f187d94f-0b2d-4f13-88d3-ff623e7f4f1e)

**Comment by reinink** [comment] 2023-07-28 01:07
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:07 UTC

**Comment by magnokf** [comment] 2024-07-15 13:11
#<IfModule mod_headers.c> 
<FilesMatch ".(js|css|xml|gz|html)$"> Header append Vary: Accept-Encoding
 </FilesMatch>
</IfModule>#

Add it to .htaccess file

**Comment by deshazer** [comment] 2025-02-24 20:11
Sorry to necro-post, but we were also struggling with this. We did figure out what was going on though, and maybe it can help others.

This was happening on both mobile and desktop. Testing was done using Chrome. 

The reason this happens is because Chrome "backgrounds" your tab or marks it "inactive" to save memory. When you come back to the tab, Chrome sees that there was recently an XHR HTTP GET request to the same address as you have in your browser's URL. That's just the way Inertia works when doing its version of client side navigation. However, because the response that came back from that XHR request is just JSON, Chrome tries to be "helpful" and just shows that content to the end user. 

Pro tip: you can go to `chrome://discards/` to see a list of all tabs and you can click "urgent discard" to force a tab into this "inactive" state. This make reproducing the issue easier. 

This behavior should be prevented by having the `Vary: X-Inertia` header present in Inertia responses. That header tells your browser that a difference in the `X-Inertia` header should be considered a different request. When `Vary: X-Inertia` correctly comes back in the Inertia response, your browser will simply reload the page when you come back to an inactive tab. Problem (supposedly) solved!

So, you'd think we'd never have had this issue, because Inertia is already doing what it's supposed to do! Right?? Right?!?

Well, our app in production was returning two `Vary` headers separately. 
```
Vary: Accept-Encoding
Vary: X-Inertia
```
We had our app deployed to AWS behind a CloudFront distribution. CloudFront only takes the first instance of a header and passes it back to the client. Not only that, but CloudFront specifically says (albeit in some old documentation I found) that it only allows the `Vary` header to be set to `Accept-Encoding`. So, we had to add a Response Header Policy with `Vary: Accept-Encoding, X-Inertia`. Now that comes back with all requests to the client and we haven't had ugly JSON shown to users since!

Hope this helps someone!
