### ISSUE TITLE
SSR error: Error [ERR_REQUIRE_ESM]: require() of ES Module ...\node_modules\@inertiajs\vue3\dist\index.js from C:\workspace\7DTD DB\storage\ssr\ssr.js not supported.

### ISSUE THREAD

**Issue by freelancefrivas** [inertiajs/inertia#1636] opened 2023-08-03 05:45 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.9

### Describe the problem:

Running  php artisan inertia:start-ssr throws this error:
var vue3 = require("@inertiajs/vue3");
           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module \node_modules\@inertiajs\vue3\dist\index.js from C:\workspace\7DTD DB\storage\ssr\ssr.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in \node_modules\@inertiajs\vue3\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
    at Object.<anonymous> (\storage\ssr\ssr.js:2:12) {
  code: 'ERR_REQUIRE_ESM'
}

### Steps to reproduce:
` php artisan inertia:start-ssr`

ssr.js:
```
import '../css/app.scss';
import { createInertiaApp } from '@inertiajs/vue3';
import createServer from '@inertiajs/vue3/server';

import {renderToString} from '@vue/server-renderer'
import {createSSRApp, h} from 'vue'
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
/* import the fontawesome core */
import {library} from '@fortawesome/fontawesome-svg-core'
/* import specific icons */
import {faCaretRight, faCaretLeft} from '@fortawesome/free-solid-svg-icons'
/* add icons to the library */
library.add(faCaretRight, faCaretLeft);

createServer(page =>
    createInertiaApp({
        page,
        render: renderToString,
        resolve: name => {
            const pages = import.meta.glob('./Pages/**/*.vue', {eager: true})
            return pages[`./Pages/${name}.vue`]
        },
        progress: {
            color: '#755D43',
        },
        setup({App, props, plugin}) {
            return createSSRApp({
                render: () => h(App, props),
            }).use(plugin)
                .component("Link", Link)
                .component("Head", Head)
                .component('font-awesome-icon', FontAwesomeIcon)
        },

    }),
)
```

This was discussed in #1442 and #1475 , but not solved.
Any help?

**Comment by marcelodelta** [comment] 2023-08-08 18:37
Did I get it resolved?

Yes, I have the same issue

**Comment by jeanlucnguyen** [comment] 2023-08-10 13:14
same issue here

**Comment by freelancefrivas** [comment] 2023-08-10 17:31
I managed to make SSR run with a fresh install, using the latest stable versions of Inertia, Vite, Vue, etc, although I'm now having some other problems on specific pages.
package.json:
`{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build && vite build --ssr"
    },
    "devDependencies": {
        "autoprefixer": "^10.4.14",
        "axios": "^1.1.2",
        "laravel-vite-plugin": "^0.7.5",
        "postcss": "^8.4.27",
        "sass": "^1.64.2",
        "tailwindcss": "^3.3.3",
        "vite": "^4.0.0"
    },
    "dependencies": {
        "@fortawesome/fontawesome-svg-core": "^6.4.2",
        "@fortawesome/free-solid-svg-icons": "^6.4.2",
        "@fortawesome/vue-fontawesome": "github:fortawesome/vue-fontawesome",
        "@inertiajs/vue3": "^1.0.9",
        "@vitejs/plugin-vue": "^4.2.3",
        "@vue/server-renderer": "^3.3.4",
        "vue": "^3.3.4"
    }
}
`
vite.config.js:
`import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue'

export default defineConfig({
    resolve: {
        alias: {
            ziggy: 'vendor/tightenco/ziggy/dist/vue.es.js',
        },
    },
    plugins: [
        laravel({
            input: [ 'resources/js/app.js'],
            ssr: 'resources/js/ssr.js',
            refresh: true,
        }),
        vue(),
    ],
  css: {
        preprocessorOptions: {
            scss: {
                additionalData: `

              @import "./resources/css/_variables.scss";

            `
            }
        }
    }
});
`
ssr.js (ziggy not working right yet):
`import {createInertiaApp, Head, Link} from '@inertiajs/vue3'
import createServer from '@inertiajs/vue3/server'
import {renderToString} from '@vue/server-renderer'
import {createSSRApp, h} from 'vue'
import {ZiggyVue} from 'ziggy';
import route from '../../vendor/tightenco/ziggy/dist/index.es';


createServer(page =>
    createInertiaApp({
        page,
        render: renderToString,
        resolve: name => {
            const pages = import.meta.glob('./Pages/**/*.vue', {eager: true})
            return pages[`./Pages/${name}.vue`]
        },
        setup({App, props, plugin}) {
            const Ziggy = {
                // Pull the Ziggy config off of the props.
                ...props.initialPage.props.ziggy,
                // Build the location, since there is
                // no window.location in Node.
                location: new URL(props.initialPage.props.ziggy.url)
            }
            return createSSRApp({
                render: () => h(App, props),
            }).use(plugin).use(ZiggyVue)
                .component("Link", Link)
                .component("Head", Head)
                .mixin({
                    methods: {
                        route: (name, params, absolute, config = Ziggy) => route(name, params, absolute, config),
                    },
                })
        },
    }),
)
`

**Comment by reinink** [comment] 2023-08-16 12:34
Hey! Can you please provide a (very) minimal reproduction of this issue as a Git repo so that we can recreate this problem?

My gut is that this isn't an Inertia specific issue, but rather just an issue with the implementation of this app that's causing SSR issues in Vue.

**Comment by reinink** [comment] 2023-08-31 10:45
Going to close this one for now since we haven't received a minimal reproduction of this issue as a Git repo, but happy to look at it again if someone is able to provide that 👍

**Closed by reinink** 2023-08-31 10:45 UTC

**Comment by st-huunguyen** [comment] 2023-09-03 13:37
I use webpackNodeExternals and configure it as follows :

```js
  .webpackConfig({
    target: 'node',
    externals: [webpackNodeExternals({
      allowlist: [
        '@inertiajs/vue3',
        ...[ any package has the same problem ]...,
      ]
    })]
  })
```
