### ISSUE TITLE
Bug cross-browser opening a page in a modal window

### ISSUE THREAD

**Issue by Fenix-dw** [inertiajs/inertia#969] opened 2021-11-11 19:38 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-vue3` version: 0.5.1

### Describe the problem:

The video shows that the page opens in a modal window, this is observed only in the latest chrome version
https://www.awesomescreenshot.com/video/5982047?key=fac39a963ada800d3e57136ebff67b17

### Steps to reproduce:

this problem is only seen in chrome

**Comment by OmarBouziane** [comment] 2021-11-29 13:59
Hey, I have the same issu, did you find any solution?

**Comment by claudiodekker** [comment] 2021-12-02 17:17
Hey,

I've just tried to reproduce this in the latest Chrome version, but am unable to reproduce this. 
Are you sure this isn't caused by a browser extension or something?

**Comment by OmarBouziane** [comment] 2021-12-02 17:27
Hey, 

For me, it doesn't reproduce all the time, and I can't figure out when and how exactly it reproduces... Maybe you can try many times after refreshing the page to confirm? 

Thank you

**Comment by reinink** [comment] 2023-07-28 01:56
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:56 UTC
Labels: help wanted, investigate, vue 3
