### ISSUE TITLE
Cached response return non-inertia response

### ISSUE THREAD

**Issue by renepardon** [inertiajs/inertia#1013] opened 2021-12-16 07:00 UTC
### Versions:

```
"@inertiajs/inertia": "^0.10.0",
"@inertiajs/inertia-vue3": "^0.5.1",
"@inertiajs/progress": "^0.2.6",
```

### Describe the problem: / Steps to reproduce

Because #154 is closed already

I had the same issue yesterday and I can confirm, that when using [spatie/laravel-varnish](https://github.com/spatie/laravel-varnish) which provides the **cachable** middleware. Within this middleware the cache header is set to public with a max-age of `60*24*26`. After removing this header and cleaning up the browser cache completely, everything works as expected. With a cache header set, the response gets converted to a non-inertia respones and therefore it opens in an iframe rather than within the existing DOM.

### Question/Suggestion

Right now, the SSR is not yet available to the public but will it be possible to use cached responses with SSR? That would help a lot.

**Comment by ajnsn** [comment] 2021-12-16 08:44
Hey @renepardon 
Not looking deeper into this response cache issue, is it still a thing to cache whole responses when building an App / SPA today? Just curious because I typically `Cache::remember` the underlying DB / external API queries. 

The (JSON) response itself should not have any huge impact as it's normally also gzipped?

**Comment by renepardon** [comment] 2021-12-16 09:01
It's just about a micro optimization to prevent additional round trips to the laravel framework/backend at all because static pages don't change frequently, so I can deliver them immediately through Varnish.
For all the other pages which have database requests and dynamic contents I agree that the gzipped JSON response is totally enough and if not I can cache the DB results.

**Comment by RobertBoes** [comment] 2021-12-16 10:27
I think a reason why this might be happening is that Inertia sends 2 different responses based on the request. The initial request returns HTML, but every subsequent request made with Inertia returns JSON, which is based on the `X-Inertia: true`request header. So if a request is first made to `/home` the HTML gets cached, then if you access that page through Inertia it's expected to return JSON, but since it's fetched from cache HTML is returned and that'll show up in the error modal. 
One thing you could try is to differentiate between requests and not cache the response when the `X-Inertia: true` header is present, or cache different versions. I haven't worked with Varnish, so I'm not sure if that's easily possible, at first glance it doesn't look like that's easily done with the `spatie/laravel-varnish` package.

**Comment by renepardon** [comment] 2021-12-16 10:42
@RobertBoes the `spatie/laravel-varnish` package adds a middleware which can be used on routes for example, which I did to wrap the static pages. This middleware adds the `Cache-Control header with values: public, max-age=60*24*60` and also an additional header `X-Cacheable` to inform varnish to cache the response for subsequent requests to prevent the laravel application from being accessed again.
This way there is no way to check for **X-Inertia** on the second InertiaJS request (for example through an additional middleware) because Varnish will already respond with the HTML version of the requested page.

**Comment by RobertBoes** [comment] 2021-12-16 10:57
@renepardon Yeah, I know, that's why I said it doesn't look like it's possible to do with the linked package. However, Varnish does have a few options to configure what and how to cache.

For example, the default hash key doesn't account for the `X-Inertia` header, you could add that so it'll cache different versions, see https://varnish-cache.org/docs/7.0/users-guide/vcl-hashing.html
You could possibly also use the `Vary` header, because Inertia uses the `Accept` header, to make it possible to return either HTML or JSON. See https://varnish-cache.org/docs/7.0/users-guide/increasing-your-hitrate.html#http-vary for more info on it for Varnish

**Comment by ajnsn** [comment] 2021-12-16 10:58
Not caching the same URl will be some sort of chicken or the egg.

You propably need to tell your proxy/cache server to bypass the cache if it's a subsequent request. Either by creating a webserver/proxy rule looking for the Inertia-header or trigger/decide it client side. I haven't used Varnish as well but maybe you could use a different port/host or ... something else :)

**Comment by renepardon** [comment] 2021-12-16 11:06
@RobertBoes @ajnsn ok, thank you guys. 
I will read about that the next days and come back as soon as I have a solution for this. I hope I can make it work with the distinction between HTML and JSON responses through Varnish. But first I need to install and setup Varnish - I only added the _Cache-Control_ header in advance and got already the problems as mentioned above.

**Comment by jez500** [comment] 2022-02-21 20:03
Following this as I have a similar issue, I want to use a CDN that relies on the `cache-control` header to know if a page is cacheable, but it seems that using cache-control with `public` and `max-age` breaks inertia due to the same url being used for html and XHR requests

What could potentially solve this is if inertia appended a change to the url. Eg a query parameter such as `?format=json` 

If anyone comes across any other solutions, I'd love to know

**Comment by reinink** [comment] 2023-07-28 01:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:54 UTC
Labels: vue 3

**Comment by mattwigham** [comment] 2024-10-18 22:34
For anyone like me having this same issue and finding this thread... our solution was to modify the URL for Inertia requests in a [before](https://www.inertiajs.com/events#before) handler. Either by adjusting the pathname:

```JS
router.on("before", (event) => {
  event.detail.visit.url.pathname += ".json";
});
```

or adding a query param:

```JS
router.on("before", (event) => {
  event.detail.visit.url.searchParams.set("inertia", "true");
});
```
