### ISSUE TITLE
Return type of useForm is not exported

### ISSUE THREAD

**Issue by AppleNectar** [inertiajs/inertia#1486] opened 2023-03-10 18:39 UTC
### Version:

- `@inertiajs/react` version: 1.0.2

### Describe the problem:

The return type of the `useForm` function, `InertiaFormProps`, is not exported from `@inertiajs/react`.
(Prior to `1.0.0` , they were exported from `@inertiajs/inertia-react`)

Now `InertiaFormProps` are exported from `@inertiajs/react/types/useForm`, but not re-exported from `index.d.ts` in `@inertiajs/react`, which causes this problem.

#### v0.x

The following works

```ts
import { useForm, InertiaFormProps } from "@inertiajs/inertia-react";
```

#### v1.x

The following will not work

```ts
import { useForm, InertiaFormProps } from "@inertiajs/react";
```

The following error is reported

```
TS2305: Module '"@inertiajs/react"' has no exported member 'InertiaFormProps'.
```

There was a similar problem with `@inertiajs/vue3`, but that seems to have been resolved in [#1402](https://github.com/inertiajs/inertia/issues/1402)

**Comment by reinink** [comment] 2023-07-28 01:46
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:46 UTC
Labels: react
