### ISSUE TITLE
Cannot change state of array of objects in form object via a function in Composition API

### ISSUE THREAD

**Issue by fbloggs** [inertiajs/inertia#1021] opened 2021-04-10 15:56 UTC
Cannot mutate an array of objects in Inertia form object using array.filter. 
According to Vue docs this should work. See https://v3.vuejs.org/guide/list.html#mutation-methods

Error: 
app.js:22 Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': [object Object] could not be cloned.

Works with array.splice.  Sample code here: 
setup() {
const form = useForm({

              
                registrants : [],
} 

//registrants array elements are added here  (WORKS): 
function addRegistrant() {

          form.registrants.push({
            id : registrantId.value,
            first_name : '',
            last_name : '',
            gender : '',
            birthyear : 0,
            email : '',
            phone : '',
            childclasses: false,
            softDelete : false,

          })

        registrantId.value ++
      }

// Removed here - called by button click on form. Passes id - inside a v-for loop that iterates over the registrants array
 function removeRegistrant(id) {
         //  form.registrants.splice(-1);   WORKS - removes last element. 
           form.registrants = form.registrants.filter(item => item.id == id)  FAILS. 
      }

I think this has something to do with the proxy object. I have seen earlier bugs reported on this, but those have been fixed. Maybe I'm missing something.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 3
