### ISSUE TITLE
React has detected a change in the order of Hooks called by Inertia. 

### ISSUE THREAD

**Issue by ubheamar** [inertiajs/inertia#465] opened 2021-01-26 16:00 UTC
### Versions:

"@inertiajs/inertia": "^0.6.3",
"@inertiajs/inertia-react": "^0.4.5",

### Describe the problem:

I am using AppLayout as persistance layout & trying to use useState Hook i am getting below error message
![image](https://user-images.githubusercontent.com/10156281/105867854-8cf23880-601b-11eb-92d0-284b6cb86d5e.png)

### Steps to reproduce:

App Layout.tsx
````Typescript
import React, { FC, useState } from "react";

import AppContent from "@/common/components/content/AppContent";

import Spacer from "@/common/components/spacer/Spacer";
import NavUserDropdown from "@/manage/components/nav-user-dropdown/NavUserDropdown";
import App from "@/manage/components/app/App";
import ComponentContainer from "@/manage/components/container/ComponentContainer";
import { Navbar, Sidebar } from "react-ui";

export interface AppLayoutProps {}

const AppLayout: FC<AppLayoutProps> = (children) => {
    /*Below line giving issue */
   [sidebarOpen, setSidebarOpen] = useState(false); 

    return (
        <ComponentContainer>
            <App>
                <Sidebar show={true}>
                    <Sidebar.Brand logo="/app/logo.png" name="Laravel" />
                    <Sidebar.Items>
                        <Sidebar.Section>User Management</Sidebar.Section>
                        <Sidebar.Item>
                            <Sidebar.Link href={route("dashboard")}>
                                <Sidebar.ItemIcon icon="users" />
                                Dashboard
                            </Sidebar.Link>
                        </Sidebar.Item>
                        <Sidebar.Item>
                            <Sidebar.Link href={route("users")}>
                                <Sidebar.ItemIcon icon="users" />
                                Users
                            </Sidebar.Link>
                        </Sidebar.Item>
                    </Sidebar.Items>
                </Sidebar>
                <AppContent>
                    <Navbar>
                        {/* <SidebarTrigger />*/}
                        <Spacer />
                        <NavUserDropdown />
                    </Navbar>
                    {children}
                </AppContent>
            </App>
        </ComponentContainer>
    );
};

export default AppLayout;

````

Codesandbox Link :
https://codesandbox.io/s/unruffled-greider-hruyj?file=/src/Pages/Layout.js

**Comment by mbryne** [comment] 2021-02-11 07:20
I'm not 100% sure why but it seems that using hooks directly in your Layout will throw the error you are seeing,

Someone else me able to chime in on the 'why' but I have found that adding my hooks into either nested components or using context providers where required for any 'theme' like state to help,

A working example can be found here:

https://codesandbox.io/s/funny-burnell-w1m2l

**Comment by ricky-barnett** [comment] 2021-05-08 20:07
I'm not sure if this is a valid fix or not, I'm just picking up React so very much a novice however I was able to resolve this issue by updating my resolveComponent method as follows:

`
resolveComponent={(name) => {
    return import(`@pages/${name}`).then(({ default: page }) => {
        if (page.layout === undefined) {
            page.layout = <Layout children={page} />;
        }
        return page;
    });
}}
`

**Comment by fmaximus** [comment] 2022-03-12 23:37
@ricky-barnett I think that's a good solution

If you set layout to the just `Layout`, it will be called as just a function instead of creating a new React Element,
so useState calls inside the Layout are in fact scoped within the Inertia App.

Not sure if there's a way to validate that the layout function creates a new Element though.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: react
