### ISSUE TITLE
`interface` typed variable not working with `router.post()` or other method

### ISSUE THREAD

**Issue by xsjcTony** [inertiajs/inertia#1457] opened 2023-02-18 17:17 UTC
### Versions:

- `@inertiajs/core` version: 1.0.1
- `@inertiajs/react` version: 1.0.1

### Describe the problem:

variable typed by `interface` raises error when send with `router` method:

This is a little bit annoying because my rule is use `interface` as much as possible, but the API is stopping me from doing so. I don't see there's any difference between `interface` and `type` in this case.

Just to mention, `interface` is not working for generic type of `useForm()` either, a bit annoying too. #1431 

### Steps to reproduce:

```ts
type TestType = { name: string }
interface TestInterface { name: string }

const typeData: TestType = { name: 'test' }
const interfaceData: TestInterface = { name: 'test' }

router.post('/test', typeData)
router.post('/test', interfaceData)
//                   ^^^^^^^^^^^^^
// TS2345: Argument of type 'TestInterface' is not assignable to parameter of type 'RequestPayload | undefined'.
//  Type 'TestInterface' is not assignable to type 'Record<string, FormDataConvertible>'. 
//   Index signature for type 'string' is missing in type 'TestInterface'.
```

**Comment by xsjcTony** [comment] 2023-05-12 08:13
Any update?

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
