### ISSUE TITLE
Remember function not working in another component (restore)

### ISSUE THREAD

**Issue by Baspa** [inertiajs/inertia#626] opened 2021-04-13 14:23 UTC
### Versions:

- `@inertiajs/inertia` version: 0.1.9
- `@inertiajs/inertia-vue` version: 0.1.4

### Describe the problem:
In component 1 I want to remember the boolean `coach_discount` for further use in component 2. I use Vue 2 so the remember function to remember that variabel looks like the following:

```
<script>
import { Inertia } from '@inertiajs/inertia'
export default {
    title: 'Sign up',
    components: {
        LoadingButton,
        TextInput,
        Layout,
    },
    props: {
        coach_discount: {
            type: Boolean,
            default: false
        },
        errors: Object,
    },
    remember: {
        data: ['coach_discount'],
        key: 'test'
    },
    data() {
        return {
            sending: false,
            form: {
               
            },
        };
    },
    methods: {
        submit() {
            this.sending = true;
            this.$inertia
                .post('/signup', {
                    locale: this.$i18n.locale,
                    name: this.form.name,
                    firstname: this.form.firstname,
                    lastname: this.form.lastname,
                    email: this.form.email,
                    password: this.form.password,
                    password_confirmation: this.form.password_confirmation,
                    coach_discount: this.coach_discount,
                })
                .then(() => (this.sending = false));
        },
    },
};
</script>

```

In component 2 I want to check if the variable is true or false. In it's mounted function I check for the key 'test':

```
    mounted() {
        let data  = Inertia.restore('test');
        console.log(data);
    },
```
The `console.log()` returns `undefined`. However, when I `console.log()` this in the exact same component the output is as the following: 
```
{
    "coach_discount": true
}
```
### Steps to reproduce:

Create two components with the code as described in the previous paragraph. 

In any additional information is needed I will provide it ofcourse.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 2
