### ISSUE TITLE
Unable to setData if the data has a json attribute

### ISSUE THREAD

**Issue by mahamudml** [inertiajs/inertia#648] opened 2021-04-24 01:02 UTC
### Versions:

- `@inertiajs/inertia` version: ^0.8.6
- `@inertiajs/inertia-react` version: ^0.5.11

### Describe the problem:

Unable to setData if the data has a json attribute.

### Steps to reproduce:

```
const { data, setData, errors, put, processing } = useForm({
  enabled: prefs.enabled || '',
  options: prefs.options || '',
});
```

Suppose options is a json coming from Laravel, now I can access data.options.textColor, but when I try to set I'm unable using setData like:
`onChange={val => setData('options.textColor', val)}`

**Comment by PonchRobles** [comment] 2022-12-22 02:00
Is there any update on this issue? I'm going through something similar and can't find much information about it.

I have data that I want to save in json format, something like...

```
const { data, setData, post, processing, errors, reset } = useForm({
        contact_one: {
            name: "",
            email: "",
            phone_number: "",
            extension: "",
            position: "",
        }
});


useEffect(() => {
        return () => {
            reset( "contact_one");
        };
    }, []);


const onHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setData("contact_one");
    };
```
The information that I have in data is passed as props to a child component where the entries are according to the json, but filling these entries does not make the change in the value of what exists in data.

```
 <InputBase
    label="Contact name"
    value={data.contact_one.name}
    name="contact_one_name"
    id="contact_one_name"
    placeholder="contact_one_name"
    handleChange={onHandleChange}
    />
```
Am I doing something wrong or is there a better way to do this?

_I should mention that I'm moving from vue.js to react.js, sorry if something doesn't look right and also because of my English I'm learning._

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: react
