### ISSUE TITLE
[React] Persistent layouts title tag as prop not working

### ISSUE THREAD

**Issue by jrson83** [inertiajs/inertia#1029] opened 2021-12-29 10:55 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-react` version: 0.7.1

### Describe the problem:

When using the first example from the [Persistent layouts docs](https://inertiajs.com/pages#persistent-layouts) to specify a page title as prop passed to the `Layout`:

```js
Home.layout = page => <Layout children={page} title="Welcome" />
```

So without using any of the existing `<Head />` components, no `<Title />` tag is inserted in the page.
This issue occurs with or without specifying ```title: title => `${title} - My App`,``` callback in the `createInertiaApp()` function.
I have tested this with and without SSR enabled.

_One thing to add:_
I noticed I did not pick up the title in my Layout function. But after changing to the following:
```js
export default function Layout({ children, title }) {
  console.log(title)
}
```

The `console.log()` prints out the passed title, but still no `<Title />` tag is inserted.
I can understand maybe if  it is still needed to have the `<Head title="Welcome" />` tag inside the Layout but like:
`<Head title={title} />` ? If this is the case it should be mentioned in the docs.

### Steps to reproduce:

1. Follow the [server side setup](https://inertiajs.com/server-side-setup)
2. Follow the [client side setup](https://inertiajs.com/client-side-setup)
3. Follow the [creating pages setup](https://inertiajs.com/pages#creating-pages) and remove `<Head title="Welcome" />`
4. Follow the [creating layouts setup](https://inertiajs.com/pages#creating-layouts)
5. Follow the [persistent layouts setup](https://inertiajs.com/pages#persistent-layouts)
6. Optional follow the [title callback setup](https://inertiajs.com/title-and-meta#title-callback) example 1

**Comment by claudiodekker** [comment] 2022-01-18 17:51
Duplicate of #938

**Closed by claudiodekker** 2022-01-18 17:51 UTC
Labels: react
