### ISSUE TITLE
ReferenceError: document is not defined inertia ssr 

### ISSUE THREAD

**Issue by samehdoush** [inertiajs/inertia#1089] opened 2022-02-07 13:53 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue` version: 0.8.0

### Describe the problem:
laravel 8

inertia js : 0.5.4

package.json
```
       "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue": "^0.8.0",
   "laravel-mix": "^6.0",
   "sass": "~1.32",
        "sass-loader": "^12.2.0",
        "vue-cli-plugin-vuetify": "~2.3.1",
        "vue-loader": "^15.9.6",
        "vue-template-compiler": "^2.6.10",
        "vuetify-loader": "^1.7.0",
        "webpack": "^5.59.1",
 "vue": "^2.6.14",
     "vue-server-renderer": "^2.6.14",
   "vuetify": "^2.5.5",
        "vuetifyjs-mix-extension": "0.0.20",
        "vuex": "^3.4.0",
        "webpack-node-externals": "^3.0.0"

```

webpack.ssr.mix.js
```
const path = require('path')
const mix = require('laravel-mix')
const webpackNodeExternals = require('webpack-node-externals');


mix
    .options({ manifest: false })
    .js('resources/js/ssr.js', 'public/js')
 
    .vue({
        version: 2, options: { optimizeSSR: true }
    })
    .webpackConfig({
        resolve: {
            alias: {

                '@resources': path.resolve('resources'),
                '{Template}': path.resolve('resources/js/Themes/default'),
                '@themeConfig': path.resolve('themeConfig.js'),
                '@core': path.resolve('resources/@core'),
                '@axios': path.resolve('resources/js/plugins/axios.js'),
                '@user-variables': path.resolve('resources/sass/variables.scss'),
                '@sass': path.resolve('resources/sass/'),
                'apexcharts': path.resolve(__dirname, 'node_modules/apexcharts-clevision'),
                '@': path.resolve('resources/js'),
                // @resources/assets/images
            },
        },
   
        target: 'node',
        devtool: 'source-map',
        externals: [webpackNodeExternals({
            // this WILL include `jquery` and `webpack/hot/dev-server` in the bundle, as well as `lodash/*`
            allowlist: [/^vuetify/,  /^lodash/,'vue-tel-input-vuetify/lib',/^vue-tel-input-vuetify^/,/^apexcharts^/,/^vue-apexcharts/,/apexcharts/,/apexcharts-clevision/,/^apexcharts-clevision/,/^apexcharts-clevision^/,/^vue-country-flag/,/\.css$/]
        })],
    })

```
ssr.js
```
import Vue from 'vue'
import { createRenderer } from 'vue-server-renderer'
import { createInertiaApp } from '@inertiajs/inertia-vue'
import createServer from '@inertiajs/server'
import PortalVue from 'portal-vue';
import store from './store'
import './plugins/acl'
import VueCompositionAPI from '@vue/composition-api'
import VueMeta from 'vue-meta'
const moment = require('moment');
import vuetify from '@/plugins/vuetify'
import Layout from '@/Layouts/AdminLayout.vue'
import AppLayout from "@/Layouts/AppLayout.vue"
import UserLayout from "@/Layouts/UserLayout.vue"
import ClientOnly from 'vue-client-only'




createServer((page) => createInertiaApp({
    page,
    render: createRenderer().renderToString,
    // resolve: name => require(`./Pages/${name}`),
    resolve:  (name) => {
        // const page = (await import(`./Pages/${name}`)).default
        const page = require(`./Pages/${name}`);
        if (page.layout === undefined && name.startsWith('Admin/')) {
            page.layout = Layout
        }
        if (page.layout === undefined && name.startsWith('Dashboard/')) {
            page.layout = Layout

        }
        if (page.layout === undefined && name.startsWith('UserDashboard/')) {
            page.layout = UserLayout
        }
        if (page.layout === undefined && !name.startsWith('Admin/') && !name.startsWith('Dashboard/')) {
            page.layout = AppLayout

        }


        return page
    },
    setup({ app, props, plugin }) {
        Vue.use(plugin);
        Vue.use(VueCompositionAPI);
        Vue.use(PortalVue);
        Vue.component('client-only', ClientOnly)
     
     
        Vue.use(VueMeta, {
            // optional pluginOptions
            refreshOnceOnNavigation: true
        })
 

        Vue.mixin({ methods: { route } });

    

        return new Vue({
            vuetify: vuetify,
            store,
            render: h => h(app, props)
            ,
        })
    },
     }))
```
```
npx mix --mix-config=webpack.ssr.mix.js
result : webpack compiled successfully 
```
```
node public/js/ssr.js
error : 
var style = document.createElement('style');
              ^

ReferenceError: document is not defined
    at insertStyleElement (C:\laragon\www\test2\public\js\ssr.js:43608:15)
    at addStyle (C:\laragon\www\test2\public\js\ssr.js:43723:13)
    at modulesToDom (C:\laragon\www\test2\public\js\ssr.js:43596:18)
    at module.exports (C:\laragon\www\test2\public\js\ssr.js:43754:25)
    at Object../resources/sass/overrides.scss (C:\laragon\www\test2\public\js\ssr.js:41341:145)
    at __webpack_require__ (C:\laragon\www\test2\public\js\ssr.js:118547:41)
    at Object../resources/js/plugins/vuetify/default-preset/preset/index.js (C:\laragon\www\test2\public\js\ssr.js:38106:1)  
    at __webpack_require__ (C:\laragon\www\test2\public\js\ssr.js:118547:41)
    at Object../resources/js/plugins/vuetify/index.js (C:\laragon\www\test2\public\js\ssr.js:38132:80)
    at __webpack_require__ (C:\laragon\www\test2\public\js\ssr.js:118547:41)
```
public/js/ssr.js
![image](https://user-images.githubusercontent.com/48515888/152800803-870bcdb4-08b6-41ad-a4d8-abfa375fe578.png)

Any help in solving this problem?

**Comment by ajnsn** [comment] 2022-02-08 06:52
Hey @samehdoush 
This seems to be an issue with Vuetify, there are many references in the error stack. `document` is not available when using SSR. I assume this is nothing related to Inertia. What you can try is to temporarly remove Vuetify from your build process and try to narrow down the problem this way.

**Comment by samehdoush** [comment] 2022-02-08 07:58
thank you ,
Already the problem is in vuetify
When I removed it, it worked fine

**Comment by JBSommeling** [comment] 2022-03-08 19:48
Having a similar problem here. I think it's a webpack configuration problem maybe? 

Using Laravel 9 with:
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        
I believe we experience this error when the application building process is done on the server-side where no 'document' exists. Anyone having an idea how to solve this? The internet says something about using an npm package called JsDom. Not sure if that will do the trick though...

**Comment by Aksoom-Hussain** [comment] 2022-03-10 07:53
> Having a similar problem here. I think it's a webpack configuration problem maybe?
> 
> Using Laravel 9 with: "@inertiajs/inertia": "^0.11.0", "@inertiajs/inertia-vue3": "^0.6.0",
> 
> I believe we experience this error when the application building process is done on the server-side where no 'document' exists. Anyone having an idea how to solve this? The internet says something about using an npm package called JsDom. Not sure if that will do the trick though...

https://github.com/inertiajs/inertia/issues/1077#issuecomment-1027907798

check this, I solve by removing style in Vue files moved it to app.css file

**Comment by JBSommeling** [comment] 2022-03-10 08:25
> > Having a similar problem here. I think it's a webpack configuration problem maybe?
> > Using Laravel 9 with: "@inertiajs/inertia": "^0.11.0", "@inertiajs/inertia-vue3": "^0.6.0",
> > I believe we experience this error when the application building process is done on the server-side where no 'document' exists. Anyone having an idea how to solve this? The internet says something about using an npm package called JsDom. Not sure if that will do the trick though...
> 
> [#1077 (comment)](https://github.com/inertiajs/inertia/issues/1077#issuecomment-1027907798)
> 
> check this, I solve by removing style in Vue files moved it to app.css file

That certainly solved the issue. The Welcome.vue in Jetstream installation was the culprit. It had CSS in the Vue files all over.
The next issue is one where property 'route' was accessed during render but not defined on instance. I think it has something to to with the usage of the 'route' method within the Links component. Example from AppLayout.vue:

`<Link :href="route('dashboard')">
                                    <jet-application-mark
                                        class="block h-9 w-auto"
                                    />
                                </Link>
`

**Comment by Aksoom-Hussain** [comment] 2022-03-10 15:47
https://github.com/tighten/ziggy/issues/431#issue-909632580

check this, hope it help

> > > Having a similar problem here. I think it's a webpack configuration problem maybe?
> > > Using Laravel 9 with: "@inertiajs/inertia": "^0.11.0", "@inertiajs/inertia-vue3": "^0.6.0",
> > > I believe we experience this error when the application building process is done on the server-side where no 'document' exists. Anyone having an idea how to solve this? The internet says something about using an npm package called JsDom. Not sure if that will do the trick though...
> > 
> > 
> > [#1077 (comment)](https://github.com/inertiajs/inertia/issues/1077#issuecomment-1027907798)
> > check this, I solve by removing style in Vue files moved it to app.css file
> 
> That certainly solved the issue. The Welcome.vue in Jetstream installation was the culprit. It had CSS in the Vue files all over. The next issue is one where property 'route' was accessed during render but not defined on instance. I think it has something to to with the usage of the 'route' method within the Links component. Example from AppLayout.vue:
> 
> `<Link :href="route('dashboard')"> <jet-application-mark class="block h-9 w-auto" /> </Link> `
> 
> Error:
> 
> > [Vue warn]: Property "route" was accessed during render but is not defined on instance.
> 
> Edit: The problem is lies I think with the ssr.js created during the tutorial. It does not say to use the `.mixin({methods:{route}})` . Once applied within the ssr.js you only get the error
> 
> > ReferenceError: route is not defined
> 
> Haha, I'm out of options here. From where do I import the unresolved variable 'route' to the mixin? This is a fresh Laravel Jetstream installation

https://github.com/tighten/ziggy/issues/431#issue-909632580

check this link hope it help
I have hosted SSR mode in server work with charm in cloud server

**Comment by reinink** [comment] 2023-07-28 01:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:54 UTC
