### ISSUE TITLE
Memory leak in `useForm` for Svelte.

### ISSUE THREAD

**Issue by mt-u** [inertiajs/inertia#1506] opened 2023-03-30 05:00 UTC
`subscribe` method of Svelte's store is called in the `useForm`, but `unsubscribe` doesn't seem to be called.
I copied the `useForm` code and modified it to pass a callback that watches for the start and end of the subscribing to the `writable` function (arguments described in the [Svelte docs](https://svelte.jp/docs#run-time-svelte-store-writable)) and checked the behavior.
Then I confirmed that the subscribing did not end even if I moved the page.
So, I think `unsubscribe` needs to be called using `onDestory` as done in `remember.js`.

`subscribe()` is called in `useForm.js` but `unsubscribe()` is not.
https://github.com/inertiajs/inertia/blob/fe35815bfc83acde823027130b31350019671a94/packages/svelte/src/useForm.js#L190-L205

On the other hand, `remember.js` calls both of them.
https://github.com/inertiajs/inertia/blob/fe35815bfc83acde823027130b31350019671a94/packages/svelte/src/remember.js#L8-L12

_Originally posted by @mt-u in https://github.com/inertiajs/inertia/discussions/1474_

**Comment by reinink** [comment] 2023-07-28 01:39
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:39 UTC
