### ISSUE TITLE
undefined is not a valid URL when attaching file to $inertia.form()

### ISSUE THREAD

**Issue by benjivm** [inertiajs/inertia#782] opened 2021-07-02 17:18 UTC
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue` version: 0.6.2

### Describe the problem:

Attaching files to `$inertia.form` prevents submission with error. Submitting without file attached works. Alternatively setting `forceFormData: true` _also_ breaks submission whether there is a file attached or not.

Form html:
```html
<form @submit.prevent="onSubmit">
    <input
        v-model="form.name"
        type="text"
    >
    <input
        type="file"
        @input="form.file = $event.target.files[0]"
    >
    <button>
        Submit
    </button>
</form>
```

Form model:
```js
form: this.$inertia.form({
    name: '',
    file: ''
})
```

Submit method:
```js
onSubmit() {
    this.form.post(route('documents.store'));
}
```

Error:
```js
[Vue warn]: Error in v-on handler: "TypeError: URL constructor: undefined is not a valid URL."
found in
---> <Create> at resources/js/Pages/Documents/Create.vue
       <Inertia>
         <Root>
```

### Steps to reproduce:

Submit a form without a file attachment: success. Attach a file to the same form and you should see the error outlined above. Or set `forceFormData: true`.

### Update

This appears to be an issue with the Ziggy route helper. Removing it and replacing it with a string seems to work:

```js
this.form.post('/documents');
```

What might be causing this?

**Comment by ajnsn** [comment] 2021-07-09 09:23
@benjivm I cannot reproduce this. Which version of Ziggy are you using? 
< v1 versions of Ziggy often needed the `url()` helper to get an url string, see [here](https://github.com/tighten/ziggy/tree/0.9.x#url), e.g. `route('documents.store').url()`.
This has been changed in >= v1. 

You can also console out that `route('documents.store')` to see what is really coming through to Inertia.
If you are using a Mixin or prototype the `route()` somewhere, it would be interesting to see your implementation. 

Hope this helps.

**Comment by reinink** [comment] 2021-07-13 20:08
Closing this, as it appears to be a Ziggy issue. 👍

**Closed by reinink** 2021-07-13 20:08 UTC
