### ISSUE TITLE
Nestedlayout and transition

### ISSUE THREAD

**Issue by yagogak** [inertiajs/inertia#750] opened 2021-06-14 11:15 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

Wrapping slot with a transition make nested layout failed.

### Steps to reproduce:

- have a Layout and a nestedlayout 
- wrap the slot with a transition
- navigate between links that display pages with layout and nested layout
- leaving a page with the simple layout to the nested layout failed silently

**Comment by ajnsn** [comment] 2021-06-29 07:14
Hey @yagogak 
Can you try to give your slot a `key`, to help Vue detect the slot content change?

Example:
```js
<slot :key="$page.url" />
```

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: vue 3
