### ISSUE TITLE
json:api compliant request cannot be processed by useForm helper

### ISSUE THREAD

**Issue by michaelklopf** [inertiajs/inertia#630] opened 2021-04-16 16:01 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-vue3` version: 0.3.13

### Describe the problem:

We structure our request payloads in [json:api](https://jsonapi.org/format/) compatible format. An example would be this

```js
const form = useForm({
    data: {
        id: "1",
        type: "contacts",
        attributes: {
            email: "john@example.com",
        },
    },
});
```

This does not work and the request payload is an empty array`[]`.

We could trace the problem to the `data()` function in `useForm.js` https://github.com/inertiajs/inertia/blob/master/packages/inertia-vue3/src/useForm.js#L22-L29

Describing it is hard, so here a debug trace with the following useForm payload
```js
const form = useForm({
    data1: {
        id: "1",
        type: "contacts",
        attributes: {
            email: "john@example.com",
        },
    },
});
```

As you can see `data()` and the `data1` object are both there and the form request is constructed correctly.
<img width="1838" alt="Bildschirmfoto 2021-04-16 um 17 49 44" src="https://user-images.githubusercontent.com/2892138/115050555-270ba380-9edc-11eb-9417-bb23bb85c8dc.png">

The reduce function somehow merges the data object with the context of `this`. The`data()` function overwrites the object when its key is `data`.

We would like to make the useForm function json:api compatible and we managed to achieve this by renaming the `data()` function to something else, like `getData()`. This didn't result in any errors. Do you see any problems with a change like this?

### Steps to reproduce:
See the above examples. Try to send a payload with the top level key being `data`.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 3
