### ISSUE TITLE
SSR: Default layouts not working

### ISSUE THREAD

**Issue by lucaros97** [inertiajs/inertia#1045] opened 2022-01-11 16:22 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-react` version: 0.8.0

### Describe the problem:

I'm using inertia-react and I just configured SSR. I'm using default layouts but I found that when enabled, it's not working.

### Steps to reproduce:

```js
createServer((page) => createInertiaApp({
  page,
  render: ReactDOMServer.renderToString,
  resolve: name => {
    const page = require(`./Pages/${name}`).default
    page.layout = page.layout || Layout
    return page
  },
  setup: ({ App, props }) => <App {...props} />,
}))
```

If found that if I remove the row `page.layout = page.layout || Layout` everything works.

This is what I see in console:
`ReferenceError: route is not defined at j (/myproject/public/js/ssr.js:1:48655)`

I'm using Ziggy, but the above error seems not coming from it.

**Comment by ajnsn** [comment] 2022-01-11 16:59
Hey @lucaros97 
I am using default layouts with SSR and it is working. The `route` thing is maybe inside your `Layout` component or it's sub components, e.g. navigation?

**Comment by lucaros97** [comment] 2022-01-11 17:14
This is what I'm trying to do but I'm using React not Vue.

**Comment by ajnsn** [comment] 2022-01-11 20:47
Hey @lucaros97 - I know but you get the idea and good hints how to solve this. If anything in the node processing fails, you will not get the SSR output.

**Comment by parth391** [comment] 2022-02-03 18:03
@lucaros97 did you manage to fix this issue?

**Comment by reinink** [comment] 2023-07-28 01:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:54 UTC
Labels: react
