### ISSUE TITLE
useForm can't read properties of itself anymore

### ISSUE THREAD

**Issue by Cynically** [inertiajs/inertia#959] opened 2021-11-02 15:48 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-vue3` version: 0.5.1

### Describe the problem:
`useForm()` cannot reference properties within the form itself. It'll throw the following error: 
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'quantity')`

This used to work prior to updating to the latest version from inertia@0.8.7 and inertia-vue3@0.3.14.

### Steps to reproduce:

Stopped working after updating to inertia@0.10.0 and inertia-vue@0.5.1
```
const form = useForm({
    price: 500,
    quantity: 1,
    totalItemPrice: computed(() => form.quantity * form.price),
})

const submit = () => {
    form.post(route('cart'))
}
```

Workaround:
```
const form = reactive({
    price: 500,
    quantity: 1,
    totalItemPrice: computed(() => form.quantity * form.price),
})

const submit = () => {
    Inertia.post(route('cart'), form)
}
```

**Comment by inlogicstudio** [comment] 2021-12-03 14:14
I have been on the same version for a while  and i never experience this

**Comment by connorClements** [comment] 2022-03-31 09:30
did anyone find a fix to this? I am coming up with the same error, it seems like it doesn't like useForm when going live but is fine in local

**Comment by reinink** [comment] 2023-07-28 01:56
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:56 UTC
Labels: investigate, vue 3
