### ISSUE TITLE
Inertia-React v18 Laravel compatibility problem

### ISSUE THREAD

**Issue by dvelez3815** [inertiajs/inertia#1168] opened 2022-05-03 16:11 UTC
### Discussed in https://github.com/inertiajs/inertia/discussions/1167

<div type='discussions-op-text'>

<sup>Originally posted by **xaviermaster** May  3, 2022</sup>
Hi, I am currently working with inertiajs/inertia-laravel": "^0.5.4" and using the new versions of react and react-dom:18 the problem I am facing is by following the documentation 

![Documentation](https://user-images.githubusercontent.com/40648189/166490603-032e3ee0-c46a-4157-bf20-9431ec37aef0.png)

I get the next warning. So render it not working properly

![problem_](https://user-images.githubusercontent.com/40648189/166491146-31d65024-8e16-4c0b-8ca3-16014eafd206.png)

![peer_dependency](https://user-images.githubusercontent.com/40648189/166595746-a1cd874d-b335-4628-b525-c77fa553e722.png)

I was trying to use react-dom/client instead of react-dom but again more problem. Has anyone faced this problem recently and solved it? It it's possible to upgrade the web documentation based on new react version? Thanks in advanced
</div>

**Comment by SuperDJ** [comment] 2022-05-04 13:07
Possible similar issue https://github.com/inertiajs/inertia/issues/1152

**Comment by lcdss** [comment] 2022-05-16 15:30
> Possible similar issue #1152

Its not related. React 18 implements a new way to attach the root component to the dom.

@xaviermaster 
You need to use the new React 18 api. Try this:

```js
import { createRoot } from "react-dom/client";
import { createInertiaApp } from "@inertiajs/inertia-react";

createInertiaApp({
  resolve: (name) => require(`./Pages/${name}`),
  setup({ el, App, props }) {
    const root = createRoot(el);

    root.render(<App {...props} />);
  },
});
```

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
