### ISSUE TITLE
Error raised while tapping on a 'Link' button in Chrome browser on iOS

### ISSUE THREAD

**Issue by haoxi911** [inertiajs/inertia#1549] opened 2023-05-12 15:20 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.2

### Describe the problem:

I have a `Link` button in the footer section of my app, it is rendered as an `<a>` tag with a `href` property, nothing special as far as I know. It works fine on desktop browsers (Safari, Chrome), as well as Safari on iOS, and Chrome on Android too.

It only doesn't work in Chrome on iOS, when I tapped a few different buttons in my app, suddenly all of the `Link` buttons stopped working. I turned on logging in the `chrome://inspect` tab on iOS, and it logged `ERROR [object Object]` every time I tapped on the `Link` button.

### Steps to reproduce:

Here are some screencasts of this issue:

- (Chrome, not working): https://youtube.com/shorts/vw_zmWNJEUU?feature=share
- (Safari, works well): https://youtube.com/shorts/6akwlvbynZo?feature=share

Noticing the 'Shipment List' button and the 'We Love Fulfillment' logo, both of them are `Link` buttons. Currently, I don't have a public repository to reproduce this issue. However, I would like to ask if there is a way to print more useful error in the logs so that I can probably fix it by myself.

Because Chrome on iOS is using WKWebView, which makes it difficult to connect and debug with a laptop.

**Comment by reinink** [comment] 2023-07-28 01:27
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:27 UTC
