### ISSUE TITLE
DOMException: Failed to execute 'replaceState' on 'History': #<Object> could not be cloned

### ISSUE THREAD

**Issue by iamohd-zz** [inertiajs/inertia#775] opened 2021-06-30 10:41 UTC
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.7

### Describe the problem:

I am using [Vue 3 Draggable](https://github.com/SortableJS/vue.draggable.next) package. In the event of dragging an element, I execute Inertia.put method and pass some data to Laravel. This is where this exception occurs.

### Steps to reproduce:

For example, in Laravel pass a project with a list of columns to your view. Then use the Draggable component as following:

```vue
<Draggable
    v-model="project.columns"
    group="columns"
    item-key="id"
    @end="onColumnPositionChanged"
>
    <template #item="{element: column}">
        <KanbanColumn
             :column="column"
             :key="column.id"
         />
    </template>
</Draggable>
```

In event of onColumnPositionChanged, trigger Inertia.put method

```js
const onCardPositionChanged = () => {
    Inertia.put('/some-route');
};
```

**Comment by reinink** [comment] 2021-06-30 10:52
I suspect this has something to do with the URL you're submitting to, which I assume isn't `/some-route`. What's the *exact* URL that's being used when submitting the request?

**Comment by iamohd** [comment] 2021-06-30 11:05
> I suspect this has something to do with the URL you're submitting to, which I assume isn't `/some-route`. What's the *exact* URL that's being used when submitting the request?

Thanks for the quick reply

The URL is:
 http://127.0.0.1:8000/back/projects/dummy-slug/columns/sort

**Comment by iamohd** [comment] 2021-07-01 07:15
I think the issue is because of trying to push a complex object into the page state. Once I replaced the page state with simple data, it worked without any issue. 

This StackOverflow's question is related to this issue
https://stackoverflow.com/questions/50618225/uncaught-domexception-failed-to-execute-pushstate-on-history-function

**Comment by reinink** [comment] 2021-07-01 11:31
> I think the issue is because of trying to push a complex object into the page state. Once I replaced the page state with simple data, it worked without any issue.

So, how are you getting complex data into your page props? We actually intentionally removed the `transformProps` option because of this very issue. The data that is saved to history state should just be the props (JSON) that come back from the server.

**Comment by reinink** [comment] 2021-07-01 14:27
Also, can you please provide an example of what specifically you're doing to cause this? I don't see how the draggable package/component should have any bearing on what ends up in history state.

**Comment by iamohd** [comment] 2021-07-01 14:38
At first, I thought it's because of Vue Draggable, but it has nothing to do with this problem.

Actually, when the data that comes from the server contains nested arrays and you change this data in your view, then this issue occurs. 

For example, suppose you are passing this to your view

```php
return Inertia::render('back/projects/tasks/index', [
    'project' => [
        'id'  => $project->id,
        'name' => $project->name,
        'columns' => $project->columns()
              ->orderBy('index')
              ->get()
               ->transform(function (Column $column) {
                   return [
                       'id'    => $column->id,
                       'name'  => $column->name,
                       'index' => $column->index,
                    ];
               })
         ]
    ]);
```

Now in your view, if you change the sort of columns and try to call Inertia.put, you will get the exception.

If it's still not producible, I don't mind giving you access to the repo to check how to produce the issue.

**Comment by reinink** [comment] 2021-07-01 14:48
Gotcha. So, there is no reason why you shouldn't be able to have a very complex/nested object structure like this. I do this all the time.

Can you identify specially what part of the data is causing the exception? You might have to systematically remove data until the problem goes away to figure this out. I've never run into an issue where server generated data caused an issue like this.

**Comment by iamohd** [comment] 2021-07-01 14:55
I tried to do that. It works when you replace 'columns' with an array of simple data types.

For example
```php
'columns' => [1,2,3,4],
```

But if you put a nested array this exception occurs

For example;
```php
'columns' => [
    ['id'=>1], ['id'=>2]
],
```

**Comment by reinink** [comment] 2021-07-01 15:03
Are you sure there is not more to it? I just tried passing the following as props in my own demo app, and it worked without issue.

```php
'columns' => [
    ['id'=>1], ['id'=>2]
],
```

Does this issue only happen when you make a visit via `Inertia.put()`? Or does it happen on the initial page load? If it's only happening on `Inertia.put()`, can you confirm that you're redirecting server-side back to the *same page*? Can you please show me the response that's coming back from that request?

**Comment by iamohd** [comment] 2021-07-01 15:08
If you never change this data then you will not get this exception. 

Once you change it in your view and you call Inertia.put this will happen. Also, even when you try to navigate away after changing this data.

- Yes in my controller I am redirecting back to the same page.
- The request does not reach the server once this exception occurs, there is no response

**Comment by reinink** [comment] 2021-07-01 15:15
Are you use the "remember" feature at all?

**Comment by iamohd** [comment] 2021-07-01 15:16
No I am not using it

**Comment by reinink** [comment] 2021-07-01 15:19
This is a strange issue. From what it sounds like, there is some type of `page` object data structure that's causing this error. I am using the example data above that you're saying is causing this issue, and I am unable to reproduce this. Basically, to fix this, I need to be able to reproduce it.

I don't really want access to your full app. Much better is a very simple Laravel/Inertia/Vue3 app that reproduces this issue with just one or two endpoints, and one or two components. If you can provide that, I'll happily look deeper into this. 👍

**Comment by iamohd** [comment] 2021-07-01 15:20
Great, I will make a repot to reproduce this issue and post the link here

**Comment by iamohd** [comment] 2021-07-01 16:11
Here it is:
https://github.com/iamohd/inertia-exception

To produce the exception, change the order of the columns by dragging them, and click on "Call Inertia.put" or "To another page" button

Also, you can try clicking on either of the buttons without changing the order of the columns, you will notice it will work fine in this case.

**Comment by oueki** [comment] 2021-07-02 14:00
same problem
@inertiajs/inertia version: 0.9.2
@inertiajs/inertia-vue3 version: 0.4.7

i am using Howl plugin
an error occurs when navigating to another page via inertia-link

**Uncaught DOMException: Failed to execute 'replaceState' on 'History': HTMLAudioElement object could not be cloned.**

**Comment by tonychuuy** [comment] 2021-07-08 00:47
I was having the same issue

```
Uncaught (in promise) DOMException: The object could not be cloned. router.ts:397:4
    replaceState router.ts:398
    saveScrollPositions router.ts:73
    resetScrollPositions router.ts:91
    g router.ts:381
    (Async: promise callback)
    g router.ts:379
    (Async: promise callback)
    setPage router.ts:373
    handleInitialPageVisit router.ts:52
    init router.ts:41
    setup app.js:43
    callWithErrorHandling runtime-core.esm-bundler.js:155
    setupStatefulComponent runtime-core.esm-bundler.js:7161
    setupComponent runtime-core.esm-bundler.js:7117
    mountComponent runtime-core.esm-bundler.js:5115
    processComponent runtime-core.esm-bundler.js:5090
    patch runtime-core.esm-bundler.js:4684
    componentEffect runtime-core.esm-bundler.js:5227
    reactiveEffect reactivity.esm-bundler.js:42
    effect reactivity.esm-bundler.js:17
    setupRenderEffect runtime-core.esm-bundler.js:5173
    mountComponent runtime-core.esm-bundler.js:5132
    processComponent runtime-core.esm-bundler.js:5090
    patch runtime-core.esm-bundler.js:4684
    render2 runtime-core.esm-bundler.js:5810
    mount runtime-core.esm-bundler.js:4085
    mount runtime-dom.esm-bundler.js:1322
    <anonymous> app.js:60
    InnerModuleEvaluation self-hosted:2384
    evaluation self-hosted:2335
```

What I noticed is that the exception occurs when I mutate the property, having an array that comes from the backend and then passed it to the vue component as property:

```
 props: {
    accounts: Array,
  },
```

I had a computed property which used the accounts prop, and applied a filter and a map methods which then the map method mutated the original array.

The issue was gone when I cloned the accounts array using JSON.parse and JSON.stringify
```
JSON.parse(JSON.stringify(this.accounts))
```

Also read the MDN for pushState which has a size limit of 640K, but that wasn't my case.
https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API#the_pushstate_method

And supported types, in my case it was a simple array of objects, but can be the issue for @oueki https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types

**Comment by igerslike** [comment] 2021-07-23 16:53
Same error happening here, basically we have deep object ( chart ) that comes from "$page.props.charts.orders"

Payload Demo here : https://api.npoint.io/63d8cf8b37aee1247b5a/orders/key

When passed via Prop to the component like follows: 

`<chart :chart="$page.props.charts.orders" />`

This will reproduce the error from OP,  but if we do like @tonychuuy mentioned and have a prop as follows :

`
 computed:{
        ordersChart(){
            return JSON.parse(JSON.stringify(this.$page.props.charts.orders))
        }
}`

It will work just fine, im not sure what the issue is, but seems like some deep objects are being converted to Proxy and so fails to replace the state on those.

**Comment by jechazelle** [comment] 2021-08-23 07:51
Hi, 

Have you found a solution @iamohd @reinink  ?

I have a same issue when I use vuedraggable in my project.

I have an error when I drag my item : Uncaught DOMException: Failed to execute 'replaceState' on 'History': #<Object> could not be cloned.

My code : https://stackblitz.com/edit/vue-shifting-array-elements-47h7cu

**Comment by iamohd** [comment] 2021-08-23 16:38
> Hi, 
> 
> Have you found a solution @iamohd @reinink  ?
> 
> I have a same issue when I use vuedraggable in my project.
> 
> I have an error when I drag my item : Uncaught DOMException: Failed to execute 'replaceState' on 'History': #<Object> could not be cloned.
> 
> My code : https://stackblitz.com/edit/vue-shifting-array-elements-47h7cu


Hi

As a temporary solution you can clone the prop into a new reactive variable and use it 

Just make sure u truly clone it, not making a shallow copy.

**Comment by ewhicher** [comment] 2021-09-16 19:08
@reinink @iamohd - I am having the same issue, did you find a fix?

@iamohd - can you show how to do the temporary solution in the mean time?

**Comment by iamohd** [comment] 2021-09-17 10:19
> @reinink @iamohd - I am having the same issue, did you find a fix?
> 
> @iamohd - can you show how to do the temporary solution in the mean time?

For example

```js
import { usePage } from '@inertiajs/inertia-vue3';
import { reactive } from 'vue';

const obj = reactive({ ... usePage().props.value.someObject });
```

**Comment by kevnk** [comment] 2021-09-23 15:53
Hey everyone... Could this maybe be related to a local storage max size?

I ran into this issue when I just stored the entire form like this:
```js
// Threw above error when I updated specific fields in my form
remember: ['form'],
```

I solved it by removing the exceptionally large parts of the form (in my case, entire models with related data including image info):
```js
// Works when I remove those specific problematic and large form props
remember: [
    'form.title',
    'form.label',
    // ... other small field types
],

**Comment by kevnk** [comment] 2021-09-23 18:46
Well... I thought it was working...

> > I think the issue is because of trying to push a complex object into the page state. Once I replaced the page state with simple data, it worked without any issue.
> 
> So, how are you getting complex data into your page props? We actually intentionally removed the `transformProps` option because of this very issue. The data that is saved to history state should just be the props (JSON) that come back from the server.

This may be my issue too...  I'm sending different data than I'm receiving...

**Comment by Numenorian** [comment] 2021-10-05 20:11
I ran into the same problem and found another possible workaround:

For whatever reason it appears that if I _mutate_ the array part of the prop with something like `array.splice()` instead of setting that value to a new array with something like `array.filter()`, it doesn't seem to trip the error. 

For example, let's say I have a prop data structure like this:

```
  someProp: {
    someInt: 3,
    someArray: [
      {
        name: "someObject1",
        id: 1,
      },
      {
        name: "someObject2",
        id:2,
      }
    ],
    someString:  "string",
  },
```
..and I want to remove "someObject1" based on it's id.

If I use `someArray.filter()`, like so, I trip the mysterious "Object could not be cloned" error:
```
let idToRemove = 1;
this.someProp.someArray = this.someProp.someArray.filter( arrayItem => {
  return arrayItem.id !== idToRemove;
});
``` 

If, however, I use `someArray.findIndex()` and `someArray.splice()`, I don't trip the error.
```
let idToRemove = 1;
let indexToRemove = this.someProp.someArray.findIndex( arrayItem => {
  return arrayItem.id == idToRemove;
});
this.someProp.someArray.splice(indexToRemove, 1);
```

I'm not sure what layer of the JavaScript/Inertia/Vuejs stack is causing this odd behavior, but I hope this information helps to work around and/or fix the issue.

**Comment by jannescb** [comment] 2022-01-03 07:38
I ran into the same error, also with draggable and Vue3. The error occurred with nested objects and ONLY if they were already present in the initial state. If the object is built after initialization the error does not occur.

My workaround for the problem is to always initialize the form's deep keys "empty" and populate them after mounting:

I have a `content` key in my form which is a deeply nested object and i always clone the content coming from a prop after mounting:

```js
const form = useForm({
     content: {}
 })

onMounted(() => {
    form.content = JSON.parse(JSON.stringify(props.page.content));
});
```

**Comment by dillingham** [comment] 2022-02-06 02:38
in a computed property..
which adds bindings for v-bind
for when looping over dynamic components.. 

I did what Numenorian / jannescb suggested and the error went away

```js
let filters = JSON.parse(JSON.stringify(this.filters));

return filters.map(() => {})

**Comment by ewhicher** [comment] 2022-02-07 05:56
I ended up using Lodash `cloneDeep` to clone the data which fixed the issue: https://lodash.com/docs/#cloneDeep

**Comment by coclav** [comment] 2022-02-24 22:49
I pulled my hair on this one for months. My solution was similar to this https://github.com/inertiajs/inertia/issues/775#issuecomment-876030983 above

Spoiler : the problem was because a "Proxy" made its way to my state.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/1837434/155620006-a1d48038-6a42-4025-975a-e01dcb4579ec.png">

So I had to find out what couldn't be cloned ?!

<img width="618" alt="image" src="https://user-images.githubusercontent.com/1837434/155620170-a334fd47-a2ae-4b08-bb4c-6419d511dd3c.png">

put a breakpoint there... and started to dig into the `e` object until i saw this 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/1837434/155620433-bc8c268b-aa4d-4da7-975b-0f613c28075d.png">

I tried to "unProxy" the value with `JSON.parse(JSON.stringify(formField)),` and this solved the issue.

**Comment by roguesherlock** [comment] 2022-03-02 18:53
Yep. I came across this today and turns out I had proxy object in my state! Thanks guys

**Comment by pintend** [comment] 2022-03-08 19:08
>```vue
> <Draggable
>     v-model="project.columns"
>     group="columns"
>     item-key="id"
>     @end="onColumnPositionChanged"
> >
>     <template #item="{element: column}">
>         <KanbanColumn
>              :column="column"
>              :key="column.id"
>          />
>     </template>
> </Draggable>
> ```

Try changing `v-model="project.columns"` to `:list="project.columns"` i was having a similar issue and this seams to have solved it for me

[source](https://github.com/SortableJS/vue.draggable.next#list)

**Comment by dellow** [comment] 2022-04-11 09:38
Just to chime in that I'm also seeing this issue with Vue Draggable and Inertia.put.

`JSON.parse(JSON.stringify(formField))` does seem to solve the issue.

**Comment by pintend** [comment] 2022-04-11 13:04
> Just to chime in that I'm also seeing this issue with Vue Draggable and Inertia.put.
> 
> `JSON.parse(JSON.stringify(formField))` does seem to solve the issue.

Are you using v-model or list?

**Comment by dellow** [comment] 2022-04-14 11:10
> Are you using v-model or list?

`v-model`

**Comment by pintend** [comment] 2022-04-14 13:12
> > Are you using v-model or list?
> 
> `v-model`

Try using `:list` to see if you dont need to json parse it

**Comment by danielendrodi** [comment] 2022-04-26 09:13
I had the same error, I solved it by sending the complex JSON object as a string from the back end and JSON.parse it on the front end.

**Comment by jjjrmy** [comment] 2022-06-03 15:42
I'm getting this same error with my checkbox component.

```js
<script setup>
import { computed } from 'vue'

const props = defineProps(['modelValue','input'])
const emit = defineEmits(['update:modelValue'])

const value = computed({
  get() {
    return props.modelValue
  },
  set(value) {
-    emit('update:modelValue', value)
+    emit('update:modelValue', JSON.parse(JSON.stringify(value)))
  }
})
</script>

<template>
  <div>
    <template v-for="option in input.options">
        <input type="checkbox" v-model="value" :name="input.id" :value="{ id: option.id, value: option.value }" />
        <label>{{ option.label }}</label>
    </template>
  </div>
</template>
```

**Comment by mauriciolanner** [comment] 2022-09-27 13:52
> 

the best solucion

**Comment by ordago** [comment] 2022-10-20 22:32
@ewhicher I haven't been able to make `structuredClone` work. I get this error.

`"UnhandledPromiseRejectionWarning: DataCloneError: Proxy object could not be cloned."`

But `JSON.stringify` seems to do the trick.

**Comment by stephan-v** [comment] 2022-12-08 11:28
Ok so I know this is because there is a Proxy object within the data structure but can anyone elaborate on why this results in an error? I am more interested in the reason why this happens than all the makeshift solutions that have been posted so far (although helpful).

**Comment by jelleroorda** [comment] 2022-12-19 10:37
I had the same issue when using `usePage()` inside of the `state` function of Pinia.

Before:
```ts
    state: () => {
        return {
            cart: usePage().props.value.cart as Cart,
        }
    },

    actions: {
        setQuantity(product_id: number, quantity: any) {
            // Here an update to the cart happened
            this.cart.products = this.cart.products.map(productInCart => {
                if (productInCart.product_id !== product_id) {
                    return productInCart;
                }

                return {
                    ...productInCart,
                    quantity: quantity,
                }
            })
            
            // Then this PUT request will error
            Inertia.put('/cart/set', {
                cart_id: this.cart.id,
                product_id,
                quantity,
            }, {
                preserveScroll: true,
                only: ['cart', 'errors'],
            });
        },
    },
```

I've fixed it by changing the state to this:

```ts
    state: () => {
        const cart =  JSON.parse(JSON.stringify(usePage().props.value.cart))

        return {
            cart: cart as Cart,
        }
    },
```

**Comment by rizkhal** [comment] 2023-01-20 18:01
Passing props into `refs` instead of change the value of it

**Comment by dev-charles15531** [comment] 2023-03-20 20:16
> ```js
> const obj = reactive({ ... usePage().props.value.someObject });
> ```

You loose reactivity doing this, and i dont want that.

**Comment by DavidClaiborne** [comment] 2023-04-07 19:09
this did the trick for me;
```
const form = useForm(structuredClone(toRaw(props.promo)))
```
https://stackoverflow.com/questions/72632173/unable-to-use-structuredclone-on-value-of-ref-variable

**Comment by frknasir** [comment] 2023-07-12 20:16
In my case, I tried writing to a prop which is supposed to be readonly. Undoing that solved it.

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: vue 3

**Comment by SDIjeremy** [comment] 2023-10-11 18:54
Still having this problem

**Comment by LarryBarker** [comment] 2023-11-01 02:15
This issue just started popping up for us recently as well :\ 

```instrument.ts:383 Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': #<Object> could not be cloned.
    at History.replaceState (http://localhost:5173/node_modules/.vite/deps/@sentry_vue.js?v=351ebc3d:953:38)
    at C.replaceState (http://localhost:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=351ebc3d:5784:35)
    at C.saveScrollPositions (http://localhost:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=351ebc3d:5645:10)
    at C.resetScrollPositions (http://localhost:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=351ebc3d:5650:14)
    at http://localhost:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=351ebc3d:5776:19```
    
Going to walk back through some commits and see if we can figure out where it started happening, but it has been very difficult to debug so far.

@reinink what would it take to get you to look into this? is this still a thing with 1.0? thanks!

**Comment by SDIjeremy** [comment] 2023-11-01 03:20
@LarryBarker  the issue seems to happen when you are using or manipulating props directly/indirectly that are large or complex. a work around is as stated above, to encode and decode the prop data.

**Comment by LarryBarker** [comment] 2023-11-01 12:37
> @LarryBarker  the issue seems to happen when you are using or manipulating props directly/indirectly that are large or complex. a work around is as stated above, to encode and decode the prop data.

@SDIjeremy yeah, thank you, I did see that. It's a tricky issue to debug if you have many props being passed to the component.

**Comment by alagiesellu** [comment] 2023-11-19 21:06
> I had the same issue when using `usePage()` inside of the `state` function of Pinia.
> 
> Before:
> 
> ```ts
>     state: () => {
>         return {
>             cart: usePage().props.value.cart as Cart,
>         }
>     },
> 
>     actions: {
>         setQuantity(product_id: number, quantity: any) {
>             // Here an update to the cart happened
>             this.cart.products = this.cart.products.map(productInCart => {
>                 if (productInCart.product_id !== product_id) {
>                     return productInCart;
>                 }
> 
>                 return {
>                     ...productInCart,
>                     quantity: quantity,
>                 }
>             })
>             
>             // Then this PUT request will error
>             Inertia.put('/cart/set', {
>                 cart_id: this.cart.id,
>                 product_id,
>                 quantity,
>             }, {
>                 preserveScroll: true,
>                 only: ['cart', 'errors'],
>             });
>         },
>     },
> ```
> 
> I've fixed it by changing the state to this:
> 
> ```ts
>     state: () => {
>         const cart =  JSON.parse(JSON.stringify(usePage().props.value.cart))
> 
>         return {
>             cart: cart as Cart,
>         }
>     },
> ```

I think it has something to do with the package [@vueuse/core](https://vueuse.org/core)

I am having the same error on pages where I use `useIntersectionObserver`


@antfu and team should help out here.

**Comment by eurairapelli** [comment] 2024-02-06 02:13
> > ```
> > <Draggable
> >     v-model="project.columns"
> >     group="columns"
> >     item-key="id"
> >     @end="onColumnPositionChanged"
> > >
> >     <template #item="{element: column}">
> >         <KanbanColumn
> >              :column="column"
> >              :key="column.id"
> >          />
> >     </template>
> > </Draggable>
> > ```
> 
> Try changing `v-model="project.columns"` to `:list="project.columns"` i was having a similar issue and this seams to have solved it for me
> 
> Source: https://github.com/SortableJS/vue.draggable.next#list

Its work. I do this, list into list (laravel with:tasks) and works change to :list

**Comment by rkyoku** [comment] 2024-02-23 07:55
I have this bug when dynamically adding a function to an object/prop in Svelte (`export let mystuff; mystuff.onEvent = () => {}`)

This is extremely handy and saves from using events (which can only happen AFTER mount, at least in Svelte) (and the syntax is also shorter and more intuitive than events)

Maybe remove functions before serializing?

**Comment by jamesst20** [comment] 2024-05-10 01:18
**2024 - Svelte 5**

```
  let { fieldGroups = [] }: Props = $props();

  structuredClone(fieldGroups);
```

Anything related to the state will not be "cloneable" so it's very likely this error will be triggered often.

`$state.snapshot` is required for deep cloning

**Comment by notifybee** [comment] 2024-06-06 05:57
Hi,

I've just come across this issue, also with vue draggable from https://github.com/Alfred-Skyblue/vue-draggable-plus

I noticed that after moving a card from one nested list to another, that the moved card is no longer proxied.

I don't know enough about vuejs/inertiajs but might that non-proxied object be the cause of this bug?

<img width="900" alt="not proxied" src="https://github.com/inertiajs/inertia/assets/13155555/c5c8a510-6136-45ef-a92d-a595f481e3bf">

**Comment by pedroborges** [comment] 2024-09-09 17:01
@jamesst20 just read the whole thread but honestly I'm not sure how I can reproduce this issue. If you or anyone can tell me how to reproduce it with Inertia I'd be happy to debug and work on a fix.
