### ISSUE TITLE
Removing URL parameters

### ISSUE THREAD

**Issue by danielprrazevedo** [inertiajs/inertia#1334] opened 2022-11-07 02:21 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.1
- `@inertiajs/inertia-react` version: 0.8.1

### Describe the problem:

When we do a navigation with `Inertia.get(route, {param: 'my-param'})` and then we do the navigation removing the parameter `Inertia.get(route, {})`, the parameter persists in the URL.

### Steps to reproduce:

call
```js
Inertia.get('', {param: 'myparam'})
```
Then use some event to call again
```js
Inertia.get('', {})
```
Note that `'?param=myparam'` will remain in the URL

**Comment by reinink** [comment] 2023-07-28 01:50
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:50 UTC
