### ISSUE TITLE
Critical bug in page redirecting

### ISSUE THREAD

**Issue by MohammadZarifiyan** [inertiajs/inertia#1543] opened 2023-05-08 14:05 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.6

### Describe the problem:

On each redirection in Firefox the following error happens:
**Consider that this is ok in other browsers like Chrome and Edge.**

![image](https://user-images.githubusercontent.com/55022827/236844887-f897fc0c-b781-4f30-81f9-42002d72c1bd.png)

### Steps to reproduce:

After clicking on form submit button, Laravel Controller redirects user to another page, But instead of redirecting, The error in above image occurs.

**Comment by RobertBoes** [comment] 2023-05-08 14:30
As the error is telling, you're not sending a proper Inertia response from the page where it's being redirected to. Most likely response headers are missing, which could be the middleware not being present on the route

Other than that, there's no information here to determine what the cause/issue could be. I primarily use Firefox and in a clean Inertia setup this problem doesn't exist. You could take a look at the [PingCRM](https://inertiajs.com/demo-application) demo, or other projects like [Laravel Breeze](https://laravel.com/docs/10.x/starter-kits#breeze-and-inertia) to see if you experience the same issue there.

**Comment by MohammadZarifiyan** [comment] 2023-05-08 14:42
The only change from old server and new server is that the current server uses nginx instead of OpenLiteSpeed.

**Comment by reinink** [comment] 2023-05-08 14:55
Something to look at — I wonder if you have a proxy in place that could be messing with the accept/vary header.

I don't have time to dig into this for you, but I'd recommend reviewing what I did here:

https://github.com/inertiajs/inertia-laravel/pull/404

And make sure you're on the latest version of the Laravel Inertia adapter.

Good luck!

**Comment by Chubb001** [comment] 2023-05-08 15:02
I've encountered the same problem. It works locally but not in production, so it must be a server config problem. I'm using nginx, Google Cloudrun and Cloudflare.

Locally my response header includes capital letters in the key:
```
X-Inertia: true
Vary: X-Inertia
```
But in production the key is lowercase:
```
x-inertia: true
vary: X-Inertia
```
That's the only difference I can see.

**Comment by RobertBoes** [comment] 2023-05-08 15:18
As far as I can see Inertia does use lowercase checks: https://github.com/inertiajs/inertia/blob/master/packages/core/src/router.ts#L204-L206 
Might not be in older versions, so checking if you're running the latest version is a good idea anyways

**Comment by MohammadZarifiyan** [comment] 2023-05-08 17:47
> I've encountered the same problem. It works locally but not in production, so it must be a server config problem. I'm using nginx, Google Cloudrun and Cloudflare.
> 
> Locally my response header includes capital letters in the key:
> 
> ```
> X-Inertia: true
> Vary: X-Inertia
> ```
> 
> But in production the key is lowercase:
> 
> ```
> x-inertia: true
> vary: X-Inertia
> ```
> 
> That's the only difference I can see.

Exactly, My code works in local but fails in production.

You can check my website using this link: https://mymember.shop

**Comment by Chubb001** [comment] 2023-05-10 12:13
For some reason Firefox is detecting the request as being cross origin, and blocking access to the header. I managed to fix this by adding this to my nginx.conf
```
add_header 'Access-Control-Expose-Headers' 'X-Inertia';
```

**Comment by MohammadZarifiyan** [comment] 2023-05-11 06:47
> For some reason Firefox is detecting the request as being cross origin, and blocking access to the header. I managed to fix this by adding this to my nginx.conf
> 
> ```
> add_header 'Access-Control-Expose-Headers' 'X-Inertia';
> ```

Thank you very much, It worked for me.
How you knew how to solve this problem?

**Comment by reinink** [comment] 2023-07-28 01:37
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:37 UTC
