### ISSUE TITLE
Inertia JS error while clicking on a Link

### ISSUE THREAD

**Issue by MohammadZarifiyan** [inertiajs/inertia#1439] opened 2023-02-09 07:19 UTC
### Version:

- `@inertiajs/inertia-vue3` version: 0.6.0
- `inertiajs/inertia-laravel` version: 0.6.3

### The problem:

**Sometimes** when i click on a Inerta Link the "**All Inertia requests must receive a valid Inertia response, however a plain JSON response was received**" shows up on a white modal that containing a JSON with props and component name that belongs to login page.

**Sometimes** reloading the page after this error can solve the problem.

Here is the code:

```vue
<template>
    <Link href="https://example.com/same-path?page=2">Go to page 2</Link>
</template>

<script>
import {Link} from '@inertiajs/inertia-vue3';

export default {
    components: {Link}
}
</script>
```

This is my `App\Http\Kernel.php`:

```php
protected $middlewareGroups = [
    'web' => [
        ... Other middlewares ...
        \App\Http\Middleware\HandleInertiaRequests::class,
    ],
];
```

**Comment by rjdaini22** [comment] 2023-07-26 09:19
Try changing your href from "https://example.com/same-path?page=2" to "/same-path?page=2".

For more informations abour Inertia.js Link component :
https://inertiajs.com/links

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
