### ISSUE TITLE
$store.component.default is undefined

### ISSUE THREAD

**Issue by pepa-linha** [inertiajs/inertia#422] opened 2021-01-10 17:08 UTC
Hi,

I got `undefined` on this line

https://github.com/inertiajs/inertia/blob/df829aa63761ef303178b42ee355a0a182566af1/packages/inertia-svelte/src/App.svelte#L26

because `$store.component.default` is `undefined` and components are not rendered. Can you please tell me what is wrong? `$store.component` is not instance but "only" FunctionConstructor.

My _main.ts_ file

```
import { InertiaApp } from "@inertiajs/inertia-svelte";

import Homepage from "./Pages/Homepage.svelte";
import About from "./Pages/About.svelte";

const pages = {
    Homepage,
    About,
}

const target = document.getElementById('app')

new InertiaApp({
    target,
    props: {
        initialPage: JSON.parse(target.dataset.page),
        resolveComponent: name => pages[name],
    },
})
```

My _Homepage.svelte_ file

```
<script context="module">
    import Layout from "../Shared/Layout.svelte"
    export const layout = Layout
</script>

<script lang="ts">
    export let name: string
</script>

<Layout title="Welcom">
    <h1>Welcome {name}</h1>
</Layout>
```

Thanks

**Comment by danieldiekmeier** [comment] 2021-01-14 11:43
I also noticed this in my project. As you already saw, the problem is that Inertia tries to get the Component from `$store.component.default`.

As a workaround, I created a new object that has the `default` key. Adjusting your code, it would be like:

```js
new InertiaApp({
    target,
    props: {
        initialPage: JSON.parse(target.dataset.page),
        resolveComponent: name => ({ default: pages[name] }),
    },
})
```

**Comment by pepa-linha** [comment] 2021-01-21 21:36
Thanks, it works but I do not understand why.

**Comment by jordankaerim** [comment] 2021-02-23 17:32
If I am not mistaken, this doesn't seem to actually be a problem with the Svelte adapter. The `resolveComponent` is supposed to dynamically import a page component with the `import()` function. This function returns an object where the default export is the `default` property. If you however import your page components statically at build like you do in your code:
```js
import Homepage from "./Pages/Homepage.svelte";
```
then `Homepage` already is the default export. I would recommend to dynamically import your pages to take advantage of code splitting so that you do not end up with a big single bundle file.

This is how I do it with Rollup:
```js
import { InertiaApp } from "@inertiajs/inertia-svelte";

const app = document.getElementById("app");
new InertiaApp({
  target: app,
  props: {
    initialPage: JSON.parse(app.dataset.page),
    resolveComponent: importPage,
  },
});

function importPage(name) {
  switch (name) {
    case "Login":
      return import("./pages/Login.svelte");

    case "Register":
      return import("./pages/Register.svelte");

    default:
      throw new Error(`Cannot find component`);
  }
}
```
If you use Webpack then according to the docs the code should look like this:
```js
new App({
  target: el,
  props: {
    initialPage: JSON.parse(el.dataset.page),
    resolveComponent: name => require(`./Pages/${name}.svelte`),
  },
})
```

**Comment by pepa-linha** [comment] 2021-02-25 21:35
@jordankaerim My weak experience with imports... Thank you for the explanation.

**Comment by reinink** [comment] 2021-02-25 21:38
@jordankaerim Thanks so much for jumping in here! 🙌 

@pepa-linha Can we mark this issue as resolved (closed)?

**Comment by jordankaerim** [comment] 2021-02-26 12:27
To add one more last thing: Both the React and Vue adapter expect the `default` export while the Svelte adapter needs all exports of the module. That's because in Svelte we can do something like this:
```html
<!-- Component.svelte -->
<script context="module">
  export const hello = "Hello";
  export const world = "World";
</script>

<!-- App.svelte -->
<script>
  import Component, { hello, world } from "Component.svelte"
</script>
```
Everything that's exported from `<script context="module">` becomes an export of the module itself. This feature is used to pass in persistent layouts to the Svelte adapter:
```html
<script context="module">
  import Layout from './Layout.svelte'
  export const layout = Layout
</script>
```
So when something like the following is resolved the module contains both the actual page component in the `default` property as well as the `layout` component and everything else that's exported from `<script context="module">`.
```js
const { default, layout } = await import("Component.svelte")
```

**Comment by reinink** [comment] 2021-02-26 19:19
Great explanation @jordankaerim. 👍 

Closing this, as it appears to be resolved.

**Closed by reinink** 2021-02-26 19:19 UTC
Labels: svelte
