### ISSUE TITLE
Is there any way to access persistent layout's refs?

### ISSUE THREAD

**Issue by Neography7** [inertiajs/inertia#1095] opened 2022-02-10 21:25 UTC
### Discussed in https://github.com/inertiajs/inertia/discussions/1092

<div type='discussions-op-text'>

<sup>Originally posted by **Neography7** February  9, 2022</sup>
Hello all, I have a question. Is there any way to access persistent layout's refs? 

For example my project layout have a navbar

`<Navbar ref="Navbar" />`

I want to access this Navbar from a page that uses this layout. Is it possible? $parent and $refs didn't give this ref.</div>

**Comment by jrson83** [comment] 2022-02-21 23:00
Which framework are you using?

**Comment by Neography7** [comment] 2022-02-21 23:07
> Which framework are you using?

I'm using Vue 3

**Comment by jrson83** [comment] 2022-02-22 23:05
Ok, sorry it took some time, but here is an example of how you can reference the `<Navbar />` inside your Pages components like `src/Pages/Home.vue`, using `ref="root"`, thanks to @RobertBoes:

https://codesandbox.io/s/adoring-moon-rfwnek

**Comment by jrson83** [comment] 2022-02-22 23:10
I have tried to create a working example, but I couldn't get it work to set a reference to the Navbar through persistent Layout, to get access to the Navbar from a Page component, sorry.

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
