### ISSUE TITLE
useForm doesn't properly work in v-for loop with nested objects

### ISSUE THREAD

**Issue by Arturexe** [inertiajs/inertia#1239] opened 2022-07-27 14:00 UTC
### Versions:

        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",

### Steps to reproduce:

I am transforming a nested `props` object into a `form`:
```
const props = defineProps({
    news: Object // {{ id: 1, body: "abc", ... }, { id: 2, body: "def", ... }, ... }
})

const form = useForm(props.news)
```

 and use it as source for a `v-for` loop:

```
<div class="news-card" v-for="(card, key) in form" :key=key>
    <p>{{card.id}}</p>
</div>
```

The paragraph throws this error message:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
```

If instead of `useForm` I use a `reactive` object, there is no such issue:
```
const state = reactive(props.news)
```
and 
```
<div class="news-card" v-for="(card, key) in state" :key="key">
    <p>{{card.id}}</p> // displays the id correctly
</div>
```

**Comment by ordago** [comment] 2022-08-08 14:07
I haven't had such problems using nested values with forms.

This looks like an array, not an object. Which are the object keys?

```javascript
const props = defineProps({
    news: Object // {{ id: 1, body: "abc", ... }, { id: 2, body: "def", ... }, ... }
})
```

This issue seems related to #1233 that you opened. Which also has problems with mixing arrays and objects.

I'd suggest you look into that and use an object with named keys instead of number keys.

**Comment by craigrileyuk** [comment] 2022-10-12 00:23
Your problem is likely caused by the fact that using `useForm` returns an object with lots of extra methods and properties on it besides just your form fields, so when you `v-for` over all of its keys, your getting those extra methods/properties hitting the iterator (which aren't objects, so calling .id on them is causing your error).

**Comment by reinink** [comment] 2023-07-28 01:51
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:51 UTC
