### ISSUE TITLE
The form does not reset when it contains an array of objects

### ISSUE THREAD

**Issue by iamohd-zz** [inertiajs/inertia#553] opened 2021-03-16 18:06 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

The form does not reset when it contains an array of objects.

### Steps to reproduce:

1. Create an instance of inertia form that has an array attribute

```
data() {
    return {
        form: this.$inertia.form({
              users: []
        });
    }
}
```

2. Then push some values into that array
```
this.form.users.push({id: 1, name: 'first'});
```

3. Then reset the form
```
this.form.reset();
```

The form will not reset and still contains the pushed items.

**Comment by reinink** [comment] 2021-03-26 03:03
This is fixed in #575! 🙌

**Comment by bayangan** [comment] 2023-06-30 20:47
Versions:
"@inertiajs/vue3": "^1.0.0",

same problem as issue starter. form.reset() not working on empty array. I have to manually set it to empty array again

**Comment by yoeriboven** [comment] 2023-08-18 23:09
This problem persists on `@inertiajs/vue3@1.0.9`.

**Comment by reinink** [comment] 2023-08-21 17:29
Going to reopen this one to remind myself to have another look.

In the meantime, if you're able to provide a minimal reproduction as a Git repo that would be much appreciated.

**Comment by reinink** [comment] 2023-08-23 11:05
@yoeriboven great, thanks for sharing, we'll have a look at this 👍

**Comment by jessarcher** [comment] 2023-08-31 01:43
Hey @yoeriboven,

Your scenario is a bit different to the original issue. In your case, the behaviour you're experiencing is intentional. Once the form has been submitted, the default form state is updated to the submitted state because that is typically what you'd want on an edit form, where resetting it should reset it back to the current state on the server.

There are two things you can do here.

1. If you want to automatically reset the state to the original defaults, you can use the `onSuccess` callback to call `form.reset()` before Inertia updates the defaults:

    ```js
    const submit = () {
      form.post('/user', {
        onSuccess: () => form.reset(),
      })
    }
    ```
3. If you only want the reset to occur when the user presses the "Reset" button, you can pass the defaults as a callback (instead of an object) which allows you to take control what happens:
  
    ```js
    const form = useForm(() => ({
      name: '',
      // etc...
    }))
    ```

**Comment by jessarcher** [comment] 2023-08-31 01:44
@bayangan we were not able to replicate this with an empty array. If you can provide a minimal reproduction repository then we can take another look.

Going to close this one for now.

**Closed by jessarcher** 2023-08-31 01:44 UTC
Labels: vue 3
