### ISSUE TITLE
Can't run npm run build  Missing "./types" specifier in "@inertiajs/react" package error during build:

### ISSUE THREAD

**Issue by konexioncnns** [inertiajs/inertia#1481] opened 2023-03-03 23:40 UTC
### Version:

- `@inertiajs/react` version: 1.0

### Describe the problem:

Can't run "npm run build"

[commonjs--resolver] Missing "./types" specifier in "@inertiajs/react" package
error during build:
Error: Missing "./types" specifier in "@inertiajs/react" package

### Steps to reproduce:

when we run "npm run build" command it issue an error 
![err](https://user-images.githubusercontent.com/67736368/222855227-5f6314ce-38fd-4bd4-b6b9-9f06009d37fe.PNG)

**Comment by christian98** [comment] 2023-03-17 19:17
I had/have the same issue and tried to fix it in #1397 a while ago. Today a tried the "fixed" version and still encounter the problem. Also, #1416 reported the issue, which was closed with my PR. Maybe someone smarter than me has an idea of how to fix this problem.

**Comment by reinink** [comment] 2023-07-28 01:47
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:47 UTC
Labels: react

**Comment by joelrhenisch** [comment] 2024-01-18 08:15
@konexioncnns Have you already checked the imports in your react files? Maybe you can find an obsolete import which cannot be resolved on the `npm run build` command.
