### ISSUE TITLE
<App> was created with unknown prop 'initialPage'

### ISSUE THREAD

**Issue by Dibbyo456** [inertiajs/inertia#1436] opened 2023-02-08 05:54 UTC
### Version:

- `@inertiajs/svelte` version: 1.0.0

### Describe the problem:

Problem 1: Errors in browser console
````
<App> was created with unknown prop 'initialPage' [@inertiajs_svelte.js:5976:15]
<App> was created with unknown prop 'resolveComponent' [@inertiajs_svelte.js:5976:15]
<Home> received an unexpected slot "default". [chunk-G52SVBKY.js:1974:15]
<Home> was created with unknown prop 'errors'
````
<img width="1582" alt="Screenshot 2023-02-08 at 10 58 12 AM" src="https://user-images.githubusercontent.com/18257605/217445846-7d86fada-1172-4367-86a8-1eda72618f77.png">

Problem 2: What is `$unknown` when building?

````sh
harry@Harrys-MacBook-Air  ~/bug-report  pnpm build 

> @ build /Users/harry/bug-report
> vite build

vite v4.1.1 building for production...
✓ 98 modules transformed.
11:09:39 AM [vite-plugin-svelte] dom compile done.
package                 files     time     avg
@inertiajs/svelte           4   48.8ms  12.2ms
$unknown                    1   16.0ms  16.0ms
public/build/manifest.json             0.25 kB
public/build/assets/app-4ed993c7.js    0.00 kB │ gzip:  0.02 kB
public/build/assets/app-251c86e5.js  102.02 kB │ gzip: 36.25 kB
harry@Harrys-MacBook-Air  ~/bug-report  
````

### Steps to reproduce:

```sh
git clone https://github.com/Dibbyo456/inertijs-svelte-bug-report
php artisan serve
pnpm dev
````

**Comment by gsxdsm** [comment] 2023-03-07 00:50
In the examples the app setup looks like:
new App({ target: el, props});

I found that the props isn't necessary - try removing that and it clears the first error.

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
Labels: svelte
