### ISSUE TITLE
TS2305: Module '"@inertiajs/inertia-react"' has no exported member 'createInertiaApp'

### ISSUE THREAD

**Issue by olivertembo** [inertiajs/inertia#980] opened 2021-11-26 11:19 UTC
### Versions:

- `@inertiajs/inertia` version: "^0.9.0",
- `@inertiajs/inertia-react` version: "^0.6.0"

### Describe the problem:

It's an error where the inertia-react/index doesn't have a default member
### Steps to reproduce:

Install Laravel with React Breeze
Use Typescript for React.

**Comment by claudiodekker** [comment] 2022-01-07 09:20
Duplicate of #823 - Already fixed in version 0.7.1

**Closed by claudiodekker** 2022-01-07 09:20 UTC
Labels: bug, react
