### ISSUE TITLE
`preserve-state` & `preserve-scroll` should accept `Boolean` and `Function`

### ISSUE THREAD

**Issue by BR0kEN-** [inertiajs/inertia#1125] opened 2022-03-12 20:54 UTC
### Versions:

- `@inertiajs/inertia` version: latest for 2022-03-12, 20:47 GMT
- `@inertiajs/inertia-vue` version: latest for 2022-03-12, 20:47 GMT

### Describe the problem:

Inertia's `Router` accepts the `preserveState` and `preserveScroll` as `Boolean` and `Function` however the `InertiaLink` component accepts `Boolean` only.

https://github.com/inertiajs/inertia/blob/85b5694dea5c6193809e9ddd4eada4dfee054f7f/packages/inertia/src/router.ts#L317-L318
https://github.com/inertiajs/inertia/blob/85b5694dea5c6193809e9ddd4eada4dfee054f7f/packages/inertia-vue/src/link.js#L25-L32
https://github.com/inertiajs/inertia/blob/85b5694dea5c6193809e9ddd4eada4dfee054f7f/packages/inertia-vue3/src/link.js#L26-L33

### Steps to reproduce:

```vue
<template>
  <inertia-link :preserve-state="(page) => true" :preserve-scroll="(page) => true">
    Link
  </inertia-link>
</template>
```

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
