### ISSUE TITLE
Link component's `as` doesn't render other components

### ISSUE THREAD

**Issue by kenan-recebli** [inertiajs/inertia#1550] opened 2023-05-12 23:51 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.6

### Describe the problem:

When I use `as` prop to render a different tag, it works. But if I pass another component to `as`, it just shows name of the passed component. This issue doesn't exist in vue2 adapter (exactly in version 1.0.6). I can use `<Link as="v-btn">` and it renders `v-btn` component, but in vue3 adapter it seems to be broken.

### Steps to reproduce:

```vue
<script setup>
import { Link } from '@inertiajs/vue3'
import MyComponent from '@/Path/To/Component/MyComponent .vue'
</script>

<template>
    <Link as="v-btn" href="/page">Button</Link>
    <Link as="v-tab" href="/page">Tab</Link>
    <Link as="my-component" href="/page">Label</Link>

    <my-component>My component</my-component>
</template>
```

#### Expected result:

```html
<button type="button" class="v-btn v-theme--light v-btn--density-default v-btn--size-default"><span class="v-btn__overlay"></span><span class="v-btn__underlay"></span><span class="v-btn__content">Button</span></button>
<button type="button" class="v-btn v-theme--light v-btn--density-default v-btn--size-default v-tab" tabindex="-1" role="tab" aria-selected="false"><span class="v-btn__overlay"></span><span class="v-btn__underlay"></span><span class="v-btn__content" data-no-activator="">Tab<div class="v-tab__slider"></div></span></button>
<div class="my-comp">Label</div>
<!-- no anchors, but when clicked, it should navigate just like in vue2 adapter  -->

<div class="my-comp">My component</div>
```

#### Actual result:

```html
<v-btn>Button</v-btn>
<v-tab>Tab</v-tab>
<my-component>Label</my-component>
<!-- no anchors, but when clicked, it navigates, however it looks ugly because components aren't rendered -->

<div class="my-comp">My component</div>
```

##### Workaround 

As a workaround I'm using a regular component and navigate via router.get, and even created a component, so I just pass URL and component's name, but it's still very inconvenient.

**Comment by craigrileyuk** [comment] 2023-05-28 08:37
This isn't an issue with inertia, it's a change to how `script setup` makes the components available to the template.

As easier workaround when working with Vuetify is to use the following plugin (install it using `app.use(convertRouterToInertia)` in your app's entry file):

```js
import { computed, useAttrs, ref } from "vue";
import { router } from "@inertiajs/vue3";
import { useBrowserLocation } from "@vueuse/core";
import { useRoute } from "inertiaRoutes";

const currentLocation = ref(null);

const RouterLink = {
	useLink(props) {
		const browserLocation = useBrowserLocation();
		if (!currentLocation.value)
			currentLocation.value = `${browserLocation.value.origin}${browserLocation.value.pathname}`;

		const route = useRoute();
		const attrs = useAttrs();
		const parameters = attrs["to-params"] || {};
		const method = attrs["to-method"] || "GET";

		return {
			route: computed(() => ({ href: route(props.to, parameters) })),
			isExactActive: computed(() => currentLocation.value === route(props.to, parameters)),
			isActive: computed(() => currentLocation.value.startsWith(route(props.to, parameters))),
			navigate(e) {
				if (e.shiftKey || e.metaKey || e.ctrlKey) return;
				e.preventDefault();

				currentLocation.value = route(props.to, parameters);
				router.visit(currentLocation.value, { method });
			},
		};
	},
};

export const convertRouterToInertia = {
	install: (app) => {
		app.component("RouterLink", RouterLink);
	},
};
```

Now you can use the `vue-router` functionality built in to Vuetify to power Inertia's router instead:

```html
    <v-btn to="/page">Button</v-btn>
    <v-tab to="/page">Tab</v-tab>
```

**Comment by cjholowatyj** [comment] 2023-06-05 18:27
Tested this myself, and can confirm that `Link` isn't rendering custom components when using the `as` property.

Assuming...
`import ImportedComponent from 'Path/To/ImportedComponent.vue';`
...I use the...
`<component :as="ImportedComponent"/>`
format in plenty of places in my projects...

Would be great if `<Link>` could be fixed to follow the same syntax/functionality as `<component>`
(where `as` can be bound directly to an imported component).

**Comment by msoubofficial** [comment] 2023-06-13 07:56
seems , nobody seriously pays attention to this ,  the whole base seems to be using tailwind , so yeah this issue prevents inertia vue from integrating it with the external world of component libraries like vuetify , or quasar or so. Well i have started a discussion on Quasar [#15969](https://github.com/quasarframework/quasar/discussions/15969)

**Comment by kenan-recebli** [comment] 2023-06-13 15:49
@msoubofficial 
Actually I-ve integrated it with vuetify. In version 2 it works perfectly, in 3rd version this is the only problem for now. I mentioned above about a workaround I used, but couple weeks ago someone wrote another great workaround, but his reply was deleted (don't know who deleted it). Fortunately, his reply was sent to my e-mail and I suddenly noticed it a few days ago. I refactored it a little bit and now this issue don't worry me at all. I keep it open in order to be fixed for other users of this great package.

This is the solution I found in my E-mail:

```
This isn't an issue with inertia, it's a change to how script setup makes the components available to the template.

As easier workaround when working with Vuetify is to use the following plugin (install it using app.use(convertRouterToInertia) in your app's entry file):

import { computed, useAttrs, ref } from "vue";
import { router } from "@inertiajs/vue3";
import { useBrowserLocation } from "@vueuse/core";
import { useRoute } from "inertiaRoutes";

const currentLocation = ref(null);

const RouterLink = {
	useLink(props) {
		const browserLocation = useBrowserLocation();
		if (!currentLocation.value)
			currentLocation.value = `${browserLocation.value.origin}${browserLocation.value.pathname}`;

		const route = useRoute();
		const attrs = useAttrs();
		const parameters = attrs["to-params"] || {};
		const method = attrs["to-method"] || "GET";

		return {
			route: computed(() => ({ href: route(props.to, parameters) })),
			isExactActive: computed(() => currentLocation.value === route(props.to, parameters)),
			isActive: computed(() => currentLocation.value.startsWith(route(props.to, parameters))),
			navigate(e) {
				if (e.shiftKey || e.metaKey || e.ctrlKey) return;
				e.preventDefault();

				currentLocation.value = route(props.to, parameters);
				router.visit(currentLocation.value, { method });
			},
		};
	},
};

export const convertRouterToInertia = {
	install: (app) => {
		app.component("RouterLink", RouterLink);
	},
};
Now you can use the vue-router functionality built in to Vuetify to power Inertia's router instead:

    <v-btn to="/page">Button</v-btn>
    <v-tab to="/page">Tab</v-tab>
```

I this is my refactored version:

```js
import { computed, useAttrs, ref } from 'vue'
import { router } from '@inertiajs/vue3'
import { useBrowserLocation } from '@vueuse/core'

const location = ref(null)

export const routerLink = {
    install: app => app.component('RouterLink', {
        useLink (props) {
            const browserLocation = useBrowserLocation()

            if (!location.value) {
                location.value = browserLocation.value.origin + browserLocation.value.pathname
            }

            const attrs = useAttrs()

            return {
                route: computed(() => ({
                    href: props.to,
                })),
                isExactActive: computed(() => location.value == props.to),
                isActive: computed(() => location.value.startsWith(props.to)),
                navigate (e) {
                    if (e.shiftKey || e.metaKey || e.ctrlKey) {
                        return
                    }

                    e.preventDefault()

                    location.value = props.to

                    router.visit(location.value, {
                        method: attrs['method'] || 'get',
                        data: attrs['data'],
                    })
                },
            }
        },
    }),
}
```

Now I really can use just `<v-btn to="/page">Button</v-btn>`. No more inertia link :) Options I've passed to `router.visit` is enough for now, I will add more if I need to.

**Comment by msoubofficial** [comment] 2023-06-14 09:39
well, there are plenty of methods of making this work , but the question is the maintainence of that peice of code.

**Comment by craigrileyuk** [comment] 2023-06-15 21:00
> Fortunately, his reply was sent to my e-mail and I suddenly noticed it a few days ago. I refactored it a little bit and now this issue don't worry me at all. I keep it open in order to be fixed for other users of this great package.

Yeah, sorry. That was me.

I posted that code and then realised that I was using the @adminui/inertia-routes package as well as a Vite alias for said package.

I figured it required too much refactoring to make it "vanilla" so I deleted the comment lest I confuse anyone.

Glad it helped!

**Comment by kenan-recebli** [comment] 2023-06-16 07:35
@craigrileyuk actually not so much refactoring, just a little bit refactored your code and changed link components to regular components with `to`. Thank you! 😊

**Comment by reinink** [comment] 2023-07-28 01:26
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:26 UTC
