### ISSUE TITLE
Persistent layouts not injected when using inertia in Vue Typescript project

### ISSUE THREAD

**Issue by Davit-000** [inertiajs/inertia#466] opened 2021-01-26 20:14 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue` version: 0.5.5

### Describe the problem:

Page Persistent Layout is not injecting, but bundle compiling successfully and there are no any runtime errors.

### Steps to reproduce:

**tsconfig.json**
```
{
  "allowJs": false,
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "node",
      "vuetify",
      "ziggy-js"
    ],
    "paths": {
      "@/*": [
        "resources/ts/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "es5",
      "dom.iterable",
      "scripthost",
      "es2015.promise"
    ]
  },
  "include": [
    "resources/ts/**/*.ts",
    "resources/ts/**/*.tsx",
    "resources/ts/**/*.vue"
  ],
  "exclude": [
    "node_modules"
  ],
  "files": [
    "resources/ts/shims-tsx.d.ts",
    "resources/ts/shims-vue.d.ts",
    "resources/ts/shims-vuetify.d.ts",
    "resources/ts/shims-inertia.d.ts",
  ]
}
```

**shims-inertia.d.ts**
```
import Vue from 'vue';
import { Inertia } from '@inertiajs/inertia';
import Page from '@/types/Page';

declare module 'vue/types/vue' {
  interface Vue {
    readonly $inertia: Inertia;
    readonly $page: Page;
  }
}

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    layout?: any;
  }
}

export default Vue;
```

**app.ts**
```
import route from 'ziggy-js';
import Vue, {CreateElement} from 'vue';
import vuetify from '@/plugins/vuetify';
import {App, plugin as inertia} from '@inertiajs/inertia-vue';

Vue.use(inertia);
Vue.mixin({methods: {route}});
Vue.config.productionTip = false;

const app = document.getElementById('app');

new Vue({
  vuetify,
  render: (h: CreateElement) =>
    h(App, {
      props: {
        initialPage: JSON.parse(app?.dataset.page as string),
        resolveComponent: (name: string) => require(`@/pages/${name}`).default
      },
    }),
}).$mount('#app');

```

**Home.vue**
```
<template>
  <v-container>
    <h1>{{ msg }}</h1>
  </v-container>
</template>

<script lang="ts">
import {Vue, Component, Prop} from 'vue-property-decorator';
import AppLayout from '@/layouts/AppLayout.vue';

@Component({
  name: "Welcome",
  layout: AppLayout,
  components: {
    TestComponent
  }
})
export default class Home extends Vue {
  @Prop(String) readonly phpVersion!: string;

  msg = 'Welcome to Laravel Vue Typescript Vuetify App!!!';
}
</script>
```

**AppLayout**

```
<template>
  <v-app>
    <v-app-bar app>
      <v-app-bar-nav-icon @click="drawer = !drawer"></v-app-bar-nav-icon>

      <v-toolbar-title>Application</v-toolbar-title>
    </v-app-bar>

    <v-navigation-drawer v-model="drawer" app>
      <!--  -->
    </v-navigation-drawer>

    <v-main>
      <slot></slot>
    </v-main>
  </v-app>
</template>

<script lang="ts">
import {Component, Vue} from 'vue-property-decorator';

@Component({
  name: "AppLayout"
})
export default class AppLayout extends Vue {
  drawer = true
}
</script>
```

**Comment by juanparati** [comment] 2021-02-03 12:41
I am facing the same issue.

I discovered that when component is transpiled using Typescript the vlue passed to the resolveComponent is a function  named "VueComponent" instead the component object.

See example of the component received:

![vuecomponent](https://user-images.githubusercontent.com/835173/106746888-73f11500-6623-11eb-8ab0-08f582362a86.png)

It doesn't matter if the Vue component is exported transpiled from a class, it also going to fails as a normal object like the following one that don't use any decorator:

```
<script lang="ts">
import Layout from '@/Shared/MyLayout';

export default {
    layout: [MyLayout]
}
</script>
```
In the previous example I just added the "lang=ts" to "script" tag, and it is enough for fail.

It seems that "render" function located in "app.js" cannot find "this.component" because the passed value is the VueComponent function so it cannot access to "this.component.layout" (@Davit-000: By the way the layout should be passed as an array item, see the app.js code).

For the same reason that layout property is not accessible the properties are not merged with the native Vue props, so I have to access directly to "$page.props" in my components.

Can somebody provide a functional example of how to use layouts with InertiaJS and Typescript??

**Comment by juanparati** [comment] 2021-02-03 12:46
This is how looks like the object passed to resolveComponent when is not transpiled by Typescript:

![Screenshot 2021-02-03 at 13 44 20](https://user-images.githubusercontent.com/835173/106748849-1ad6b080-6626-11eb-9ce5-2e23439719a4.png)

In this case it works but I cannot use Typescript.

**Comment by azurinspire** [comment] 2021-02-24 08:44
I'm complete newbie with Typescript, so I have no idea if my solution is by any means good, but I got layout working with Vue3 adapter and dynamic imports like this:

```ts
import { createApp, h } from 'vue';
// @ts-ignore
import { App, plugin } from '@inertiajs/inertia-vue3';

import TheLayout from '../views/Layouts/TheLayout.vue';
const el: any = document.getElementById('app');

createApp({
    render: () =>
        h(App, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: async (name: string) => {
                const component: any = (
                    await import(`../views/Pages/${name}.vue`)
                ).default;

                return component.layout === undefined
                    ? Object.assign({}, component, { layout: TheLayout })
                    : component;
            }
        })
})
    .use(plugin)
    .mount(el);
```

**Comment by nielsbauman** [comment] 2021-03-23 14:04
I came across this PR where someone proposed an alternative way to do this (which actually works and is not too much additional effort): https://github.com/inertiajs/inertia/pull/183.

**Comment by juanparati** [comment] 2021-03-25 10:29
@nielsbauman : The solution proposed by TheDoctor0 solves the issue persist layouts however it doens't resolve the poblem with the automatic passed properties.

**Comment by nielsbauman** [comment] 2021-03-25 10:47
@juanparati Ah right, that's true. Perhaps this issue should be renamed or a different issue should be created? The current title and description of this issue don't exactly represent the problem with automatically passed properties.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 2
