### ISSUE TITLE
Inertia navigation 'fails' silently for pages that contain JS errors

### ISSUE THREAD

**Issue by claudiodekker** [inertiajs/inertia#710] opened 2021-06-02 12:28 UTC
### Versions:

- `@inertiajs/inertia` version: 0.9.1
- Any adapter (although identified on the Vue 3 one)

### Describe the problem:

When redirecting to (or simply loading) a Page component that crashes due to javascript errors, the page will silently fail to load, and the previous/original page will remain visible. Of course, you do get to see the console error from the 'target' page component, but Inertia itself will act as-if nothing went wrong.

**When this occurs, instead of failing, it would be great if we could display a console warning, indicating the user of this.**

The goal here is to prevent the user from temporarily 'ignoring' the obvious user error while they attempt to get Inertia to render the next page (as that's the first action they took, order-of-execution wise)

### Steps to reproduce:

1. Create two pages. One that loads just fine, and another that contains javascript that 'crashes' (e.g. require a non-existent component in the `mount` method if you're using Vue to do this)
2. `Inertia::render` the first page
3. Visit the second page using one of Inertia's visitation methods: `<inertia-link>`, `Inertia.visit` / `$inertia.get` etc.
4. Observe the console error from the failed require, as well as how the page did not update.

If anyone needs more information, feel free to reply to this issue.

**Comment by belguinan** [comment] 2021-12-22 17:12
I just found the issue. I removed **Link** component from the navigation as a work around.
Error returned from the console `Unhandled error during execution of scheduler flush. This is likely a Vue internals bug`
...
 `dashboard.js?id=672fd15b45ac49d726aa:20102 Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

It's probably an error in the event emitted by the parent components

**Comment by belguinan** [comment] 2021-12-24 21:03
The issue is related to **teleport**. I had to edit where a modal was teleporting. I hope this is helpful.

**Comment by matiaslagoevia** [comment] 2023-03-18 00:20
Hello, I'd like to tackle this issue if possible. Thanks!

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: good first issue, core
