### ISSUE TITLE
Bug between Inertia and Axios

### ISSUE THREAD

**Issue by Benoit1980** [inertiajs/inertia#640] opened 2021-04-20 20:04 UTC
### Versions:
     "inertiajs/inertia-laravel": "^0.3.5",
        "@inertiajs/inertia": "^0.8.4",
        "@inertiajs/inertia-vue3": "^0.3.5",
        "@inertiajs/progress": "^0.2.4",
### Describe the problem:

Axios simple get request returns:
`{ "cookies": {}, "transferStats": {} }`

### Steps to reproduce:

```
    axios.get('/test-connection')
                .then(response => {
                    this.TestConnection = response.data;
                })
```

Response is a json object from Laravel:

`return response()->json($data);`

The response is always returning `{ "cookies": {}, "transferStats": {} }`, I am not the only people with this issue, others on Laracast experience this too.

Tried everything I could, I cannot get a normal response in Json with Axios when Intertia is installed.

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
