### ISSUE TITLE
STATUS NOT FOUND - SSR on LOCALHOST

### ISSUE THREAD

**Issue by essential-writer-codebase** [inertiajs/inertia#1601] opened 2023-06-26 10:29 UTC
{"status":"NOT_FOUND","timestamp":1687784180271} error if you run php artisan inertia: start-ssr on localhost

My configs:

vite.config.js
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import react from "@vitejs/plugin-react";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.scss',
                'resources/js/app.jsx',
            ],
            ssr: 'resources/js/ssr.jsx',
            refresh: true,
        }),
        react(),
    ],
});

app.jsx
import { createInertiaApp } from '@inertiajs/react'
import { hydrateRoot } from 'react-dom/client'

createInertiaApp({
    resolve: name => {
        const pages = import.meta.glob('./Pages/**/*.jsx', { eager: true })
        return pages[`./Pages/${name}.jsx`]
    },
    setup({ el, App, props }) {
         hydrateRoot(el, <App {...props} />)
    },
})

ssr.jsx
import { createInertiaApp } from '@inertiajs/react'
import createServer from '@inertiajs/react/server'
import ReactDOMServer from 'react-dom/server'

createServer(page =>
    createInertiaApp({
        page,
        render: ReactDOMServer.renderToString,
        resolve: name => {
            const pages = import.meta.glob('./Pages/**/*.jsx', { eager: true })
            return pages[`./Pages/${name}.jsx`]
        },
        setup: ({ App, props }) => <App {...props} />,
    }),
)

**Comment by craigrileyuk** [comment] 2023-06-28 10:44
Inertia checks the following for a valid SSR entry file:

```php
    config('inertia.ssr.bundle'),
    base_path('bootstrap/ssr/ssr.mjs'),
    base_path('bootstrap/ssr/ssr.js'),
    public_path('js/ssr.js')
```

So if you check where your ssr file is being built and then use `inertia->ssr->bundle` in the config directory to set it manually if it's not one of the defaults above.

**Comment by essential-writer-codebase** [comment] 2023-06-29 20:49
yea i iried this command:
php artisan vendor:publish --provider="Inertia\ServiceProvider"
and uncommented Bundle
 'bundle' => base_path('bootstrap/ssr/ssr.mjs'),

But it did not help, in theory I expect a redirect from port 13714 to APP_URL in .env file

**Comment by essential-writer-codebase** [comment] 2023-06-29 20:52
Maybe needed create Nginx with proxy pass for localhost?

localhost:13714 must work independently but it also doesn't work and throws that error

**Comment by essential-writer-codebase** [comment] 2023-06-29 20:53
> Inertia checks the following for a valid SSR entry file:
> 
> ```
>     config('inertia.ssr.bundle'),
>     base_path('bootstrap/ssr/ssr.mjs'),
>     base_path('bootstrap/ssr/ssr.js'),
>     public_path('js/ssr.js')
> ```
> 
> So if you check where your ssr file is being **_built_** and then use `inertia->ssr->bundle` in the config directory to set it manually if it's not one of the defaults above.

Where exactly should this be added?

**Comment by essential-writer-codebase** [comment] 2023-06-29 21:19
> Inertia checks the following for a valid SSR entry file:
> 
> ```
>     config('inertia.ssr.bundle'),
>     base_path('bootstrap/ssr/ssr.mjs'),
>     base_path('bootstrap/ssr/ssr.js'),
>     public_path('js/ssr.js')
> ```
> 
> So if you check where your ssr file is being **_built_** and then use `inertia->ssr->bundle` in the config directory to set it manually if it's not one of the defaults above.

There are differences in jsx extension. I Tried but its don't help me.

![image](https://github.com/inertiajs/inertia/assets/11135501/d229e88d-01a8-4669-bf0b-b0d8c66ad9f9)

**Comment by AramDonyaee** [comment] 2023-07-24 11:15
Hi @essential-writer-codebase. I was wondering if you have found a workaround for this issue? I am experiencing the same problem.

**Comment by reinink** [comment] 2023-07-28 00:56
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 00:56 UTC
Labels: react

**Comment by FurrukhJamal** [comment] 2023-10-12 21:28
anyone found a work around as yet?

**Comment by JoaoHamerski** [comment] 2024-08-17 19:32
If anyone else stepped into this:

This is intended behavior, when you start 
```bash
php artisan inertia:start-ssr
```

Inertia will output a message like this:
> Starting SSR server on port 13714...

This is not the port your application should be accessed from, you should access via the default port (usually 8000), this is the port inertia internal process uses to render the HTML, and then serve it to the Laravel application.

To test if your SSR is working properly, type something inside a Vue component, like:  
```vue
<template>
  HELLO WORLD
</template>
```
Then, run `npm run build` to run Inertia's SSR build files.

After that stop and start the command `php artisan inertia:start-ssr` again.

Open you app (localhost:8000), press CTRL + U to open its source code and CTRL + F to find for words, search for "HELLO WORLD", if you find it, it's because inertia is properly rendering the HTML via server-side. Or you can disable Javascript in your browser, if the pages render the "HELLO WORLD" content from inside your Vue file, it's also working.
