### ISSUE TITLE
Server ports in combination with Laravel pagination lost

### ISSUE THREAD

**Issue by NickSdot** [inertiajs/inertia#811] opened 2021-07-15 08:39 UTC
# Versions

**package.json**
- `@inertiajs/inertia` version: 0.9.2 / 0.0.10
- `@inertiajs/inertia-vue` version: 0.6.2 / 0.7.1

**composer.json**
- `inertiajs/inertia-laravel` version 0.4.2
- `laravel/framework` version 8.40 / 8.50

# Describe the problem

There might be is a problem with inertia-link requests to the Laravel pagination. The issue for sure **depends on the stack and server**. Please don't stop reading here! 😃 I tried for two days to work around it in several ways, but came to the conclusion that this is most likely an Inertia issue, because for this issue working fixes lead to other problems elsewhere.

### Excpected behavior

- Returned pagination links always should contain the port, if the requesting page url has a port
- XHR requests always should contain the port, if the requesting page url has a port.

### Current behavior

**Case A:**

On page: https://pingcrm.test:3000/organizations?page=1
- Everything is alright on first page load (F5)
- Returned pagination links of XHR requests DO NOT have a port
   Example: https://pingcrm.test/organizations?page=2)
- Second click on pagination after initial page load makes XHR Request WITHOUT port
   Example: https://pingcrm.test/organizations?page=1

**Case B:**

To work around this issue in Webpack/BrowserSync the proxy can be set to `changeOrigin: false` in webpack.mix.js. This is resulting in links with duplicate port `https://pingcrm.test:3000:3000/organizations?page=1`. The duplicate port leads Inertia to crash with the following error.

```js
TypeError: Failed to construct 'URL': Invalid URL
    at Object.h [as mergeDataIntoQueryString] (index.js:1)
    at render (index.js:1)
    at createFunctionalComponent (vue.esm.js:3067)
    at createComponent (vue.esm.js:3240)
    at _createElement (vue.esm.js:3431)
    at createElement (vue.esm.js:3362)
    at vm._c (vue.esm.js:3500)
    at Proxy.render (templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/js/Shared/Layout.vue?vue&type=template&id=6bf30086&:140)
    at VueComponent.Vue._render (vue.esm.js:3554)
    at VueComponent.updateComponent (vue.esm.js:4072)
```

---
For mor infos please check the "Steps to reproduce" section.

### Laravel

Laravel is determiting the current path of the pagination links based on the request. Since the very fist request, the initial page-load, is returning the correct links I assume this _could_ be related to the request made by Inertia afterwards.

```php
\Illuminate\Pagination\PaginationState

class PaginationState
{
    public static function resolveUsing($app)
    {
        //...

        Paginator::currentPathResolver(function () use ($app) {
            return $app['request']->url();
        });

        //...

    }
}
```

Using `$app['request']->url();` here would fix the issue. But then, in contrast to the routing links in the Laravel framework, the response would contain relative URLs instead of the absolute URLs. 

Imho this would not be a big deal, but a) the links are correct on initial page load and b) it could be considered a breaking change. Hence, for now, I am working around the issue by using a custom `currentPathResolver` in the `AppServiceProvider.php`:

```php
        Paginator::currentPathResolver(function () use ($app) {
            return $app['request']->url();
        });
```

Still, I think the main cause for the issue should be fixed. This is why I first report it here to find out whether or not this can be confirmed as an Inertia issue.

# Stack
In my specific case the setup looks as following:

• Inertia
• Laravel
• Vue
• Laravel Valet
• Laravel Mix
• Webpack
• Webpack BrowserSync

Laravel Valet is handling the domain and SSL. The project is served with `npm run watch` trought mix and uses a proxy for BrowserSync. This is my `webpack.mix.js`.

```js
const mix = require('laravel-mix');
const domain = 'pingcrm.test'; // changed URL to match demo repo
const homedir = require('os').homedir();

// The mix script:
mix.browserSync({
    proxy: {
        target: 'https://' + domain,
        // proxyOptions: {
        //     changeOrigin: false, // uncommented, see more infos in demo repo readme.md
        // },
    },
    host: domain,
    open: 'external',
    https: {
        key: homedir + '/.config/valet/Certificates/' + domain + '.key',
        cert: homedir + '/.config/valet/Certificates/' + domain + '.crt',
    },
    notify: false,
})

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */


mix.js('resources/js/app.js', 'public/js')
    .vue()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ])
    .webpackConfig(require('./webpack.config')).sourceMaps();

if (mix.inProduction()) {
    mix.version();
}
```

# Steps to reproduce

Test repo: https://github.com/NickSdot/pingcrm/tree/main

I did setup a test repo based on the PingCRM demo. Kindly check the [edited readme.md ](https://github.com/NickSdot/pingcrm/blob/main/readme.md) for detailed infos and the repo for the source. The repo is basically a 1:1 clone of the PingCRM demo – only 2 changes have been made to match my stack/setup, those are documented in the readme.md.

Alternatively, you can find:

a) The same base repo, but with the latest versions here:
https://github.com/NickSdot/pingcrm/tree/updated-packages

b) The same base repo, but with Vue 3 here (did not fix design stuff):
https://github.com/NickSdot/pingcrm/tree/fork-with-vue-3

# Notes

- The error exists in both, installations with Vue 2 and Vue 3.
- I've tested it with several package versions, including the very latest ones.
- As you can see on the demo repo, I've also tested it outside of my own project to not do any false reports.

I am aware that this also pretty much can be an issue in Laravel itself. Please forgive me that I start with reporting here. 😀

Thanks for your time and the wonderful Inertia!

**Comment by AngosStudio** [comment] 2021-07-22 02:54
Same behavior here =(

**Comment by tahitahi** [comment] 2022-03-01 22:59
Same issue here

**Comment by jakjr** [comment] 2022-05-12 21:38
Same problem.... first pagination load works, after change pages, the urls are without port number. This causes a CORS error.

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: vue 2
