### ISSUE TITLE
Wacher trigger loop on  $inertia.form with preserveState

### ISSUE THREAD

**Issue by jesperbjoernandersen** [inertiajs/inertia#676] opened 2021-05-14 14:41 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-vue` version: 0.5.12

I have a data property with an assigned $inertia form, containing a search attribute.

```vue
search: this.$inertia.form({
    q: null,
})
```

I have my watcher looking for changes on the form attribute, with preserveState on it.

```vue
search: {
    handler: debounce(function() {
        this.search.get('/search', {
            preserveState: true
        });
    }, 150),
    deep: true
}
```

The issue here is that when the preserveState is true, it keeps triggering an input change on the form, meaning it goes into a submit loop..

I tried using the regular inertia visit
```vue
this.$inertia.get(this.route('tasks.index'),
    pickBy(this.form) {
        preserveState: true
    });
```
 and that works fine.

I'm just curious if the behaviour with assigning an inertia form object to an attribute is intended or a bug.

**Comment by freakzlike** [comment] 2021-05-22 08:39
You should only watch what is really necessary and either use a computed
```js
computed: {
  searchQuery () {
    return this.search.q
  }
},
watch: {
  searchQuery () {
    // handle change
  }
}
```

or watch only the specific attribute
```js
watch: {
  'search.q' () {
    // handle change
  }
}
```

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: vue 2
