### ISSUE TITLE
Problem with interacting "input" tag after history.back()

### ISSUE THREAD

**Issue by Freezon** [inertiajs/inertia#970] opened 2021-11-15 11:52 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: 0.7.2
- `vue` version: 2.6.14

### Describe the problem:

When moving through the inertia module to another page, and then when returning, it is impossible to interact with the input

### Steps to reproduce:
Routing over ZiggyVue

Steps: 
1. Open /test page
2. Fill input in TestPage, more then 10 charecters (the condition may be different, this is for example)
3. Submit form
4. Click back button, and what kind of button it will be no difference, the reaction is the same, even if you press the back button in the browser
5. Try to delete/correct value in input field

TestPage.vue
```vue
<template>
   <form @submit.prevent="send">
     <input v-model="value">
     <div v-if="'value' in errors">{{errors.value}}</div>
     <button type="submit">send</button>
   </form>
</template>

<script>
export default {
  name: "TestPage",
  data() {
    return {
      value: '',
      errors: {},
    }
  },
  methods: {
    send(){
      this.$inertia.post(route('test-and-redirect', {value: this.value}), {}, {
        onError: (errors) => this.errors = errors,
      })
    }
  }
}
</script>
```

ConfirmedPage.vue
```vue
<template>
   <div>
     <span>{{value}}<span>
     <Link :href="route('test')">Back variant 1</Link>
     <a @click="back">Back variant 2</Link>
   </div>
</template>

<script>
export default {
  name: "ConfirmedPage",
  
  methods: {
    back(){
      history.back();
    }
  }
}
</script>
```

web.php
```php
Route::get('test', function(){ 
  return inertia('TestPage');
})->name('test');

Route::post('test/{value}/check', function($value){
  if(mb_strlen($value) < 10){
    return redirect()->back()->withErrors(['value' => __('Not valid value')]);
  }
  return redirect()->route('test-and-confirm', ['value' => $value]);
})->name('test-and-redirect');

Route::get('test/{value}', function($value){
  return inertia('ConfirmedPage', compact('value'))
})->name('test-and-confirm');
```

**Comment by Freezon** [comment] 2021-11-16 05:42
This heppens, if on ConfirmedPage has `vue-range-component@1.0.3`. This package don`t unbind events on keyup/keydown, mouse*, be cearfully!

**Comment by claudiodekker** [comment] 2021-12-02 14:02
Hey @Freezon,

Do you mean that this is an issue when using the `vue-range-component` in combination with Inertia? Because if so, this honestly sounds like an issue with that package rather than an issue with Inertia.

Thanks!

**Comment by reinink** [comment] 2023-07-28 01:56
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:56 UTC
Labels: vue 2
