### ISSUE TITLE
Any time SSR throws an error, the last segment of the url path is changed to /undefined, breaking refresh

### ISSUE THREAD

**Issue by jakedowns** [inertiajs/inertia#1148] opened 2022-03-30 18:38 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: 0.7.2

### Describe the problem:

Any time my SSR fails, the frontend app changes the url of the current page from /some/erroring/page to /some/erroring/undefined
Which, leads to a minor annoyance when debugging, cause then I have to change the URL (most times, back button is not enabled to get _back_ to erroring route)

### Steps to reproduce:

with a Laravel SSR Setup, throw a render-breaking exception in your boot-server equivalent file
Check the URL bar when trying to load the page, should see the last segment of the pathname changed to `undefined`

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed as completed by reinink** 2023-07-28 01:53 UTC
