### ISSUE TITLE
method delete is not supported error

### ISSUE THREAD

**Issue by AndrGutierrez** [inertiajs/inertia#509] opened 2021-02-19 13:23 UTC
### Versions:

- `@inertiajs/inertia` version: 6.14.11
- `@inertiajs/inertia-react` version: 6.14.11

### Describe the problem:

When I use Inertia.delete on react, data is deleted as expected, but shows an error that says DELETE method is not supported. supported methods: GET, HEAD, POST

I have to reload the page to see the changes (I guess it is because of the redirect to a route that uses get method

### Steps to reproduce:

create `Route::resource` routes like this

`Auth::routes(); 
Route::resource('users', 'App\Http\Controllers\Backend\PostController')->middleware('auth');`

create destroy method

`use App\Models\Post; 
class UserController extends Controller
{
    public function destroy(User $user){
        $user->delete();
        $return back();
    }
}`

in any React component in a route that uses get, head or post method do this:
`Inertia.delete("/users/" + ${user.id})`

still not working :[

_Originally posted by @AndrGutierrez in https://github.com/inertiajs/inertia/issues/497#issuecomment-782062530_

**Comment by claudiodekker** [comment] 2021-02-19 15:06
Closing - Duplicate of #497

I understand that your issue may still persist, but in that case just commenting on the issue (like you did [here](https://github.com/inertiajs/inertia/issues/497#issuecomment-782062530)) would've been sufficient, as it keeps discussion around this problem centralized and allows us to not have to re-read the original post or thread.

Furthermore, the fact that we closed #497 also does not end the conversation or mean that we won't try to help you. Instead, it means that _as of right now_ we believe that the library is working as intended. If you're able to clearly demonstrate otherwise, we can always decide to re-open that issue. The reason the process works like this, is because it allows us to track actual issues vs. perceived issues, which in turn allows us to measure what thing require urgent attention.

**Closed by claudiodekker** 2021-02-19 15:06 UTC
