### ISSUE TITLE
Undefined X-Inertia-Partial-Component when manual visit on page load after a browser refresh

### ISSUE THREAD

**Issue by yfrommelt** [inertiajs/inertia#1363] opened 2022-12-20 10:04 UTC
### Versions:

- `@inertiajs/core` version: 0.11.1
- `@inertiajs/react` version: 0.8.1

### Describe the problem:

On first page load, Laravel Inertia props are available in the app div data attribute, but they aren't reconciled with the router page data.
I'm doing a manual visit on page load to acquire more data from the back, depending on viewport. The `X-Inertia-Partial-Component` is `undefined`

<img width="304" alt="image" src="https://user-images.githubusercontent.com/44576727/208639278-85e99b38-9dd8-4fa0-95a9-c6d3cf83f4cb.png">
Note : main is coming from the lib, `*-Fix` is set on the manual visit using `usePage().component`

### Steps to reproduce:

Refresh a page with a `Inertia::lazy` data. With React make a manual visit on a `useEffect(()=>{}, [])`. Headers will not be set correctly.
But if we do the same code, coming from a different inertia page. The component will have a correct value.

**Comment by reinink** [comment] 2023-07-28 01:49
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:49 UTC
