### ISSUE TITLE
inertia form not properly updating value of checkbox input with v-model

### ISSUE THREAD

**Issue by liam-ot** [inertiajs/inertia#647] opened 2021-04-23 23:27 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-vue` version: 0.5.5

### Describe the problem:

inertia form not properly updating value of checkbox input with v-model

```
<template>
    <!-- Root div -->
    <div>
        <FormInput v-model="form.subscribe" type="checkbox" :error='form.errors.subscribe' label='Email me news 
         and special offers'/>
    </div>
    <!-- End Root div -->
</template>

<script>
import FormInput from '@/Shared/FormInput'

export default {
    data () {
        return {
            form: this.$inertia.form({
                subsrcibe: false,
            }),
        }
    },
}
</script>
```

when page loads vue dev tools shows `subscribe` as being false as that is the default value, once the checkbox is clicked the `form.subscribe` value is updated not to true but to an empty string, subsequent clicking of the checkbox does nothing and `form.subscribe` stays as an empty string

![image](https://user-images.githubusercontent.com/48032728/115938629-605a8b00-a469-11eb-807f-2c8b817f87de.png)

![image](https://user-images.githubusercontent.com/48032728/115938644-6f413d80-a469-11eb-9616-8981a1d80050.png)

### Steps to reproduce:
**Page**

```
<template>
    <!-- Root div -->
    <div>
        <FormInput v-model="form.subscribe" type="checkbox" :error='form.errors.subscribe' label='Email me news 
         and special offers'/>
    </div>
    <!-- End Root div -->
</template>

<script>
import FormInput from '@/Shared/FormInput'

export default {
    data () {
        return {
            form: this.$inertia.form({
                subsrcibe: false,
            }),
        }
    },
}
</script>
```

**FormInput component**

```
<template>
  <div>
    <div  class="py-3">
      <label v-if="label" class="font-sans font-semibold text-gray-700 tracking-tight leading-tight" :for="id">{{ label }}:</label>
      <input :id="id" ref="input" v-bind="$attrs" class="ml-2 border-gray-300 border-2 text-black focus:border-gray-300 focus:ring-black" :class="{ error: error }" :type="type" :value="value" @input="$emit('input', $event.target.value)" />
      <div v-if="error" class="text-red-500 text-sm font-semibold font-mono">{{ error }}</div>
    </div>
  </div>
</template>

<script>
export default {
  inheritAttrs: false,
  props: {
    id: {
      type: String,
      default() {
        return `text-input-${this._uid}`
      },
    },
    type: {
      type: String,
      default: 'text',
    },
    value: String,
    label: String,
    error: String,
  },
  methods: {
    focus() {
      this.$refs.input.focus()
    },
    select() {
      this.$refs.input.select()
    },
    setSelectionRange(start, end) {
      this.$refs.input.setSelectionRange(start, end)
    },
  },
}
</script>
```

**Comment by reinink** [comment] 2021-04-24 13:30
Please update to the latest version of [inertia-vue](https://inertiajs.com/releases#inertia-vue) and let me know if that fixes this problem. There has been a ton of form helper related bug fixes since 0.5.5. 👍

**Comment by liam-ot** [comment] 2021-04-26 20:58
oddly enough that resulted in a relatively weirder issue

now when the page loads as before there is a subscribe attr on the form object set to false but now upon selecting the checkbox it adds yet another subscribe attr with the value of an empty string and subsequent clicks of the checkbox result in no change as before 


![image](https://user-images.githubusercontent.com/48032728/116149721-7c03a280-a6b0-11eb-94cf-72c8ffa61d5f.png)

**Comment by liam-ot** [comment] 2021-04-27 00:57
```
return Object
        .keys(data)
        .reduce((carry, key) => {
          carry[key] = this[key]
          return carry
        }, {})
```

not sure, does this have anything to do with why the false is being literally interpreted from a false to an empty string

**Comment by liam-ot** [comment] 2021-04-27 14:21
https://github.com/liam-ot/min_repo

i believe that should be the min reproducible code

**Comment by liam-ot** [comment] 2021-04-28 13:19
sorry, that repo was inadequate, it should now be the proper set up to reproduce it

**Comment by liam-ot** [comment] 2021-04-29 13:31
any updates? is that repo helpful or did i forget to provide something necessary?

**Comment by liam-ot** [comment] 2021-05-02 16:23
hello, hope you're having a nice weekend

any updates on this bug yet?

**Comment by reinink** [comment] 2021-05-03 19:13
@liam-ot Thanks for providing the repo, but it could take us a while before we get into this to figure it out. We work on this project as we have time.

**Comment by liam-ot** [comment] 2021-05-05 15:18
okay, thanks for the update please keep this issue updated as things progress

you all do great work and it's very appreciated

**Comment by liam-ot** [comment] 2021-05-13 20:21
any progress so far?

**Comment by liam-ot** [comment] 2021-06-14 08:11
i hope someone has found time to address this bug?

**Comment by reinink** [comment] 2021-06-14 11:43
Is it because you have "subscribe" spelt incorrectly here?

```js
form: this.$inertia.form({
    subsrcibe: false,
}),
```

It's spelt as "subsrcibe", not "subscribe".

**Comment by inlogicstudio** [comment] 2021-12-03 14:36
I think this issue needs to be closed.

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: vue 2
