### ISSUE TITLE
Wrong target for anchor links (position-dependent)

### ISSUE THREAD

**Issue by Muetze42** [inertiajs/inertia#1480] opened 2023-03-03 14:37 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.2

### Describe the problem:

When you click on an anchor link again, the screen scrolls up.  
(But this happens only with html scolling smooth)

### Steps to reproduce:

- Click on an Anchor-Link
- Keep on the Anchor-Target
- Click on the same Anchor-Link again

https://user-images.githubusercontent.com/26193232/222747517-d4108171-be6e-46ad-840f-ec67b98414ee.mp4

---

Link to example page: https://sad-feynman.167-235-9-201.plesk.page/helpers-collection/v1/helpers

**Comment by reinink** [comment] 2023-07-28 01:47
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:47 UTC
