### ISSUE TITLE
Inertia-Vue3 assumes Options API is used when registering Remember mixin

### ISSUE THREAD

**Issue by obennaci** [inertiajs/inertia#458] opened 2021-01-25 09:26 UTC
### Versions:

- `@inertiajs/inertia` version: #.#.#
- `@inertiajs/inertia-vue3` version: #.#.#

### Describe the problem:
The `inertia-vue3` plugin registers the `remember` mixin.

But mixins aren't available when strictly using Composition API (`__VUE_OPTIONS_API__` set to `false`) so Vue keeps throwing such warning `[Vue warn]: Mixins are only available in builds supporting Options API`

### Steps to reproduce:
- Typical setup for Inertia and Vue
- Disable Options API using `__VUE_OPTIONS_API__`

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: bug, investigate, vue 3
