### ISSUE TITLE
Head component (title) does not work as expected if already in HTML

### ISSUE THREAD

**Issue by pedzed** [inertiajs/inertia#978] opened 2021-11-25 10:16 UTC
### Versions:

```json
"@inertiajs/inertia": "^0.10.1",
"@inertiajs/inertia-vue3": "^0.5.2",
```

### Describe the problem:

I am using Laravel with Inertia and Vue3. The `Head` component as described in https://inertiajs.com/title-and-meta does not work as expected if `<head>` is already present in the HTML.

More specifically, the `<title>` does not override. Removing the conflicting `<title>` in the HTML solves the problem, but this caveat is not documented nor does it get logged to the console to give a heads up, leaving the developer confused as to why it does not work. (I realized this after reading the dated https://www.martyfriedel.com/blog/getting-started-with-inertia-head)

### Steps to reproduce:

Have the `<head>` in the master layout:
```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>{{ config('app.name') }}</title><!-- The culprit -->
    </head>
    <body>
        @inertia
    </body>
</html>
```

Add the `Head` component:
```vue
// Pages/Home.vue
<template>
    <Head title="Home" />
</template>

<script>
import { Head } from '@inertiajs/inertia-vue3';

export default {
    components: {
        Head,
    },
};
</script>
```

### Solution

What I propose is to do three things to fix this:
1. Override the `<title>` tag (as it makes most sense, considering the frontend gets primarily written with JavaScript)
2. Document the possible conflict
3. Log warning to console

**Comment by ajnsn** [comment] 2021-11-27 16:34
Hey @pedzed 
for me it would be more unexpected **if** Inertia would remove or alter something coming from my Blade template. 

I think the beaviour is by design, the `<title>`-tag is also not [included in the setup section](https://inertiajs.com/server-side-setup).  It could be mention in the documentation for Title & meta somewhere,  I agree.

**Comment by ciamarro** [comment] 2021-11-29 21:51
This may be what you are looking for in your layout
`<title inertia>{{ config('app.name') }}</title>`

**Comment by pedzed** [comment] 2021-11-30 07:46
@ciamarro I didn't know that was a thing, but no, I'm fine with removing it altogether and use JavaScript (as Inertia does anyway). The problem is that I had to search the internet as to why it didn't work.

**Comment by claudiodekker** [comment] 2021-12-01 17:56
Hey @pedzed,

@ciamarro's fix is actually what I would recommend doing. By adding the `inertia` attribute to a `<head>` tag, you're essentially letting Inertia know that it's okay to 'manage' that tag, regardless of it's current value.

In either case, now that this issue has a definitive answer, I'll be closing this issue :)

Thanks for using Inertia! 👍

**Closed by claudiodekker** 2021-12-01 17:56 UTC

**Comment by irfanahmad7272** [comment] 2023-01-29 21:15
I am still facing this issue in vue2 :( inertia does not even replace but create a duplicate <head> tag in component. I've tried to insert [inertia](#) in my blade <head> tag as well, but still no charm :(

**Comment by ciamarro** [comment] 2023-01-29 22:19
Is it like so?
` <title inertia>{{ config('app.name', 'My Inertia App') }}</title>`

**Comment by irfanahmad7272** [comment] 2023-01-29 22:22
Yes, I tried both, <title inertia> and <head inertia> but both didn't work for me sadly.

**Comment by irfanahmad7272** [comment] 2023-01-29 22:24
So, alternate way for me to use `Vuemeta` plugin

**Comment by ciamarro** [comment] 2023-01-29 22:24
Hmm, ok. Is there some code I can have a peek at?

**Comment by irfanahmad7272** [comment] 2023-01-29 22:29
`<Head>
            <title>
                {{
                    current_page !== undefined && current_page.title
                        ? current_page.title
                        : "Default Page Title"
                }}
            </title>
            <meta
                v-if="current_page !== undefined && current_page.description"
                head-key="description"
                name="description"
                :content="current_page.description"
            />
        </Head>`

**Comment by ciamarro** [comment] 2023-01-29 22:33
Just to be clear, in your app.blade.php (layout) you have 
`<title inertia>`
In your <head> component, the one you import (import { Head as InertiaHead } from "@inertiajs/inertia-vue3") 
I  don't think you need the inertia attribute
```
<inertia-head>
        <title>{{ title }}</title>
```

**Comment by irfanahmad7272** [comment] 2023-01-29 22:35
I am using vue2, not vue3.

**Comment by irfanahmad7272** [comment] 2023-01-29 22:36
and yes, I tried in my blade file like this `<title inertia> `
