### ISSUE TITLE
Vue 3 example on Validation docs page uses Vue 2 code

### ISSUE THREAD

**Issue by richeklein** [inertiajs/inertia#726] opened 2021-06-05 13:48 UTC
### Steps to reproduce:
Open the [Validation docs](https://inertiajs.com/validation) and select the Vue 3 example.

_Sorry if this issue is misplaced or if the options API was used intentionally._

**Comment by claudiodekker** [comment] 2022-01-04 19:33
Hey @richeklein,

Thanks for letting us know, I think we did this intentionally at the time to show the similarities/ease-of-migration between Vue 2 and Vue 3. If you're aware of the Options API and prefer that, then using Inertia with that should not be an issue, as we do have functionality for it.

In either case, I'll let @reinink confirm this one as I'm not 100% sure.

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: investigate, vue 3
