### ISSUE TITLE
Posting a request with a file produces error: Failed to construct 'URL': Invalid URL 

### ISSUE THREAD

**Issue by EfosaSO** [inertiajs/inertia#890] opened 2021-09-02 18:12 UTC
### Versions:

- `@inertiajs/inertia` version: ^0.10.1
- `@inertiajs/inertia-react` version: ^0.7.1

### Describe the problem:

When posting a request with the `useForm` helper that has a file, the browser reports an error as seen here:
```
    index.js:1 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at p (index.js:1)
    at e.n.visit (index.js:1)
    at e.n.post (index.js:1)
    at eval (index.js:1)
    at post (index.js:1)
    at handleSubmit (Edit.jsx:95)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070)
```
When I remove the file, everything posts fine.

### Steps to reproduce:

Use the `useForm` helper hook to post a request with a file.

**Comment by devAlnadjom** [comment] 2021-09-09 06:02
Facing the same issue. Is there any way to deal with this?

**Comment by ImFranQ** [comment] 2021-09-15 04:08
is there any code that can be seen.

**Comment by wntechs** [comment] 2021-09-15 11:13
The issue still exist but I have come up with following solution -

change `post(route('users.update', user.id));` to `post(route('users.update', user.id).url());`

**Comment by ImFranQ** [comment] 2021-09-15 19:58
try to send the url by controller

```
public function edit(User $user){
    return Inertia::render("User/Update", [
        'updateUrl' => route("users.update", $user)
    ]);
}
```

view

```
export default ({ updateUrl }) => {
    const {post} = useForm()

    const submitHandler = () => {
        post(updateUrl)
    }
}
```

**Comment by claudiodekker** [comment] 2021-12-01 18:58
Closing this, as it appears to be a duplicate of https://github.com/inertiajs/inertia/issues/782

While we still use Ziggy's route helper in the PingCRM demo app, we intend to replace this with template strings or hardcoded URLs in a future build. In part to work around issues such as these, but also to reduce the initial page render and to make our demo application more straight forward.

Personally, I consider the following to be good alternatives:

```js
`/users/${user->id}/posts`
```

or something like

```js
"/users/:user/posts".replace(":user", user.id)
```

**Closed by claudiodekker** 2021-12-01 18:58 UTC
Labels: react
