### ISSUE TITLE
Going back through history changes $page.props before component hooks are called

### ISSUE THREAD

**Issue by jsandfordhughes** [inertiajs/inertia#519] opened 2021-02-25 09:26 UTC
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:

When navigating back through history using the back button in the browser the `$page.props` change back to the previous page's props before the component you are navigating away from has called its `beforeDestroy()` and `destroyed()` hooks. If you are, like me doing something in those hooks that requires something in the `$page.props` for that current component it then fails as its not available anymore.

### Steps to reproduce:

Create 2 page components with different data passed through from the controller. 
In the `beforeDestory()` hook of the second component `console.log()` the `$page.props`.
Navigate to the first component and then navigate to the second component. 
Now press the back button of the browser and inspect the console log for the $page.props object and you will see the data from component 2 is missing.

**Comment by reinink** [comment] 2023-07-28 01:59
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:59 UTC
Labels: vue 2
