### ISSUE TITLE
jest page tests fail after update to 1.0.0 (or newer)

### ISSUE THREAD

**Issue by madpilot78** [inertiajs/inertia#1405] opened 2023-01-19 19:00 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.0 (or newer, tested up to 1.0.2)

### Describe the problem:

After updating a project to `@inertiajs/vue3` v 1.0.0 page tests start to show unexpected failures. The pages in the browser work fine though.

The issues are:

#### `Link` element

It fails to render in tests. Adding `import 'vue'` is a workaround that makes it work.

#### `useForm` fails to read its own properties

This is similar to issue #959. But again shows up only in testing, everything looks fine in the browser.

The error I get from jest is:

```
TypeError: Cannot read properties of undefined (reading 'field')
```

### Steps to reproduce:

I created a demo repo to show the issue: [madpilot78/inertia-test](https://github.com/madpilot78/inertia-test)

The very basic pages there work as expected in the browser, when served locally, but the tests fail.

**Comment by madpilot78** [comment] 2023-01-27 18:30
After some further testing I noticed that both issues are "fixed" if I add `import 'vue'` to the vue page setup.

**Comment by madpilot78** [comment] 2023-02-14 08:41
I tested with the latest v1.0.1 and I can confirm this issue is still happening.

**Comment by madpilot78** [comment] 2023-03-15 17:27
Hi,

This one keeps not working as the demo repo I created shows.

Tests are important and should work and be easy to implement.

How can I draw attention to this issue? Maybe I'm doing my tests wrong, then some indication on how to fix them would be useful.

Thanks for any feedback!

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
