### ISSUE TITLE
NPM fails to install with React version ^18.0.0

### ISSUE THREAD

**Issue by mindrage** [inertiajs/inertia#1187] opened 2022-05-27 07:08 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-react` version: 0.8.0

### Describe the problem:

npm fails to install inertia.js with react version ^18.0

### Steps to reproduce:

in dependencies:
```json
    "dependencies": {
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-react": "^0.8.0",
        "@types/react": "^18.0.9",
        "react": "^18.0.0",
        "react-dom": "^18.0.0"
    }
```

Then try to run `npm install`

Solution is probobally to add, within inertia-js/intertia-react/package.json, 
`|| ^18.0.0` for the react version.

**Comment by SuperDJ** [comment] 2022-05-27 19:26
Possible similar issue https://github.com/inertiajs/inertia/issues/1152 and related PR https://github.com/inertiajs/inertia/pull/1159

**Comment by TomKalina** [comment] 2022-08-02 08:16
I have the same problem. We are waiting for the release of `inertia-react` which will solve it.

**Comment by reinink** [comment] 2023-07-28 01:52
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:52 UTC
Labels: react
