### ISSUE TITLE
Server-Side Rendering not working if you enable Client side hydration

### ISSUE THREAD

**Issue by connecteev** [inertiajs/inertia#1584] opened 2023-06-05 00:35 UTC
### Discussed in https://github.com/inertiajs/inertia/discussions/1583

<div type='discussions-op-text'>

<sup>Originally posted by **connecteev** June  4, 2023</sup>
Following the guide here https://inertiajs.com/server-side-rendering , I have Server-Side Rendering working with Laravel and Inertia + Vue. 

However, when I enable `Client side hydration` per the instructions above, my app breaks. I see one (often BOTH) of the following:
- the content is duplicated in the browser on a hard refresh, and
- warnings in console, like below

```
app.js:103 [Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <Layout errors= {} auth= {user: {…}} users= {current_page: 6, data: Array(10), first_page_url: 'http://127.0.0.1:8000/users?page=1', from: 51, last_page: 15, …} > 
  at <Inertia initialPage= {component: 'Users', props: {…}, url: '/users?page=6', version: '1d5096ae5d3c7d87eb0790bfc68dd5d0'} initialComponent= {components: {…}, props: {…}, __hmrId: '7a49e397', __file: '/Users/kunalpunjabi/Code/web/laracasts_build_moder…pps_using_inertia_js/resources/js/Pages/Users.vue', render: ƒ, …} resolveComponent=fn<r>  ... > 
  at <App>
```

I have followed the guide to a tee. Copying my app.js and ssr.js below, I am hoping the creators of Inertia can clarify what in the world is wrong here.

## app.js:
```
import '../css/app.css';

import { createSSRApp, h } from 'vue'
import { createInertiaApp, Head } from '@inertiajs/vue3'
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers'; // resolvePageComponent needed to enable code-splitting (or lazy-loading) using Vite, see comment https://laracasts.com/series/build-modern-laravel-apps-using-inertia-js/episodes/14?reply=21929
import Layout from './Shared/Layout.vue'

let enableCodeSplitting = true
const appName = 'MyInertiaApp';

createInertiaApp({
  title: title => `${title} - ${appName}`,

  // If using Vite instead of Webpack / Laravel Mix, the resolve function may look something like this
  resolve: (name) => enableCodeSplitting ?

    // Enable code-splitting: Using Async-Await format
    (async function() {
      let page = await resolvePageComponent(
        `./Pages/${name}.vue`,
        import.meta.glob('./Pages/**/*.vue', { eager: false })
      );
      if (!page.default.layout) {
        page.default.layout = Layout
      }
      return page;
    })()

    :

    // Disable code-splitting / Enable eager-loading (opposite of lazy-loading / code-splitting)
    (function() {
      const pages = import.meta.glob('./Pages/**/*.vue', { eager: true })
      let page = pages[`./Pages/${name}.vue`]

      if (!page.default.layout) {
        page.default.layout = Layout
      }
      return page
    })(),

  setup({ el, App, props, plugin }) {
    createSSRApp({ render: () => h(App, props) })
      .use(plugin)
      .component('Head', Head)
      .mount(el)
  },
})
```

## ssr.js:
```
import '../css/app.css';

import { createSSRApp, h } from 'vue'
import { renderToString } from '@vue/server-renderer'
import { createInertiaApp, Head } from '@inertiajs/vue3'
import createServer from '@inertiajs/vue3/server'
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import Layout from './Shared/Layout.vue'

let enableCodeSplitting = true
const appName = 'MyInertiaApp';

createServer(page =>
  createInertiaApp({
    page,
    render: renderToString,
    title: (title) => `${title} - ${appName}`,

    // If using Vite instead of Webpack / Laravel Mix, the resolve function may look something like this
    resolve: (name) => enableCodeSplitting ?

      // Enable code-splitting: Using Async-Await format
      (async function() {
        let page = await resolvePageComponent(
          `./Pages/${name}.vue`,
          import.meta.glob('./Pages/**/*.vue', { eager: false })
        );
        if (!page.default.layout) {
          page.default.layout = Layout
        }
        return page;
      })()

      :

      // Disable code-splitting / Enable eager-loading (opposite of lazy-loading / code-splitting)
      // Note: When you run `npm run build` (which in turn calls `vite build`), it will output one large JavaScript bundle
      (function() {
        const pages = import.meta.glob('./Pages/**/*.vue', { eager: true })
        let page = pages[`./Pages/${name}.vue`]
        if (!page.default.layout) {
          page.default.layout = Layout
        }
        return page
      })(),

    setup({ App, props, plugin }) {
      return createSSRApp({
        render: () => h(App, props),
      })
      .use(plugin)
      .component('Head', Head)
    },
  }),
);

```

**Comment by craigrileyuk** [comment] 2023-06-09 13:09
Sounds like a problem with your HTML that is being compiled by the SSR renderer. 

A common issue is that SSR doesn’t support self-closing tags (e.g. `<div class=“p-20” />`) even though the client-side Vue engine parses them correctly.

**Comment by connecteev** [comment] 2023-06-09 15:25
Interesting, let me try removing all the self-closing tags from my vue files. 

Is this problem specific to Inertia, or SSR in general? How can I find all the use-cases that are NOT supported by Inertia's SSR?

**Comment by craigrileyuk** [comment] 2023-06-12 22:40
It's not really Inertia's SSR. All Inertia does is pass on configuration to Vue's **renderToString** function and provide an HTTP server. So caveats and gotchas are all down to the Vue engine: https://vuejs.org/guide/scaling-up/ssr.html

**Comment by reinink** [comment] 2023-07-28 01:13
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:13 UTC
