### ISSUE TITLE
Problem with accent letter Áäá or Ññ

### ISSUE THREAD

**Issue by yashiroiori** [inertiajs/inertia#1053] opened 2022-01-18 06:05 UTC
### Versions:

- `@inertiajs/inertia` version: ^0.8.2
- `@inertiajs/inertia-vue` version: ^0.5.4

- `@inertiajs/inertia` version: ^0.10.1
- `@inertiajs/inertia-react` version: ^0.7.1

### Describe the problem:
I use both versions in 2 different projects in Laravel 8
When field into database have any letter with accent like: ÁáäÉéë, etc.
But works with separate letter in the name like: Avila áÄÁ but not work like: áÄÁvila

Get error
![image](https://user-images.githubusercontent.com/17031855/149879796-0eca9ece-af47-414d-9dfa-764e94e11629.png)
Database values
![image](https://user-images.githubusercontent.com/17031855/149879833-bdf82cd5-22a5-4bbb-a1eb-d863faa87b16.png)

**Comment by HassanZahirnia** [comment] 2022-01-22 09:39
Hey @yashiroiori 😀
Can you show how and where are you exactly using this column data? Is it in a vue file ? If so can you please show your code ?

**Comment by yashiroiori** [comment] 2022-01-22 09:49
> Hey @yashiroiori 😀 Can you show how and where are you exactly using this column data? Is it in a vue file ? If so can you please show your code ?

The problem become from controller when inertiajs share data, the error is before render a vue component

**Comment by HassanZahirnia** [comment] 2022-01-22 09:59
> The problem become from controller when inertiajs share and try parse the data to send vue/react component
> The column in database are a simple text/varchar

I understand you're trying to pass those data to the frontend, but my question is how are you doing that, and how are you showing/using those data in your client side ?
I just tried passing those data and there were no problems. 

If you provide more context and some code maybe we could find the source of this issue 😄

**Comment by ordago** [comment] 2022-01-23 23:15
![image](https://user-images.githubusercontent.com/6376814/150701855-ccae92d4-9604-44c9-bf8a-705588b305bc.png)

I can't replicate the problem. I have no issues with accents.

        "@inertiajs/inertia": "^0.10.0",
        "@inertiajs/inertia-vue": "^0.7.1",


@yashiroiori , just a hunch, what's the encoding of the text column in the database?

**Comment by reinink** [comment] 2023-07-28 01:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:54 UTC
