### ISSUE TITLE
Head children not rendered in SSR

### ISSUE THREAD

**Issue by kyriakos** [inertiajs/inertia#1467] opened 2023-02-26 17:25 UTC
### Version:

- `@inertiajs/react` version: 1.0.2

### Describe the problem:

Using Head component in page template is not rendered in the server side rendered HTML <head></head> section.  This is problematic because social media sites won't be able to scrape the title and display it correctly when a page is shared; also bad for SEO.

### Steps to reproduce:

The following behavior can also be seen on http://demo.inertiajs.com/

1. Enable SSR build / run server and ensure its running correctly.
2. Make sure there is no <title> element in the base template (in my case app.blade.php)
3. Add a Head component in a page with a <title> child element and gve it a value.
4. Open the page, using devtools verify that there is a <title> tag and has the correct value. (This is correctly added on client side).
5. View page source using ctrl-u, <title> element should exist in header. It's not.

**Comment by rsdrsd** [comment] 2023-04-05 15:17
Is there already a fix for this?

**Comment by reinink** [comment] 2023-07-28 01:47
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:47 UTC
Labels: react
