### ISSUE TITLE
Inertia Link (Vue3) Don't work properly with web workers

### ISSUE THREAD

**Issue by Swe-HimelRana** [inertiajs/inertia#1581] opened 2023-06-04 09:53 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.0
- - `Node` version: 18.16.0
- - `Vite` version: 4.0.0
- - `Laravel` version: 10.10
- - `PHP` version: 8.1

### Description of problem:
If I use use `fetch `or `axios `inside  [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). Inertia Link wait for web worker task completion. (Route shows loading until web workers complete fetching)

But for CPU intensive task like long calculation Inertia Link works perfectly (Route to another page without delay). 

### Steps to reproduce:
```Home.Vue```
```javascript
<template>

<Link href="/settings">Go to Settings </Link>

</template>
<script setup>
import GmailWorker from '../workers/gmailworker.js?worker'
import {Link} from "@inertiajs/vue3";
import {onMounted} from "vue";

const gmailWorker = new GmailWorker()

async function getMailsFromWorker(){
    gmailWorker.postMessage('start')
    gmailWorker.onmessage = (e) => {
        if(e.data.status === "working"){
            console.log("Working....")
        }

        if(e.data.status === "done"){
            console.log("Worker done it's task: ", e.data.info)
        }

        console.log("Worker start command send")

        return true
    }
}

onMounted(() => {
 getMailsFromWorker()
})

</script>
```
```gmailworkers.js```
```javascript
self.onmessage = function async (message) {

    postMessage({status: "working"})
    fetch("/dashboard/api/get?email=tmailaddress%2Brge1og6%40gmail.com")
        .then((response) => response.json())
        .then((json) => {
            postMessage({status: 'done', info: json})
        });
}
```
_Now If I click on `Go to Settings` Link it shows loading until worker send complete response. After that Route to Setting Page. But It shouldn't wait for Worker task._

Now if I do a CPU intensive task in gmailworkers.js

```javascript
 postMessage({status: "working"})
   let sum = 0;
    for(let i=0; i < 10000000000; i++){
    sum += i;
    }
 postMessage({status: 'done', info: sum})
```
_In this case worker task 5-7 seconds but In any time I Click `Go to Settings` Link It's route to Setting page without waiting for works to be completed_

**Can anyone give solution about how to use `fetch/axios` inside worker in Inertia Vue3?**

**Comment by Swe-HimelRana** [comment] 2023-06-04 09:59
@todaycodemaster
@kukac7

**Comment by craigrileyuk** [comment] 2023-06-04 17:59
Did you seriously just ping every single contributor to get an answer to your "issue"? 🤦

**Comment by Swe-HimelRana** [comment] 2023-06-10 20:40
@craigrileyuk But still did not got any solution. It's a issue with inertia Link Component.

**Comment by reinink** [comment] 2023-07-28 01:16
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:16 UTC

**Comment by thecrypticace** [comment] 2023-07-28 01:39
Hey! I noticed that your worker is making a fetch request to an API. Are you, by chance, using `php artisan serve`? If so, the API call could be taking a long time to complete and is effectively pausing the PHP process such that it can take any further requests until that process is complete. This is because it's a single process handling requests one at a time. And if one of those requests takes a significant time to complete it stalls all future requests.

Generally this is not a major problem but when you're interacting with slower APIs this can show up. I'd recommend testing using a more real web server that can handle multiple concurrent requests by using something like Herd, Valet, Homestead, etc…
