### ISSUE TITLE
<i18n-t> error 500 [Codegen node...]

### ISSUE THREAD

**Issue by devstack-be** [inertiajs/inertia#1356] opened 2022-12-05 13:55 UTC
### Version: 

        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "@inertiajs/progress": "^0.2.7",

### Describe the problem:

Hello,

I m using a vue component named "SimplePagination.vue" to manage my pagination.
Inside this one, i m using the Translation component ().
Im facing the following error:
"[plugin:vite:vue] Codegen node is missing for element/if/for node. Apply appropriate transforms first."

I already spent several hours on the problem without finding a solution.
I deleted and reinstalled the node_modules folder, I tried the problematic code on another page and/or in another component, without any result.
As soon as I add the template slots inside the i18n-t component, the error appears.

On another project with vue 3 and without inertia, this code is working perfectly.

### Steps to reproduce:

```html
<i18n-t keypath="info"> <template v-slot:start> <span class="font-semibold">{{ totalItems === 0 ? '0' : currentPage === 1 ? '1' : Math.ceil(1 + (currentPage - 1) * itemPerPage) }}</span> </template> <template v-slot:end> <span class="font-semibold">{{ Math.min(currentPage * itemPerPage, totalItems) }}</span> </template> <template v-slot:total> <span class="font-semibold">{{ totalItems }}</span> </template> </i18n-t>
```

```html
const i18n = createI18n({
    locale: localStorage.getItem('locale') ?? 'fr',
    fallbackLocale: 'fr',
    globalInjection: true,
    messages
})

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, app, props, plugin }) {
        return createApp({ render: () => h(app, props) })
            .use(plugin)
            .use(Toast, { filterBeforeCreate })
            .use(ZiggyVue, Ziggy)
            .use(i18n)
            .mount(el);
    },
});
```

### Error
```
[plugin:vite:vue] Codegen node is missing for element/if/for node. Apply appropriate transforms first.
C:/laragon/www/doctor/resources/js/Components/pagination/SimplePagination.vue
    at assert (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:508:15)
    at genNode (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2642:13)
    at genNodeList (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2616:13)
    at genNodeListAsArray (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2601:5)
    at genNodeList (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2613:13)
    at genVNodeCall (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2784:5)
    at genNode (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2665:13)
    at genNode (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2644:13)
    at genNodeList (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2616:13)
    at genNodeListAsArray (C:\laragon\www\doctor\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2601:5
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

![screenshot here][1]

  [1]: https://i.stack.imgur.com/waCsk.png

**Comment by reinink** [comment] 2023-07-28 01:50
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:50 UTC
