### ISSUE TITLE
NProgress CSS included in the production JS bundle with includeCSS option set to false

### ISSUE THREAD

**Issue by AndrewSavetchuk** [inertiajs/inertia#1485] opened 2023-03-09 17:55 UTC
### Version:

- `@inertiajs/vue3` version: 1.0.2

### Describe the problem:

I created Inertia app with the following configuration:

```javascript
createInertiaApp({
  ...
  progress: {
    includeCSS: false,
    showSpinner: false,
  },
});
```

When I run `vite build` I can see the NProgress CSS being added to the final JavaScript bundle:

<img width="1047" alt="Screenshot 2023-03-09 at 12 52 13 PM" src="https://user-images.githubusercontent.com/14139435/224113856-52828752-2b21-43dd-b2bd-757da3b05ec8.png">

**Comment by SergkeiM** [comment] 2023-03-31 05:57
Hi @AndrewSavetchuk this is becuase `progress` is always imported in `createInertiaApp`

https://github.com/inertiajs/inertia/blob/5c9c2707dc5f2f1f36d8eff99d731b5e42dab021/packages/vue3/src/createInertiaApp.ts#L1

@reinink Maybe is better to remove the import from there and if someone needs it:

```js
import { setupProgress } from '@inertiajs/core'

createInertiaApp({
    progress: () => setupProgress(options),
})


//inside createInertiaApp

if (!isServer && progress) {
    progress()
}

```

**Comment by reinink** [comment] 2023-07-28 01:47
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:47 UTC
