### ISSUE TITLE
"Page lacks the HTML doctype"  devtools warning

### ISSUE THREAD

**Issue by jonagoldman** [inertiajs/inertia#1139] opened 2022-03-22 09:46 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:

Each time a modal is rendered I get this console warning from Lighthouse in Chrome Devtools:

`Page lacks the HTML doctype, thus triggering quirks mode.`

The issue seems to be that the modal `html` element is created without the `doctype` declaration:

https://github.com/inertiajs/inertia/blob/master/packages/inertia/src/modal.ts#L10

I think replacing `document​.​createElement​(​'html'​)` with `document.implementation.createHTMLDocument()` will fix the issue as it creates a valid html document (with doctype) instead of a regular element.

**Comment by jonagoldman** [comment] 2022-04-25 17:48
Yes this is about the modals in development, but still an issue nonetheless in my opinion.

**Comment by ninjaparade** [comment] 2022-04-25 19:37
Think you're standing alone on that one, but good on you for making sure the HTML is proper for a dev debugging tool!

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
