### ISSUE TITLE
Inertia resolves the page twice at first load

### ISSUE THREAD

**Issue by mhelaiwa** [inertiajs/inertia#1091] opened 2022-02-09 11:51 UTC
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue` version:0.8.0

### Describe the problem:

When open the page the first time, the code inside `resolve` function will execute twice.

### Steps to reproduce:

```
createInertiaApp({
    resolve: (name) => {
        const page = require(`./Pages/${name}`).default
        page.layout = page.layout || Layout
        return page
    },
    setup({ el, App, props, plugin }) {
        Vue.use(plugin)
        let vm = new Vue({
            render: h => h(App, props),
        }).$mount(el);
    },
})
```

**Comment by craigrileyuk** [comment] 2022-02-24 10:22
Mine's executing 3 times...

**Comment by reinvanimschoot** [comment] 2022-02-25 12:59
We are experiencing the same issue. I just tested with a fresh Rails/React project and I see the same behaviour. Anyone found any answer to this?

**Comment by rajan-parmar** [comment] 2022-03-10 10:00
I am also facing this issue with:
@inertiajs/inertia version: 0.11.0
@inertiajs/inertia-vue version:0.6.0

**Comment by reinvanimschoot** [comment] 2022-09-23 11:41
I tried to reproduce this issue in a new project using React, Rails and Inertia (bundled with Webpacker).

[The project can be found here](https://github.com/reinvanimschoot/inertia-react-rails-test)

Even in a newly built app, with the most recent versions of both Inertia and Inertia-rails, the page, without even providing it with props or using `usePage` is rendered twice.

The only solution that fixed the issue is to wrap the page function in `React.memo`. I haven't tried this in our production app so I don't know whether or not this results in other problems but at least the render only happens once.

Maybe this is something that Inertia could use under the hood?

**Comment by RationalFragile** [comment] 2022-11-19 17:18
Also facing this same issue. Any ideas how to fix it with vue3?

**Comment by BorisKM** [comment] 2023-01-20 21:18
The same..

**Comment by fatoskurtishi** [comment] 2023-07-15 01:44
Same here..
using inertia laravel react
`resolve: (name) =>
	resolvePageComponent(
		`./Pages/${name}.tsx`,
		import.meta.glob("./Pages/**/*.tsx"),
	),`
is called twice on initial load! any fix for this ?

**Comment by craigrileyuk** [comment] 2023-07-15 01:47
https://github.com/inertiajs/inertia/pull/1608 should resolve this issue if it's cleared for release

**Comment by fatoskurtishi** [comment] 2023-07-15 07:26
> #1608 should resolve this issue if it's cleared for release

my page components rendered 2 or 3 times and I thought that "resolveComponent" is doing it, but after this patch #1608 it dropped from 3 to 2 :) but still 2 renders. this is the console.log() by order.
1. resolve Patched app.tsx 
2. createInertiaApp setup app.tsx
3. root.render app.tsx
4. Welcome page Welcome.tsx
5. Welcome page Welcome.tsx

**Comment by reinink** [comment] 2023-07-28 01:54
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:54 UTC

**Comment by zcuric** [comment] 2024-05-23 10:37
@lepikhinb I've seen your contributions to the repository. This is still an outstanding issue and it happens to as well. Can you check it out? Is there a way I can help contribute?

**Comment by AlvesJorge** [comment] 2024-07-18 09:59
Bump. Happening to me too

**Comment by reinvanimschoot** [comment] 2024-10-24 14:25
Is there any update on this? Any solution or workaround?

**Comment by Dracula707** [comment] 2024-11-20 14:38
Same on vue3 seems if you don’t use template works fine?

**Comment by abdasis** [comment] 2024-12-06 22:16
same issuse

"@inertiajs/react": "^2.0.0-beta.3",
