### ISSUE TITLE
Uncaught (in promise) TypeError: can't access property "default", g2 is undefined Inertiajs 1.0.0

### ISSUE THREAD

**Issue by trevorpan** [inertiajs/inertia#1426] opened 2023-02-02 20:08 UTC
### Discussed in https://github.com/inertiajs/inertia/discussions/1425

<div type='discussions-op-text'>

<sup>Originally posted by **trevorpan** February  1, 2023</sup>
Hi,

I have a `"laravel/framework": "^9.48.0",` app using Vite, Jetstream.

When upgrading to `inertiajs 1.0.0` I receive this error in the console.

```
//app.js
import "./bootstrap";

// Import modules...
import { createSSRApp, h } from "vue";
import.meta.glob(["../images/**", "../fonts/**"]);

import { createInertiaApp } from "@inertiajs/vue3";
import VueMeta from "vue-meta";

// Components
import Welcome from "./Pages/Welcome/Welcome.vue";
import Layout from "./Shared/Layout.vue";
import { MediaLibraryAttachment } from "../../vendor/spatie/laravel-medialibrary-pro/resources/js/media-library-pro-vue3-attachment";
import { MediaLibraryCollection } from "../../vendor/spatie/laravel-medialibrary-pro/resources/js/media-library-pro-vue3-collection";

createInertiaApp({
  resolve: (name) => {
    const pages = import.meta.glob("./Pages/**/*.vue", { eager: true });
    return pages[`./Pages/${name}.vue`];
  },

  setup({ el, App, props, plugin }) {
    createSSRApp({
      render: () => h(App, props),
      components: {
        MediaLibraryAttachment,
        MediaLibraryCollection,
        Welcome,
        VueMeta,
      },
    })
      .use(plugin)
      .mount(el);
  },

  title: (title) =>
    title ? `${title} - Site Title` : "Site Title",

  progress: {
    color: "#4B5563",
    showSpinner: true,
  },
});
```
The error occurs on line 16 which is this `createInertiaApp({...` I really don't know what to do. g2 seems to be related to jquery, but I don't reference jquery. There's just nothing else that I can find to see why this is rendering a white page.

any ideas? 

here's a console.log of `createInertiaApp`
```
Promise { <state>: "pending" }
​
<state>: "rejected"
​
<reason>: TypeError: can't access property "default", g2 is undefined
​​
columnNumber: 161
​​
fileName: "http://[::1]:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=44353a1e"
​​
lineNumber: 6113
​​
message: `can't access property "default", g2 is undefined`
​​
stack: "I/r/<@http://[::1]:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=44353a1e:6113:161\npromise callback*r@http://[::1]:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=44353a1e:6113:148\nI@http://[::1]:5173/node_modules/.vite/deps/@inertiajs_vue3.js?v=44353a1e:6113:198\n@http://[::1]:5173/resources/js/app.js:16:28\n"
```

If we look at line 6113:
```
// @inertiajs_vue3.js
  let m2 = typeof window > "u", d = m2 ? null : document.getElementById(e), h3 = p || JSON.parse(d.dataset.page), r = (f) => Promise.resolve(o(f)).then((g2) => g2.default || g2), i = [], s = await r(h3.component).then((f) => n({ el: d, App: $2, props: { initialPage: h3, initialComponent: f, resolveComponent: r, titleCallback: l, onHeadUpdate: m2 ? (g2) => i = g2 : null }, plugin: E }));
```
and then where g2 is defined, there is no default? 

I could be wrong.

```
// @inertiajs_vue3.js line 6038
   let f = d(this.data()), g2 = { ...s, onCancelToken: (u) => {
      if (a = u, s.onCancelToken)
        return s.onCancelToken(u);
```

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
