### ISSUE TITLE
Unable to use History API within Inertia Event System

### ISSUE THREAD

**Issue by toxifiedmatrix** [inertiajs/inertia#1020] opened 2021-04-17 22:11 UTC
I need to set the url back to `/users` only if a condition satisfies, i.e. if the url has `page=1`, I am using history api to do that, but am unable to set the url to the required one. It is replacing it to `/users` then it reverts back again to `/users?page=1`. How this can be achieved using inertia?

![url query new](https://user-images.githubusercontent.com/65024122/115127921-e0ab6700-9ff7-11eb-9df7-afa266cba4b2.gif)

```
        mounted() {
            this.$inertia.on('start', (event) => {
                let currentUrl = event.detail.visit.url.toString();

                if(currentUrl.toString().includes('page=1')) {
                    window.history.replaceState('users', null, 'users')
                }
            })
        }
```

**Comment by reinink** [comment] 2023-07-28 01:58
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:58 UTC
Labels: vue 2
