### ISSUE TITLE
Launch server on node crashes

### ISSUE THREAD

**Issue by Stripeberry** [inertiajs/inertia#1442] opened 2023-02-09 16:30 UTC
### Version:

- `@inertiajs/vue2` version: 1.0.0

### Configs
 
server.js:
 
```js
const inertiaApp = require('@inertiajs/vue2')
const {createInertiaApp} = inertiaApp
const createServer = require('@inertiajs/vue2/server')
import Vue from 'vue'
import { createRenderer } from 'vue-server-renderer'

createServer(page =>
    createInertiaApp({
        page,
        render: createRenderer().renderToString,
        resolve: name => import(`./Pages/${name}.vue`),
        setup({ App, props, plugin }) {
            Vue.use(plugin)
            return new Vue({
                render: h => h(App, props),
            })
        },
    }),
)
```

webpack.mix.js:

```js
const path = require('path')
const mix = require('laravel-mix')
const webpackNodeExternals = require('webpack-node-externals')

mix
    .options({ manifest: false })
    .js('resources/ssr/server.js', 'public/ssr')
    .vue({ options: { optimizeSSR: true } })
    .alias({ '@': path.resolve('resources/js') })
    .webpackConfig({
      target: 'node',
      externals: [webpackNodeExternals()],
    })
```

### Steps to reproduce:
```
npm mix --mix-config=webpack.mix.js
node public/ssr/server.js
```

Same error with:
```
php artisan inertia:start-ssr
```

### Error
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: XXX\site\node_modules\@inertiajs\vue2\dist\index.js
require() of ES modules is not supported
: "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from XXX\site\node_modules\@inertiajs\vue2\package.json
```

**Comment by OrangePixelLtd** [comment] 2023-02-13 17:21
I'm getting this with React.
`Error [ERR_REQUIRE_ESM]: require() of ES Module /var/www/html/node_modules/@inertiajs/react/dist/index.js from /var/www/html/public/js/ssr.js not supported.`

**Comment by Slaak** [comment] 2023-02-15 15:56
I have the same error with vue 3.
`Error [ERR_REQUIRE_ESM]: require() of ES Module XXX/www/node_modules/@inertiajs/vue3/dist/index.js from XXX/www/public/build-ssr/inertia.js not supported.`

**Comment by BrayamValero** [comment] 2023-02-26 17:44
Same issue here.
- "vue": "^2.6.14"
- "vue-server-renderer": "<=2.6.14"
-  "@inertiajs/vue2": "^1.0.2"

```
module.exports = require("@inertiajs/vue2");
                 ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/vagrant/projects/######/node_modules/@inertiajs/vue2/dist/index.js
from /home/vagrant/projects/######/public/js/ssr.js not supported.
```

**Comment by Squishy123** [comment] 2023-03-06 14:32
I ran into a similar issue. I had to use Node experimental loaders to have compatability of both ES modules and CJS modules. If you're running Node v19 try this: 

1. Create a custom loader file (I grabbed this directly from Node.JS Examples): 
```
/**
 * Custom esm loader
 * Source: https://github.com/nodejs/loaders-test
 */
'use strict';


Object.defineProperty(exports, '__esModule', {
	value: true
});
exports.resolve = resolve;
var _nodeModule = require('node:module');
var _nodePath = require('node:path');
var _nodeProcess = require('node:process');
var _nodeUrl = require('node:url');
var _nodeUtil = require('node:util');
var _async = _interopRequireDefault(require('resolve/async.js'));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
const resolveAsync = (0, _nodeUtil.promisify)(_async.default);
const baseURL = (0, _nodeUrl.pathToFileURL)((0, _nodeProcess.cwd)() + '/').href;
async function resolve(specifier, context, next) {
	const {
		parentURL = baseURL
	} = context;
	if ((0, _nodeModule.isBuiltin)(specifier)) {
		return next(specifier, context);
	}

	// `resolveAsync` works with paths, not URLs
	if (specifier.startsWith('file://')) {
		specifier = (0, _nodeUrl.fileURLToPath)(specifier);
	}
	const parentPath = (0, _nodeUrl.fileURLToPath)(parentURL);
	let url;
	try {
		const resolution = await resolveAsync(specifier, {
			basedir: (0, _nodePath.dirname)(parentPath),
			// For whatever reason, --experimental-specifier-resolution=node doesn't search for .mjs extensions
			// but it does search for index.mjs files within directories
			extensions: ['.js', '.json', '.node', '.mjs', '.ts']
		});
		url = (0, _nodeUrl.pathToFileURL)(resolution).href;
	} catch (error) {
		if (error.code === 'MODULE_NOT_FOUND') {
			// Match Node's error code
			error.code = 'ERR_MODULE_NOT_FOUND';
		}
		throw error;
	}
	return next(url, context);
}
```

2. Run the generated SSR entry (from wherever you built it)
```
node --loader ./loader.js bootstrap/ssr/ssr.mjs
```

I also had to customize my Vite config to allow it to work with certain libraries (without ES module support e.g MUI), so this is what it ended up looking like:

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';
// eslint-disable-next-line import/no-unresolved
import { cjsInterop } from 'vite-plugin-cjs-interop';


export default defineConfig({
	// run in container config
	// server: {
	//     host: "0.0.0.0",
	//     hmr: {
	//         host: "localhost",
	//     },
	// },
	ssr: {
		noExternal: [
			'laravel-vite-plugin',
			'@inertiajs/react',
			'@inertiajs/core'
			//'@inertiajs/react/server',
		],
	},
	plugins: [
		cjsInterop({
			// List of CJS dependencies that require interop
			dependencies: [
				'@mui/material/**/*', '@mui/x-data-grid/**/*', '@mui/x-date-pickers/**/*', '@mui/icons-material/**/*', '@emotion/**/*'
			],
		}),
		laravel({
			input: 'resources/js/app.jsx',
			ssr: 'resources/js/ssr.jsx',
			refresh: true,
		}),
		react(),
	],
});
```

**Comment by StuartCreed** [comment] 2023-04-20 15:00
I am getting the same issue error with vue2

**Comment by tecbay** [comment] 2023-06-07 00:42
Is there any fix?

**Comment by KimhoutSam** [comment] 2023-06-08 22:25
I think it related to inertia in all of its package.json write {"type":"module"}

**Comment by reinink** [comment] 2023-07-28 01:48
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:48 UTC
