### ISSUE TITLE
Actions can only be applied to DOM elements, not components

### ISSUE THREAD

**Issue by diontron** [inertiajs/inertia#1105] opened 2022-02-21 07:18 UTC
I am using [Inertia](https://inertiajs.com/links) and [Sveltestrap](https://sveltestrap.js.org/?path=/story/components--navbar).

I am trying to add `use:inertia` to a `NavLink` component but I get the following error:

> Actions can only be applied to DOM elements, not components

Here is the code:

```
<script>
    import {inertia} from '@inertiajs/inertia-svelte'
    import {NavLink} from 'sveltestrap'
</script>

<NavLink href="/login" use:inertia>Login</NavLink>
```

Is there any way I can `use:inertia` on a non-DOM element (e.g. a component)?

**Comment by danmatthews** [comment] 2023-05-02 16:49
Hey!

This is a limitation of Svelte and not InertiaJS.

You can get around this by wrapping your `NavLink` component with a `<Link>` tag, or using the `use:inertia` directive INSIDE the `<NavLink>` component, or wrapping it in a <div> tag and using `use:inertia` on there.

Not ideal i know, but a limitation of the Svelte framework.

**Comment by reinink** [comment] 2023-07-28 01:53
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:53 UTC
Labels: svelte
