### ISSUE TITLE
Form submit synchronizes new data instead of sent ones

### ISSUE THREAD

**Issue by netpok** [inertiajs/inertia#1361] opened 2022-12-15 08:38 UTC
### Version:

- `@inertiajs/vue2` version: 0.8.0

### Describe the problem:

After a successful form submit the current data is synchronized so any changes between the submit and completion will be marked as pristine. My expected behavior is that the sent state will be the new default.

I checked out the source code it looks like the vue3 behaves the same. Also I think the react and svelte versions are not even synchronizing the defaults but I'm not well versed in those.

If needed I can submit a PR which fixes this in vue2 and vue3

### Steps to reproduce:

- Create a form with default `value: A`, change to `value: B` and submit it too a long response endpoint
- While the request is processing change to `value:  C`
- On completion the `isDirty` field will be marked false and the default will be `C` instead of `B`

**Comment by reinink** [comment] 2023-07-28 01:49
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:49 UTC
