### ISSUE TITLE
Data too big to add to state

### ISSUE THREAD

**Issue by MrAtiebatie** [inertiajs/inertia#940] opened 2021-10-15 13:27 UTC
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue3` version: 0.5.2

### Describe the problem:

I'm using vue.draggable.next to add a drag and drop functionality on my page. However, the object is too big to push to state.  I wouldn't mind not having a rememberedState for the page. Is there a possibility to disable this? I'm getting the following error:
```
Uncaught DOMException: Failed to execute 'replaceState' on 'History': #<Object> could not be cloned.
    at e.n.replaceState (http://localhost:8080/js/app.js:22:11758)
    at e.n.saveScrollPositions (http://localhost:8080/js/app.js:22:4660)
    at e.n.visit (http://localhost:8080/js/app.js:22:8724)
    at onClick (http://localhost:8080/js/app.js:10:8427)
    at callWithErrorHandling (http://localhost:8080/js/app.js:14874:22)
    at callWithAsyncErrorHandling (http://localhost:8080/js/app.js:14883:21)
    at HTMLDivElement.invoker (http://localhost:8080/js/app.js:16344:90)
```

### Steps to reproduce:

I can't share my project, unfortunately. If you grab an example of vue.draggable.next and implement inertia it will be the same though.

**Comment by claudiodekker** [comment] 2021-12-01 18:28
Hey @MrAtiebatie,

Do you have a small snippet that demonstrates how you're implementing this library? 

The `#<Object> could not be cloned.` part of the message kind of indicates to me that you're somehow trying to store it in the state, given that by default only the manually marked scroll regions and the server-provided inertia page details (props, url, version, component) are stored in history state if I'm not mistaken.

Thanks!

**Comment by MrAtiebatie** [comment] 2021-12-13 09:04
```html
<draggable
    v-model="pipelines"
    item-key="id"
    v-bind="draggableOptions"
    v-on="draggableOptions"
    class="relative flex h-full"
>
    <template #item="{ element }">
        <pipeline-card
            :key="element.id"
            :pipeline="element"
            class="inline-block px-3 w-80 h-full"
        ></pipeline-card>
    </template>
</draggable>
```

I managed to fix this bug with the following:

```vue
watch: {
    "$page.props.pipelines": {
        immediate: true,
        handler(value) {
            // This is a workaround for a bug from inertia
            // (see: https://githubmemory.com/repo/inertiajs/inertia/issues/775?page=2)
            if (typeof value !== "undefined") {
                this.clonedPipelines = JSON.parse(JSON.stringify(value));
            }
        },
    },
},
```

And then using clonedPipelines as v-model in the draggable component. Is this sufficient enough for you to have an idea where the bug might be related to?

**Comment by marcbelletre** [comment] 2022-05-24 15:05
Hi,

Did you try to change `v-model` to `:list` as proposed [here](https://github.com/inertiajs/inertia/issues/775#issuecomment-1062109906)?

At least it worked for me ;)

**Comment by reinink** [comment] 2023-07-28 01:56
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:56 UTC
Labels: vue 3
