### ISSUE TITLE
$page.props `undefined` in build mode

### ISSUE THREAD

**Issue by indygill** [inertiajs/inertia#1534] opened 2023-04-28 00:10 UTC
### Version:

- `@inertiajs/svelte` version: ^1.0.2
- `vite` version: ^4.0.0
- `@sveltejs/vite-plugin-svelte` version: ^2.0.4
- `laravel-vite-plugin` version: ^0.7.2

### Describe the problem:
Laravel 10 + Inertia + Svelte + Vite

I have two basic svelte components:

1. `resources/js/Pages/Test.svelte`
2. `node_modules/@ruco/dashboard-ui/js/Pages/Foo.svelte`

Both of these components import and use `import { page } from '@inertiajs/svelte';`

When running `npm run build` `Test.svelte` can access `$page.props` however `Foo.svelte` cannot - I just get `undefined` when trying to reference `$page.props`

When running `npm run dev` both `Test.svelte` and `Foo.svelte` can access `$page.props` no problem.

The HTML data attribute `data-page` is populated in both instances.

#### resources/js/dashboard.js
```js
import { createInertiaApp } from '@inertiajs/svelte';
import { DashboardPages } from 'ruco/dashboard/js/app.js';

const localPages = import.meta.glob('./Pages/**/*.svelte', { eager: true });

const pages = {
	...DashboardPages,
	...localPages
};

createInertiaApp({
	resolve: name => {
		return pages[`./Pages/${name}.svelte`]
	},
	setup({ el, App, props }) {
		new App({ target: el })
	},
})
```

#### resources/js/Pages/Test.svelte
```svelte
<script>
	import { page } from '@inertiajs/svelte';

	console.dir($page.props);
</script>
<h1 class="text-stone-600">Hello World!</h1>
```

#### node_modules/@ruco/dashboard-ui/js/app.js
```js
export const DashboardPages = import.meta.glob('./Pages/**/*.svelte', { eager: true });
```

#### node_modules/@ruco/dashboard-ui/js/Pages/Foo.svelte
```svelte
<script>
	import { page } from '@inertiajs/svelte';

	console.dir($page.props);
</script>
<h1 class="text-stone-600">Foo Bar</h1>
```

#### vite.config.js
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import path from 'path';

export default defineConfig({
    resolve: {
        alias: {
            svelte: path.resolve(__dirname, 'node_modules/svelte'),
            'ruco/dashboard': path.resolve(__dirname, 'node_modules/@ruco/dashboard-ui'),
        }
    },
    plugins: [
        laravel.default({
            input: ['resources/css/app.css', 'resources/js/app.js', 'resources/css/dashboard.css', 'resources/js/dashboard.js'],
            refresh: true,
        }),
        svelte()
    ],
});
```

**Comment by tcampbPPU** [comment] 2023-05-20 02:14
I am running into a similar issue with Vue & TS

- Laravel: `10.11.0`
- vue: `3.3.4`
- vue-tsc: `1.6.5`
- vite: `4.3.8`
- pnpm:  `8.4.0`

> This is from the Laravel Breeze using Laravel + Vue + TS
![image](https://github.com/inertiajs/inertia/assets/25044744/d0ce60d8-1b41-457f-ad60-fde25f62ef70)

**Comment by medeiroz** [comment] 2023-07-24 00:53
I have same issue with vue2

**Comment by reinink** [comment] 2023-07-28 01:38
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️

**Closed by reinink** 2023-07-28 01:38 UTC
Labels: svelte

**Comment by adiramardiani** [comment] 2024-02-25 02:33
Hi @tcampbPPU is your is issue is fixed, I have some problem too :(
- vue : 3.4.19
- vue-tsc : 1.8.27
- vite : 5.1.4
- @inertiajs/vue3 : 1.0.14

I install fresh using latest breeze,  I also trying new laravel 11 dev, and issue still the same. $page.props is dont have user and ziggy

Here my global.d.ts from breeze
``` typescript
import { PageProps as InertiaPageProps } from '@inertiajs/core';
import { AxiosInstance } from 'axios';
import { route as ziggyRoute } from 'ziggy-js';
import { PageProps as AppPageProps } from './';

declare global {
    interface Window {
        axios: AxiosInstance;
    }

    const route: typeof ziggyRoute;
}

declare module 'vue' {
    interface ComponentCustomProperties {
        route: typeof ziggyRoute;
    }
}

declare module '@inertiajs/core' {
    interface PageProps extends InertiaPageProps, AppPageProps {}
}

```

Here my index.d.ts from breeze
``` typescript
import { Config } from 'ziggy-js';

export interface User {
    id: number;
    name: string;
    email: string;
    email_verified_at: string;
}

export type PageProps<T extends Record<string, unknown> = Record<string, unknown>> = T & {
    auth: {
        user: User;
    };
    ziggy: Config & { location: string };
};

```

Here my type check

![image](https://github.com/inertiajs/inertia/assets/8703419/cc0b38af-2b40-4e0a-8e67-7475eaf74dbd)

Is my code have something wrong ?
Sorry I tag you also @reinink

**Comment by coffebar** [comment] 2024-06-07 12:11
It seems this issue is related to pnpm. I have it on pnpm and don't on npm
