### ISSUE TITLE
redirection to /dashboard after login does not work

### ISSUE THREAD

**Issue by albertopinilla** [inertiajs/inertia#1838] opened 2024-03-31 02:39 UTC
### Version:

- `@inertiajs/vue3` version: #.#.#

### Describe the problem:

I just installed Laravel 11 with the laravel new installer, using Laravel Breeze with Inertia.js and Vue 3. After creating the migrations and registering a user, I cannot log in. The exception that occurs is Illuminate\\Auth\\AuthenticationException: Unauthenticated, even though the credentials are correct. I notice that it makes a GET request to dashboard?%2Fdashboard, but it returns nothing.

### Steps to reproduce:

I did a clean installation with laravel new. The strange thing is that if I use a SQLite database, it works, but it doesn't work with MySQL.

**Comment by driesvints** [comment] 2024-04-02 08:23
Duplicate of https://github.com/inertiajs/inertia-laravel/issues/609. Please do not post on multiple repos.

**Closed by driesvints** 2024-04-02 08:23 UTC
